### ISSUE TITLE
[ActivityUpdate.Json]: While navigating Activity update screen, keyboard focus is landing on non-interactive elements. 

### ISSUE THREAD

**Issue by vagpt** [microsoft/AdaptiveCards#8104] opened 2022-12-06 04:59 UTC
### Target Platforms

Android

### SDK Version

2022.12.01.1 (60498133)

### Application Name

Adaptive Cards

### Problem Description

**Test Environment:**
Android Version: 13
App: Adaptive Cards Android Visualizer
App Version: 2022.12.01.1 (60498133)
Tool: Logitech Bluetooth Keyboard

**Repro Steps:**
1. Open Adaptive Cards Visualizer Application.
2. Navigate to sample cards using tab key and activate it using Enter key.
3. Navigate to the 'Choose Sample' combo box and press enter key to activate it.
4. Navigate to 'Activity Update' options and press enter key to activate it.
5. Press Shift+Tab key and navigate to the visual tab item and press enter key to activate it.
6. Navigate the sample card and observe the issue.

**Actual Result:**
Keyboard focus is landing on the non interactive element under activity update sample card. It is going on the non-interactive text.

**Expected Result:**
Keyboard focus should not go to the non-interactive text while navigating to the sample card.

**User Experience:**
Keyboard users would get affected if Keyboard focus moves to non interactive element in DatePicker under Due Date.

**MAS Reference:**
[Focus Order - Liquid (microsoft.com)](https://liquid.microsoft.com/Web/Object/Read/MS.Accessibility/Requirements/02.04.03)

"Have feedback to share on Bugs ? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-apoorva%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400998658942%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=l6w0SvVcMSvyGnJ6%2B6uSSgd3braF2dZ7/AdBrqqzIR8%3D&reserved=0) “,

### Screenshots

https://user-images.githubusercontent.com/95913748/205819756-9025639e-804f-40f0-abc4-4a8af185bf7e.mp4

### Card JSON

```JSON
NA
```

**Comment by jwoo-msft** [comment] 2022-12-13 00:19
duplicate of #7959 
please re-open it if you think otherwise.

**Closed by jwoo-msft** 2022-12-13 00:19 UTC
Labels: Bug, Area-Renderers, Area-Accessibility, A11ySev3, A11yWCAG, HCL-E+D, HCL-AdaptiveCards-Android
