### ISSUE TITLE
Action.Submit not work in angular 6 

### ISSUE THREAD

**Issue by vidhema** [Microsoft/AdaptiveCards#2185] opened 2018-11-26 08:28 UTC
Hello Developers,

I'm use adaptive card in angular 6 so action submit not working. Can you help any one to submit action and how to do work with and filtered data from AzureChatbot.

I used the following  code but not working:
constructor() {
    this.adaptiveCard = new AdaptiveCards.AdaptiveCard();

   }

  ngOnInit() {
  	// this.adaptiveCard = new AdaptiveCards.AdaptiveCard();
//   	this.adaptiveCard.hostConfig = new AdaptiveCards.HostConfig({
//     fontFamily: "Segoe UI, Helvetica Neue, sans-serif"
//     // More host config options
// });
 
// Set the adaptive card's event handlers. onExecuteAction is invoked
// whenever an action is clicked in the card
this.adaptiveCard.OnSubmit = function(action) { alert("Ow!"); }
 
// For markdown support you need a third-party library
// E.g., to use markdown-it, include in your HTML page:
//     <script type="text/javascript" src="https://unpkg.com/markdown-it/dist/markdown-it.js"></script>
// And add this code to replace the default markdown handler:
//     AdaptiveCards.processMarkdown = function(text) { return markdownit().render(text); }
 
// Parse the card payload
this.adaptiveCard.parse(this.cardsValue);
 
// Render the card to an HTML element:
this.renderCards = this.adaptiveCard.render();
this.cards.nativeElement.innerHTML=this.renderCards.innerHTML;

// this.innerHTMLVal=this.renderCards;
//  this.item = this.renderCards;;
console.log('carddss');
console.log(this.renderCards)
      console.log(this.cardsValue)
  }
.....................................
{"type":"AdaptiveCard","version":"1.0","body":[{"type":"TextBlock","text":"Month"},{"type":"Input.ChoiceSet","id":"month","value":"1","style":"compact","isMultiSelect":false,"choices":[{"title":"Jan","value":"Jan"},{"title":"Feb","value":"Feb"},{"title":"Mar","value":"Mar"},{"title":"Apr","value":"Apr"},{"title":"May","value":"May"},{"title":"Jun","value":"Jun"},{"title":"Jul","value":"Jul"},{"title":"Aug","value":"Aug"},{"title":"Sep","value":"Sep"},{"title":"Oct","value":"Oct"},{"title":"Nov","value":"Nov"},{"title":"Dec","value":"Dec"}],"placeholder":"select"}],"actions":[{"type":"Action.Submit","data":{"type":"submit"},"title":"Submit"}]}

this json strigy data use to create adaptive card...card created successfully but submit action not working.

**Comment by khouzam** [comment] 2018-11-26 18:14
Duplicate of #2186

**Closed by khouzam** 2018-11-26 18:14 UTC
