### ISSUE TITLE
Bot Builder v4 IgnoreEmptyItemsConverter causes an issue when ReadJson

### ISSUE THREAD

**Issue by kenakamu** [microsoft/AdaptiveCards#2148] opened 2018-11-05 03:11 UTC
# Platform
Bot Builder v4.0 (dotnet core)

# Author or host
web api (Bot Framework)

# Version of SDK
1.1

# Issue
When deserialize the DialogState which contains the AdaptiveCard, it fails with error "Error reading JArray from JsonReader at 

var array = JArray.Load(reader);. 

Error: Current JsonReader item is not an array: StartObject. Path 'DialogState.DialogStack.$values[0].State.dialogs.DialogStack.$values[0].State.options.Prompt.attachments.$values[0].content.action"

This caused by [JsonConverter(typeof(IgnoreEmptyItemsConverter<AdaptiveAction>))] attribute on AdaptiveCard which will be called while deserialization but it's not actually an array yet, as $value holds an array not action (nor body)

```json
"actions": {
    "$type": "System.Collections.Generic.List`1[[AdaptiveCards.ActionBase, AdaptiveCards]], System.Private.CoreLib",
    "$values": [
    {
        "$type": "AdaptiveCards.SubmitAction, AdaptiveCards",
        "type": "Action.Submit",
        "data": "Test",
        "title": "Test"
    }
    ]
}
```
We should try/catch JArray.Load

**Comment by tusharvaja** [comment] 2018-11-16 07:50
I am also getting error while returning an adaptive card with many buttons. error comes in var dc = await Dialogs.CreateContextAsync(turnContext) line.  Error: Error reading JArray from JsonReader. Current JsonReader item is not an array: StartObject. Path 'DialogState.DialogStack.$values[0].State.dialogs.DialogStack.$values[0].State.options.Prompt.attachments.$values[0].content.body'.


Any solutions?

**Comment by paulio** [comment] 2018-11-25 11:36
The workaround I'm currently using is to SendActivityAsync the Card and then issue a small text prompt, "please make a selection". You can then add a validator to examine the Activity.Value

**Comment by paulcam206** [comment] 2018-11-27 03:34
So I think I have a couple of approaches to solve this problem. I've been able to reproduce the issue outside of the Bot Framework. However, I think it'd be helpful to know what the payload looks like so I can figure out what the right fix should look like. For example here's a card that repros the same exception:

```JSON
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
	],
	"actions": {
			"type": "Action.OpenUrl",
			"url": "http://adaptivecards.io"
	}
}
```
(note that `actions` is an object -- not an array)

the same card with the action section being an array works fine:

```JSON
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
	],
	"actions": [
		{
			"type": "Action.OpenUrl",
			"url": "http://adaptivecards.io"
		}
	]
}
```

**Comment by v-kydela** [comment] 2018-12-02 23:45
Here's an easy way to repro the issue in a console app:

```c#
var card = new AdaptiveCard
{
	Body = { new AdaptiveTextBlock() },
	Actions = { new AdaptiveSubmitAction() },
};

var js = new JsonSerializer() { TypeNameHandling = TypeNameHandling.All };
var obj = JObject.FromObject(card, js).ToObject<object>(js);
```

Note that the problem only occurs if you pass to `FromObject` a `JsonSerializer` with `TypeNameHandling.All` because otherwise the object won't be serialized as an AdaptiveCard and therefore won't use the `IgnoreEmptyItemsConverter` upon deserialization. This of course hints at a good workaround. All you have to do is bypass the AdaptiveCards package when adding the card as an attachment, i.e. send it as a normal object (and not an AdaptiveCard) using the serialize/deserialize trick: `Content = JsonConvert.DeserializeObject(JsonConvert.SerializeObject(card))`

Obviously we shouldn't have to do this so `IgnoreEmptyItemsConverter` should be fixed. I'm happy to fix it myself if someone could explain to me what purpose it's meant to serve in the first place.

**Comment by satyansh-sagar** [comment] 2019-02-12 10:39
Attachment attachment = new Attachment()
{
	ContentType = AdaptiveCard.ContentType,
	Content = JsonConvert.DeserializeObject(JsonConvert.SerializeObject(AdpCard)),
};

**Comment by khouzam** [comment] 2019-02-13 18:17
Hi @v-kydela,

In your example actions is an object and not an array. The AdaptiveCards schema specifies that Actions need to be an array and this might be why you're seeing this failure.

**Comment by v-kydela** [comment] 2019-02-13 19:05
@khouzam - It might look that way if you're unfamiliar with C#. But actually that syntax can be used to initialize enumerable types in C#, and indeed C# is a strongly-typed language so it would be impossible to assign a non-array object to `Actions`.

Thank you for your help but I already know exactly why I'm seeing the failure. There's a bug in the AdaptiveCards source code, as we've said. We're commenting on an open-source repo so we can see exactly where the faulty code is.

**Comment by dclaux** [comment] 2019-02-13 19:26
The problem is that the actions property must be specified as an array in the json payload. I don't think there is a bug in Adaptive Cards.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by v-kydela** [comment] 2019-02-13 19:59
@dclaux - Thank you for the comment but that is also incorrect. I've already shown in my earlier comment that this issue can be reproduced in a non-bot console app without any payload being sent anywhere. If there was no bug in the AdaptiveCards source code then we wouldn't be able to work around the issue by bypassing the AdaptiveCards code with the serialize/deserialize trick: `JsonConvert.DeserializeObject(JsonConvert.SerializeObject(card))`

**Comment by dclaux** [comment] 2019-02-13 22:12
@v-kydela please provide the payload that is being parsed, as @paulcam206 asked. That will help us understand what's going on and what the appropriate fix is, if a fix is needed. We have no doubt you are able to debug our code, but from my viewpoint:

If your payload defines `actions` as follows:
```
"actions": {
    "type": "Action.OpenUrl",
    "url": "http://adaptivecards.io"
}
```

then you have an invalid payload. The `actions` property is an array and specifying it as an object should not and will not work, in any of our renderers.

If however your `actions` property is correctly specified as an array as follows:
```
"actions": [
    {
        "type": "Action.OpenUrl",
        "url": "http://adaptivecards.io"
    }
]
```

then there is definitely a bug that needs fixing.

**Comment by v-kydela** [comment] 2019-02-13 23:16
@dclaux - Thank you for the reply.

I've made a slight modification to my sample from earlier so that you can see what lies in the intermediate step between `JObject.FromObject` and `JObject.ToObject` and that reveals that the reason `actions` is an object is because of the `TypeNameHandling`. In order to preserve the type names of the original C# objects, the `JsonSerializer` wraps each array in an object:

```c#
var card = new AdaptiveCard
{
	Body = { new AdaptiveTextBlock() },
	Actions = { new AdaptiveSubmitAction() },
};

Console.WriteLine(JsonConvert.SerializeObject(card));
// Output:
//	{
//		"type": "AdaptiveCard",
//		"version": "1.1",
//		"body": [
//			{
//				"type": "TextBlock",
//				"text": " "
//			}
//		],
//		"actions": [
//			{
//				"type": "Action.Submit"
//			}
//		]
//	}

var js = new JsonSerializer() { TypeNameHandling = TypeNameHandling.All };
var jObject = JObject.FromObject(card, js);

Console.WriteLine(jObject.ToString());
// Output:
//	{
//		"$type": "AdaptiveCards.AdaptiveCard, AdaptiveCards",
//		"type": "AdaptiveCard",
//		"version": "1.1",
//		"body": {
//			"$type": "System.Collections.Generic.List`1[[AdaptiveCards.AdaptiveElement, AdaptiveCards]], mscorlib",
//			"$values": [
//				{
//					"$type": "AdaptiveCards.AdaptiveTextBlock, AdaptiveCards",
//					"type": "TextBlock",
//					"text": " "
//				}
//			]
//		},
//		"actions": {
//			"$type": "System.Collections.Generic.List`1[[AdaptiveCards.AdaptiveAction, AdaptiveCards]], mscorlib",
//			"$values": [
//				{
//					"$type": "AdaptiveCards.AdaptiveSubmitAction, AdaptiveCards",
//					"type": "Action.Submit"
//				}
//			]
//		}
//	}

var obj = jObject.ToObject<object>(js);
// Newtonsoft.Json.JsonReaderException:
// 'Error reading JArray from JsonReader. Current JsonReader item is not an array: StartObject. Path 'body'.'
```

Please run this code yourself to reproduce the error. You can see when the card is serialized without type names that the card's body and actions are both arrays (they couldn't possibly not be because C# is strongly-typed). However, when that same card is serialized with type names the arrays are wrapped in objects. Since there is nothing wrong with the way the card is defined (it's constructed with the C# code from this repo) there is a bug in the repo, as you've said.

The expected behavior is for the AdaptiveCards custom deserialization to complete without error even when an Adaptive Card has been serialized with `TypeNameHandling` set to `All`, as it is in the BotBuilder v4 dialog code.

I hope this helps!

**Comment by dclaux** [comment] 2019-02-13 23:44
Thnk you, this helps.

So it looks like the problem is the Adaptive Card object model isn't fully compatible with NewtonSoft's JSON serialization/deserialization algorithm when TypeNameHandling.All is used. Namely, an AdaptiveCard object cannot be round-tripped (FromObject then ToObject) in TypeNameHandling.All mode.

I'll leave it to @khouzam and @paulcam206 from here (maybe they had already understood all this for that matter.)

**Comment by shalinijoshi19** [comment] 2019-04-22 21:43
@Paulcam206, please repage-in once you are through 1.2 backlog

**Comment by PriyankTUV** [comment] 2019-10-03 05:18
Solution Worked for me ... 

 public static Attachment ToAdaptiveCard(this AdaptiveCard card)
        {
            var adaptiveCardJson = JsonConvert.SerializeObject(card);
            return new Attachment()
            {
                ContentType = "application/vnd.microsoft.card.adaptive",
                Content = JsonConvert.DeserializeObject(adaptiveCardJson),
            };
        }

**Comment by arman-g** [comment] 2019-11-27 19:06
Do you have a timeline when this is going to be fixed? Thanks

**Comment by hansmbakker** [comment] 2020-05-11 16:04
@khouzam @shalinijoshi19 @paulcam206 

I think this code is at least a workaround for `IgnoreEmptyItemsConverter`:
```csharp
JArray array;
if (objectType.IsGenericType && (objectType.GetGenericTypeDefinition() == typeof(List<>)) && reader.TokenType == JsonToken.StartObject)
{
    dynamic wrappedArray = JObject.Load(reader);
    array = wrappedArray["$values"];
}
else
{
    array = JArray.Load(reader);
}
```

Can you please help fix this in Nuget, as bots that use this library break when this is not patched: https://github.com/microsoft/botbuilder-dotnet/issues/2456#issuecomment-626766819

**Comment by v-kydela** [comment] 2020-05-11 16:31
@hansmbakker - While this bug should certainly be fixed in the Adaptive Cards .NET SDK, it is still possible to get your bots to work by bypassing the SDK. The workaround people have been using is to convert their Adaptive Cards to JObjects before attaching them to activities.

**Comment by hansmbakker** [comment] 2020-05-11 16:43
@v-kydela now I see, thank you!

**Closed** 2021-11-04 23:06 UTC
Labels: Bug, Platform-.NET
