### ISSUE TITLE
issue in Input.Date control in adaptive cards

### ISSUE THREAD

**Issue by Vishnuvk33** [microsoft/AdaptiveCards#4186] opened 2020-06-16 06:40 UTC
we have created an adaptive card for outlook with Input.Date field and one http.action.

On click of  http.action , we are always getting the date from input.date filed as one day before.

For ex, if we set 13 may 2020 in date field, we are always getting 12 may 2020 as api input.

Channel :  O365

Any thing need to be given in Input.Date fiels?

**Comment by shalinijoshi19** [comment] 2020-06-18 23:51
@dclaux for FYI on this one. @Vishnuvk33 can you please share out your card payload here? Also it would be great if in the future you could use our [Bug Template](https://github.com/microsoft/AdaptiveCards/issues/new?assignees=&labels=Bug&template=bug_report.md&title=%5BPlatform%5D%5BBroad+Issue+Category+if+applicable+%28eg+Accessibility%29%5D+%5BBug+Title%5D) to file bugs for us with more details! Thanks

**Comment by dclaux** [comment] 2020-06-18 23:59
@Vishnuvk33 could you indee share a card payload as well as:
- Which Outlook version you're referring to (Windows, OWA, iOS, Android?)
- The time zone configured on the system running Outlook

"13 may 2020" basically means "13 may 2020 at 0:00 in the system's time zone". If the system's time zone is, for instance, set to Central European Summer Time, or GMT+2, "13 may 2020 at 0:00 GMT+2" converts into "12 may 2020 at 22:00 GMT", e.g. the previous day.

**Comment by Vishnuvk33** [comment] 2020-06-19 04:29
@dclaux  have uploaded the json flle in this.

1. we are using outloook windows 0365
2.  The timezone configured in the outlook is IST

[customer_card.txt](https://github.com/microsoft/AdaptiveCards/files/4802438/customer_card.txt)

**Comment by Vishnuvk33** [comment] 2020-06-19 04:35
Yeah sure @shalinijoshi19 , will follow the mentioned steps to report bugs.

**Comment by dclaux** [comment] 2020-06-19 06:04
@Vishnuvk33 the team was able to repro and is investigating.

**Comment by Vishnuvk33** [comment] 2020-06-22 05:16
Hi @dclaux , Any update on this issue.

**Comment by dclaux** [comment] 2020-06-22 15:24
The problem has been identified and a fix will be implemented. It's a server-side fix so it won't require an Outlook update. I don't have an ETA.

**Comment by Vishnuvk33** [comment] 2020-06-23 06:00
Hi @dclaux  Thanks for the update.

**Comment by Vishnuvk33** [comment] 2020-06-23 13:19
Hi @dclaux what is the fix which is implemeted.

Can you please just describe it.

The Date filed will always consider the Current date time.

For example we are in IST and the date time is 23-06-2020 18:45:00

And the user make the changes in Date field and set it as 22-06-2020

What time i will get to back end ?

It is either 22-06-2020 01:15:00 or 21-06-2020 06:30:00

**Comment by dclaux** [comment] 2020-06-23 17:59
@Vishnuvk33 I'm going to use "23-06-2020 at 2:30 in the morning IST" as it illustrates the principle better: 

At the protocol level, you will get a fully formed date/time, e.g. a date with a time offset. We're still debating whether we format it (if you have an opinion let us know):
- In the local time zone from the machine the date was selected, i.e. `"2020-06-23T02:30+5:30"`
- Or in GMT: `"2020-06-22T21:00Z"`

Note that the GMT version is the day before, but it remains that the two are 100% equivalent. Plus it shouldn't make any difference to you anyway. You are likely using the Date class of whichever framework/language your backend is implemented in, and that class will automatically convert whatever it receives into a local date/time. So assuming your backend also uses IST, it will "see" 23-06-2020 at 2:00 in the morning

**Comment by Vishnuvk33** [comment] 2020-06-24 10:35
@dclaux  Thanks for the update.

**Comment by shalinijoshi19** [comment] 2020-06-26 14:31
@dclaux do you have a link to the Exchange

> The problem has been identified and a fix will be implemented. It's a server-side fix so it won't require an Outlook update. I don't have an ETA.

Hey @dclaux can you reference the exchange/office-side ticket # here for tracking that the customer can visit or use to track this issue ? Alternatively would you be able to update the bug once the fix has been deployed? Thanks

**Comment by dclaux** [comment] 2020-06-30 15:31
@Vishnuvk33 the issue has been fixed server-side. The fix should be deployed in about two weeks.

**Comment by Vishnuvk33** [comment] 2020-07-09 11:52
Hi @dclaux  can you please describe, what fix is deployed in server side.

For Ex:  We need to use date time control in adaptive cards designer instead of date control.

Please just describe how the fix work.

**Comment by dclaux** [comment] 2020-07-09 15:20
@Vishnuvk33 I have explained the fix in a previous comment above. I do not know if the team went with local or GMT, but again that should make zero difference to you. You can continue using the Date control as before.

**Comment by Vishnuvk33** [comment] 2020-07-09 15:25
Yes thanks @dclaux .
But i also have raised another one issue [https://github.com/microsoft/AdaptiveCards/issues/4214](url) to record backdated data.
You closed that issue and mentioned that fix for this issue is same as [https://github.com/microsoft/AdaptiveCards/issues/4186](url)
So What about recording backdated record.
We need combination of both date and time controls as a single control to get both date and time as GMT.

**Comment by dclaux** [comment] 2020-07-10 16:08
@Vishnuvk33 I have explained in https://github.com/microsoft/AdaptiveCards/issues/4214 that if you need to record the time you can use both a Date input as well as another input for the time. I suggested using a ChoiceSet.

**Comment by Vishnuvk33** [comment] 2020-07-15 09:19
Hi @dclaux , As our organization and our customers are most interested to use adaptive cards,
We need a combination of both date and time control for backdated data.
if we use choiseset for time control, the choiseset will give the same value to backend what the user selected.
But the back end don't know, which timezone data coming from.
If we have a control with both date and time means, user can provide both date and time in a single control and then the given data will be converted to UCT or GMT, then we can make the changes in back end as per the timezone.
Please consider this comment.
And also how we know that , the fix for this issue is deployed in server side. is there any tagging for this .
Thanks,
Vishnukumar M

**Comment by dclaux** [comment] 2020-07-15 15:52
@Vishnuvk33 you are right. What I meant was that you could make the assumption that the time from the ChoiceSet was expressed in the same time zone as the date, but the problem is you don't know what that time zone was when you receive the time value. So you do need an actual Time input that also includes a TZ offset.

So here is where we are:
- Technically, Adaptive Cards include an `Input.Time` element. But Outlook currently doesn't support it. To satisfy your need, Outlook would have to add support. I will ping the team again to get the conversation started. Please understand though that even if the team commits to doing it it will take a while before it is available across Outlook clients
- The existing Input.Time control currently doesn't do the right thing. The time value it provides is in the "HH:mm" format, when it should be a fully qualified date/time, e.g. "MM-DD-YYYYTHH:mm<TZ offset>". The AC team will be looking into this.

**Comment by Vishnuvk33** [comment] 2020-07-16 09:57
@dclaux  thanks for the update and your guidance.

**Comment by slakkanp** [comment] 2020-08-24 07:58
@Vishnuvk33 We are now sending date in this format (`YYYY-MM-DDThh:mm:ssTZD`) from clients like windows and ios. This format includes local timezone. Example - `2020-08-13T00:00:00+0530`

I am assuming that you need Date+Time input control on Outlook Actionable Messages. 

You can use the date coming in the date field in the above format, and time from the choice set solution (for now) suggested by @dclaux, and timezone from the date field. Using all above and combining them, you can have a fully formed date. 

Does this work for you?, for now, because actionable messages on Outlook doesn't support Input.Time field.

**Closed** 2021-09-09 20:38 UTC
Labels: Bug, Resolution-External
