### ISSUE TITLE
[JS][MsTeams] Click-to-call hyperlinks in Action.OpenUrl buttons don't work in MS Teams

### ISSUE THREAD

**Issue by mrestorff** [microsoft/AdaptiveCards#3905] opened 2020-04-06 11:45 UTC
# Platform

What platform is your issue or question related to? (Delete other platforms).

* JavaScript

# Author or host
* Author

If you're an author, who are you sending cards to?
* MS Teams

# Version of SDK
npm 1.2.5

# Details

When sending an adaptive card with an Action.OpenUrl button from a bot (using MS Bot Framework), click-to-call hyperlinks ('tel:+12345') do not work in MS Teams - neither the Web Client nor the Desktop client. They do work in the MS Teams Android client and the WebChat however.

The Teams desktop client does nothing at all when the button is clicked while the Teams web client opens a new tab with the Teams web client on the exact same conversation.
The same hyperlink embedded in a simple text message works flawlessly on all Teams clients.

The Button is embedded in an _ActionSet_ that has no other members but this button.
```
"items": [{
    "type": "ActionSet",
        "actions": [{
            "type": "Action.OpenUrl",
            "title": "Call me",
            "url": "tel:+99 9999 9999"
        }]
}]
```

This could be related to #3614

**Comment by shalinijoshi19** [comment] 2020-04-17 16:01
@mrestorff let me follwo up on this one via #3614 .. I;ll resolve this one as a duplicate of that for now and if you could start to follow 3614 that would be great. Thanks again.

**Comment by shalinijoshi19** [comment] 2020-04-22 22:48
Dup of #3614

**Closed** 2020-04-22 22:47 UTC
Labels: Bug, Duplicate, MSTeams-Developer-Support, MsftTeams-Integration, Resolution-Duplicate
