### ISSUE TITLE
[Teams/Android][Formatting/JSON Issue] Unable to Mention someone when using Post Adaptive Card to User and Wait for Response

### ISSUE THREAD

**Issue by SeanFBrampton** [microsoft/AdaptiveCards#5342] opened 2021-02-01 17:30 UTC
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] Desktop
- [ ] Android
- [ ] iOS

# Author or host
Authoring - Using Power Automate for compose cards.

If you're an author, who are you sending cards to? - Sending Cards to Internal staff, using Teams Web/Desktop/Android/iOS

# Version of SDK

Unknown - Teams Default

# Details

When using Action "Post an Adaptive Card to a Teams User and Wait for a Response", the @mention feature doesn't work.  When using the same code in "Post an Adaptive Card to a Teams User" Action, the mention does work.

**Comment by jonmill** [comment] 2021-05-27 20:17
Dupe of #5739

**Closed by jonmill** 2021-05-27 20:17 UTC
Labels: Bug, Triage-Investigate

**Comment by SeanFBrampton** [comment] 2021-05-28 11:47
Not a Dupe.  This is a completely separate issue.  The issue isn't in documentation, but in the actual performance.  

It hasn't been possible to @mention someone in this very specific action card.

**Comment by jonmill** [comment] 2021-05-28 23:39
@SeanFBrampton - this is an issue for Teams specifically, which is described here: https://github.com/MicrosoftDocs/msteams-docs/issues/3202. This thread should help describe how to @ mention someone using an Adaptive Card in Teams. I apologize for not being clear earlier

**Comment by SeanFBrampton** [comment] 2021-05-31 11:47
@jonmill ,

Can you review the details of the issue?   "When using Action "Post an Adaptive Card to a Teams User and Wait for a Response", the @mention feature doesn't work. When using the same code in "Post an Adaptive Card to a Teams User" Action, the mention does work."

This isn't about figuring out who to send it to and how, this is about correctly trying to mention someone and literally copying the code and not having it work.

This isn't platform to platform but action to action.
