### ISSUE TITLE
For "column" component, the UI is different when set "width" = "auto" in IOS platform

### ISSUE THREAD

**Issue by FelixZhang-yong** [microsoft/AdaptiveCards#3192] opened 2019-07-11 03:34 UTC
# Platform

* iOS

# Author or host

No

# Version of SDK

IOS v1.2.0

# Issue

For "column" component, the UI is different when set "width" = "auto" in IOS platform
For the same payload
```
{
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "Container",
      "items": [
        {
          "type": "ColumnSet",
          "columns": [
            {
              "type": "Column",
              "width": "auto",
              "items": [
                
              ]
            },
            {
              "type": "Column",
              "width": "auto",
              "items": [
                {
                  "type": "TextBlock",
                  "size": "medium",
                  "weight": "bolder",
                  "text": "title"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

Other platform rendered as
<img width="420" alt="屏幕快照 2019-07-11 上午10 51 46" src="https://user-images.githubusercontent.com/52741892/61020276-b878e800-a3cf-11e9-8d59-132b5e394793.png">
But in IOS, it is rendered as 
<img width="329" alt="屏幕快照 2019-07-11 上午11 26 04" src="https://user-images.githubusercontent.com/52741892/61020286-c4fd4080-a3cf-11e9-9d9c-5665f836e8eb.png">

**Comment by nesalang** [comment] 2019-07-12 17:23
Hello @FelixZhang-yong 
Thanks for the feedback.
I tried your json, I could reproduce the issue, and this inconsistency is caused by the empty column. Is there a need for this use case?

**Comment by FelixZhang-yong** [comment] 2019-07-13 06:53
I intended to simplify the issue with previous payload. Below is the sample payload for the use case we meet. We want to show an image in the left and place name & title on the right of the image.
{
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "Container",
      "items": [
        {
          "type": "ColumnSet",
          "columns": [
            {
              "type": "Column",
              "width": "auto",
              "items": [
                {
                  "type": "Image",
                  "size": "small",
                  "style": "person",
                  "url": "https://pbs.twimg.com/profile_images/3647943215/d7f12830b3c17a5a9e4afcc370e3a37e_400x400.jpeg"
                }
              ]
            },
            {
              "type": "Column",
              "width": "auto",
              "items": [
                {
                  "type": "TextBlock",
                  "size": "medium",
                  "weight": "bolder",
                  "text": "name"
                },
                {
                  "type": "TextBlock",
                  "size": "small",
                  "text": "title",
                  "spacing": "none",
                  "separation": "none"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}

For other platform, the UI would be:
<img width="429" alt="屏幕快照 2019-07-13 下午2 49 20" src="https://user-images.githubusercontent.com/52741892/61168266-f74ca080-a57d-11e9-889d-34d8bb1daaac.png">

But on IOS platform, the UI is as below:
<img width="351" alt="屏幕快照 2019-07-13 下午2 48 26" src="https://user-images.githubusercontent.com/52741892/61168278-07fd1680-a57e-11e9-9ac7-54cb6225c4a9.png">

**Comment by nesalang** [comment] 2019-07-15 22:07
thanks for the payload

**Comment by nesalang** [comment] 2019-07-15 23:16
fixed by #3232

**Comment by FelixZhang-yong** [comment] 2019-07-16 01:44
Got it, Thanks.

**Comment by FelixZhang-yong** [comment] 2019-07-29 06:23
@nesalang , I find the fix has been merged. Do you know when would the new adaptive card framework be generated and what version it is (like 1.2.1)?

**Comment by nesalang** [comment] 2019-07-29 17:15
@FelixZhang-yong, it will be part of the next release (1.2.1). it will be 7/31.

**Closed** 2019-07-29 18:21 UTC
Labels: Bug, Platform-iOS, Potential-1.2.1, Status-In Code Review, Triage-Approved for Fix
