### ISSUE TITLE
Dynamic Table not working with $data

### ISSUE THREAD

**Issue by Bngo15** [microsoft/AdaptiveCards#5370] opened 2021-02-09 01:00 UTC
Hello,

Trying to run the code example outlined in this blog post, but I'm running into issues with the $data portion of the payload.

The card is returning null values.

The payload I'm intending to pass to this is coming from an internal API and follows the output as outlined.

More information:

I'm using the Botframework for Visual Studio and my Adaptive Card template is done in the LG file.

---
* URL: https://adaptivecards.io/blog/2020/Templating-RC/

**Comment by Bngo15** [comment] 2021-02-09 01:00
I can provide more info if needed or can get on a call.

**Comment by jwoo-msft** [comment] 2021-02-09 18:13
@Bngo15,
 Is it your first time using the template and AdaptiveCards? Can you post your payload, so I can try? I can at least verify if it works on our SDK.

**Comment by Bngo15** [comment] 2021-02-11 15:36
Yes it is. I have put it in the designer https://adaptivecards.io/designer/

{
    "testData": [
        {
            "Balance": "15",
            "Units": "bread"
        },
        {
            "Balance": "21",
            "Units": "eggs"
        },

    ]
}

It showed up fine there, but doesn't work in my Virtual Assistant bot. The bot was made using the template.

An alternative approach was tried using a .json template for the card and then passing it through the Attachment class. This provided positive results.

I'm just a little confused as to why the method of using GenerateActivityForLocale and passing the data through this card returned null.

**Comment by Bngo15** [comment] 2021-02-11 15:37
Submitting my previous comment seems to have messed with the format.

I uploaded it here as a text document.

[testPayload.txt](https://github.com/microsoft/AdaptiveCards/files/5966478/testPayload.txt)

**Comment by jwoo-msft** [comment] 2021-02-11 18:04
@Bngo15,

Can you also share your template?

**Comment by Bngo15** [comment] 2021-02-11 18:58
[testCard.txt](https://github.com/microsoft/AdaptiveCards/files/5967815/testCard.txt)

**Comment by Bngo15** [comment] 2021-02-11 18:59
The only difference between the testPayload.txt payload and the api payload is that the api payload isn't surrounded by {testData:[...}

**Comment by jwoo-msft** [comment] 2021-02-11 20:11
@Bngo15,
I tested yours with our main. It works fine.
![image](https://user-images.githubusercontent.com/4112696/107692732-12075f80-6c62-11eb-84cb-f27e0dfee933.png)
It could be this related issue if you're using the botframework. https://github.com/microsoft/AdaptiveCards/issues/5225

**Comment by Bngo15** [comment] 2021-02-11 21:49
It could be. I think it may be related to some form of deserialization of the json when passing the data using GenerateActivityForLocale. If this is resolved in the update, then I understand and can close this issue.

**Comment by jwoo-msft** [comment] 2021-02-11 22:21
@Bngo15,
I will close the issue for now for the tracking purpose. Please do re-activate it if the issue is not resolved after the update.

**Closed by jwoo-msft** 2021-02-11 22:21 UTC
