### ISSUE TITLE
[Designer] Buttons not full width on Teams

### ISSUE THREAD

**Issue by Narizz28** [microsoft/AdaptiveCards#5386] opened 2021-02-11 19:37 UTC
In the designer, it shows the action buttons full card width, but they are not, nor can they set be (that I've figured out how anyway) full width once rendered in a Teams Channel or in Teams Mobile.

**Comment by paulcam206** [comment] 2021-02-25 20:24
@dclaux - do we need to take hostconfig updates from Teams?

**Comment by dclaux** [comment] 2021-02-25 20:25
@paulcam206 Teams should make these changes themselves in the designer.

**Comment by RamaMohanaChary** [comment] 2021-03-02 11:11
Hi @Narizz28,

Currently, there is no way to set width for buttons. They pick up the width based on the length of text.

Could you please try below example, will get more idea,

`{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "width": "stretch",
                    "items": [
                        {
                            "type": "ActionSet",
                            "actions": [
                                {
                                    "type": "Action.Submit",
                                    "title": "Action.Submit"
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "width": "stretch",
                    "items": [
                        {
                            "type": "ActionSet",
                            "actions": [
                                {
                                    "type": "Action.Submit",
                                    "title": "Submit action 2"
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "width": "stretch",
                    "items": [
                        {
                            "type": "ActionSet",
                            "actions": [
                                {
                                    "type": "Action.Submit",
                                    "title": "Submit action3 Submit action3 Submit action3 Submit action3 Submit action3 Submit action3"
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}`

![image](https://user-images.githubusercontent.com/71380905/109639289-00d0b500-7b75-11eb-8211-db818956c704.png)

**Comment by RamaMohanaChary** [comment] 2021-03-10 12:37
Hi @Narizz28,

Could you please let us know the above example and documents helps you.

**Comment by Narizz28** [comment] 2021-03-16 13:10
@RamaMohanaChary It does not. The main issue is WYSIWIG. And the way it's presented in the designer is actually ideal for Teams Mobile, and appreciated in Teams Desktop (stacked full width). Barring the ability to set something like a stretch attribute on the button itself, it would alternatively be nice to at least anchor to parent container width if added to one (versus the action button just hanging out on the card as a free standing element).

**Comment by RamaMohanaChary** [comment] 2021-03-26 07:44
Hi @Narizz28,

Yes, adaptive card has defined width in both designer and Teams Desktop. And also for mobile it has fixed width.
It's by design. 

Could you please raise a [user voice](https://microsoftteams.uservoice.com/forums/555103-public/filters/new) for this

**Comment by jonmill** [comment] 2021-05-13 20:54
Resolving as external as Teams owns this area

**Closed by jonmill** 2021-05-13 20:54 UTC
Labels: Area-Designer, MSTeams-Developer-Support, Resolution-External
