### ISSUE TITLE
[Feature Request] Custom header for Image fetch

### ISSUE THREAD

**Issue by robin-liao** [microsoft/AdaptiveCards#5583] opened 2021-03-25 23:46 UTC
# Platform

What platform is your issue or question related to? (Delete other platforms).
* All platforms

# Author or host
Cards in Microsoft Teams

# Issue
As on behalf of Microsoft Teams, we received customer's ask to request adaptive card support for custom header for "Image". So in SDK it can apply such custom headers when fetch images from the specified URLs.

**Comment by paulcam206** [comment] 2021-03-29 17:55
thanks for the issue @robin-liao! if you haven't already, please feel free to start an email thread/Teams conversation about what exactly you are looking for and what timeline you expect.

**Comment by jonmill** [comment] 2021-04-22 20:53
This is a dupe of #4763

**Closed by jonmill** 2021-04-22 20:53 UTC
Labels: Design Discussion - Needed, Request, Resolution-Duplicate
