### ISSUE TITLE
[iOS] Card selector grows and shrinks as I choose cards

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#3635] opened 2019-11-21 22:03 UTC
# Platform

* iOS (Visualizer app)

# Details

When I pick a card the panel where all the cards in the folder will shrink, if I pick another one, then the panel will grow and so on.

**Comment by nesalang** [comment] 2019-11-22 00:43
@almediana-ms this is the expected behavior. it meant to give space as much as possible for card selection table when choosing card. Once card is chosen, app gives space as much as possible for rendered card.

**Comment by RebeccaAnne** [comment] 2019-11-22 17:21
@almedina-ms Could you get us a screen recording of this behavior?

**Comment by nesalang** [comment] 2019-12-04 22:07
after talking to alberto, i realized that the real issue is that people who haven't used iPhone, the behavior can be confusing. 
It's confusing mainly because when the selection view shrink, it still allows scrolling. The selection view meant to be touched, and expanded. But since it allows scrolling, the above mentioned user group can miss this expansion behavior by touch.

will change app, so that when selection view is shrunken, the scrolling is disabled

**Comment by jwoo-msft** [comment] 2020-10-27 19:17
I'm closing this as this is the user experience with the sample app. I will re-open it if the issue is associated with the accessibility bugs we have.

**Closed by jwoo-msft** 2020-10-27 19:17 UTC
Labels: Bug, BugBash, no-recent-activity
