### ISSUE TITLE
[Slack/Facebook/Emails] Images are rendered as blank

### ISSUE THREAD

**Issue by ejadib** [Microsoft/AdaptiveCards#1019] opened 2017-12-01 14:31 UTC
This was working hours ago, but now cards in Slack/Facebook/Emails are appearing empty, for example:

https://scontent-amt2-1.xx.fbcdn.net/v/t34.0-0/p280x280/24252331_1971244569866818_1392801263_n.png?_nc_ad=z-m&_nc_cid=0&oh=dc69dd00a65fc5283a09053dca52fbd3&oe=5A2474D9

Was there any change? We are using node.js and the 0.6.1 adaptivecards package. also happening with 1.0.0-beta9

**Comment by ejadib** [comment] 2017-12-01 14:58
Seems to be related to https://github.com/Microsoft/AdaptiveCards/issues/985

**Comment by matthidinger** [comment] 2017-12-01 19:25
Duplicate of #985. I'll keep that thread updated with status. Sorry about the troubles folks

**Closed by matthidinger** 2017-12-01 19:25 UTC
