### ISSUE TITLE
[JavaScript]Adaptive card rendering issue in the newest version, when customization is applied.

### ISSUE THREAD

**Issue by Antti-Leskinen** [microsoft/AdaptiveCards#3745] opened 2020-01-27 07:46 UTC
# Platform

What platform is your issue or question related to? (Delete other platforms).
* JavaScript

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards? If host, please specify the corresponding host (app) name.

According to my understanding Host since we are using directline which means we can modify the adaptive cards host file if needed.

If you're an author, who are you sending cards to?

# Version of SDK

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...

Using npm package botframework webchat. The product for the bot is Healthcare Bot. It is a SAAS service. There is a free pricing tier on Azure. The SDK is whatever they are using. I cannot see this information.

# Details

Explain your issue. If you just have a question, please post [on StackOverflow instead](https://stackoverflow.com/questions/tagged/adaptive-cards).

This issue was also filed in botframework webchat github page here: https://github.com/microsoft/BotFramework-WebChat/issues/2834

Succesfully reproduced in the comments: https://github.com/microsoft/BotFramework-WebChat/issues/2834#issuecomment-578610774

Here is the full description from the bot framework webchat issue page:
## Screenshots
Old version:
![image](https://user-images.githubusercontent.com/59018989/72723096-8c150400-3b88-11ea-8ffc-217e7dc6f4a2.png)

New version:
![image](https://user-images.githubusercontent.com/59018989/72723138-a51db500-3b88-11ea-8453-0579c5cb9558.png)

## Version

All the versions are NPM packages. Using React:
Old version:
Botframework-webchat 4.4.2. Where the adaptive cards package is 1.1.3

New version:
Botframework-webchat 4.7.1. Where the adaptive cards package is 1.2.3

## Describe the bug

Using react with create react app and using Javascript to manipulate the DOM  to change the adaptive card behaviour.
The current flow that is working in the old version is:
- the adaptive card button is clicked. The clicked button is disabled and the color is changed to green.
- if there are any other buttons in the adaptive card then disable them and change the color to grey.
- if the current adaptive card contains any radio buttons, checkboxes or any other kind of input elements disable them also.
- This allows the user to see a history of what the user has clicked by showing the clicked buttons as green and everything else as grey. The other benefit is that the buttons can only be clicked once (same applies to other html elements like radiobuttons). The default is that the adaptive card buttons can be clicked multiple times.

How this is achieved:
- For the current button being clicked we check if the "event.target" contains the button class and then the current button is disabled and a css class is added to make the button green.
- Another function checks all the buttons using normal for loop and the button class. The button is disabled and a css class is added to the button to make it grey.
- In order to achieve the above a normal click event listener using javascript is created and a function is applied to it. This function handles the card button click.
- The functions are called inside the store (create a new store like in the minimizablewebchat sample) to make them repeat after every activity.

New version problems:
- In the new version this does not work at all. The buttons keep the original state. Even the radio buttons and other elements are not disabled. 
- During my investigation it seems to sometimes work for less than a second until it reverts to the original state and it does it for all the adaptive cards at the same time while the old version seemed to have only modified the current adaptive card instead of every card. 
- Moreover the actual button in the adaptive card is no longer recognized by “event.target” while every other element is recognized. We need this in order to track the currently selected button. This is probably one of the reason why the custom code does not work anymore. 
- I am not allowed to show actual code.

## Steps to reproduce

0. Creating an adaptive card in the bot. Can you create an adaptive card somehow on your side?
1. Create a react app (for example use the minimzable webchat sample (the old version that is still on the readme.md instead of the new version that is in the code currently but not reflected in the readme file) in webhat directory in here: https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/06.recomposing-ui/a.minimizable-web-chat).
2. create button listener using javascript and apply a custom function to the listener that contains something like "console.log(event.target)". Can also try to disable the target or add a class with a color and see that it is not applied.
3. Notice that in the new version clicking adaptive card button does not show in the browser console but clicking everything else in the chat does show. In the old version the button click showed in the console.
4. This means there is no point doing anything else for the adaptive card since it does not get recognized.
5. You can still try to "document.queryselectorall" to disable the button and if I remember correctly it disables all the buttons and this means the buttons cant be clicked at all.

## Expected behavior

The adaptive card buttons and other html elements like radiobutton should disable when prompted by the DOM. Now it seems to go back to default state for every card after something is changed.

Is there another way to do this other than manipulating the DOM with JavaScript? I have not figured out any other way. Kind of like the "styleset" options to modify the look of the chat to ensure the changes are kept between versions.

## Additional context

- The bug seems to appears when the adaptive cards npm package version changes to 1.2.0 or above.  
- Something seems to have changed in the rendering of the adaptive card in version 1.2.0.
- When the version is 1.1.3 like it is in webchat 4.4.2 it works correctly.
- This happens when the botframework-webchat package is updated from 4.4.2 to any other above version like 4.5.2.
- This is currently a blocker since the bot uses adaptive cards heavily and this problem prevents the updating of the botframework-webchat npm package.
- This bug can be reproduced by the CDN version also using just JavaScript.
- We are using the minimizablewebchat.js sample, but it should not matter in this case since it can be reproduced from CDN version.
- Using Healthcare bot. There is a free pricing tier available on Azure.

**Comment by shalinijoshi19** [comment] 2020-01-28 12:27
Thanks for reporting this @Antti-Leskinen and for the detailed bug report and repro steps. ARe you able to actually share some of the JSON for the card at all to help speed the investigation up? Meanwhile, @dclaux do you have any insights here?

**Comment by Antti-Leskinen** [comment] 2020-01-28 13:13
I can share the adaptive card that is used in the above picture since it happens on any card no matter the content. As long as it includes button or any html element if I remember correctly. I added the file as txt. You need to change it to json.
[adaptive-card-button-error.txt](https://github.com/microsoft/AdaptiveCards/files/4122510/adaptive-card-button-error.txt)

**Comment by shalinijoshi19** [comment] 2020-01-31 12:24
@dclaux, the attached sample json above + using the designer with the onclick event handler added seems to repro the issue for the user here.. For reference please see the comments from the webchat dev ( @stevkan ) [here](https://github.com/microsoft/BotFramework-WebChat/issues/2834#issuecomment-578610774)

**Comment by dclaux** [comment] 2020-01-31 17:50
@Antti-Leskinen I think the problem is probably that your implementation has taken a dependency on the generated DOM, and while that is definitely something you can do, we make no promise to not modify the way the DOM is generated from one version to another. I think the generated DOM has indeed changed between the 1.0 and 1.2 version of the library, and therefore the trick you were previously using doesn't work anymore. If that is indeed what's going on, it is not something we are going to fix; you will have to take steps on your side working around it.

**Comment by Antti-Leskinen** [comment] 2020-02-03 07:20
That is the problem. There is nothing I can do since the adaptive card button click is not getting recognized. As evidenced by the "event.target" not showing anything when clicking the button but it does show the html element when clicking anywhere else Our implementation depends on capturing the adaptive card button click. It was recognized in the old version but not in the new version. On the adaptive card the type is "Action.Submit". Can you find out what has happened between the different versions in terms of the "Action.Submit" rendering? Or can you suggest some other way to get the button click to be recognizable again with the "event.target" parameter? @dclaux

**Comment by dclaux** [comment] 2020-02-03 16:45
@Antti-Leskinen the implementation hasn't changed when it comes to rendering buttons.

The real question is, why are you hooking in to the generated elements in the first place? You should simply implement a handler for the `onExecuteAction` event. If that's not what you're doing, then you should try it; if you're already doing that but still need to hook into the generated buttons' click events, then please explain why. Here is a short code sample that an onExecuteAction handler:

```typescript
// Assuming that card is your AdaptiveCard instance
card.onExecuteAction = (action: Action) => {
    if (action instanceof SubmitAction) {
        // Handle the Action.Submit
    }
}
```

**Comment by Antti-Leskinen** [comment] 2020-02-10 11:40
Sorry, for the long delay. Since I am using React and botframework webchat and according to the API docs in here: https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/API.md 
the activityMiddleware option should be correct, but it only seems to add new DOM elements instead of having a way to modify existing one, It also includes the card property but it seems to be different from the above. 

Maybe the webchat card property does not contain the same things as the instance from adaptive card? Since i added that function card.onExecuteAction and nothing happened. When I console.log the card property the webchat gives I get the card itself correctly. there is a sample in webchat here: https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/05.custom-components/c.user-highlighting

Where it creates a new div with different classnames depending on if the sender is bot or user. I modified this for my own purposes but it seemed to create a completely new div after the button click and no visible changes in the UI. It seems the DOM manipulation is not possible anymore using the html elements since the div seems to applied too high up (the most outermost div) and I mostly need to modify the buttons themselves. Here is the code I tried:
`this.activityMiddleware = () => next => card => {

    console.log(card);

      if (card.activity.channelData !== undefined && card.activity.channelData.postBack === true) {
        // Handle the Action.Submit
        return children => (
          <div
            className={"active"}
          >
            {next(card)(children)}
          </div>
        );
      }
    
      return children => (
      
             next(card)(children)
      
         );

    };`
I tried to do it like this since I did not get the onExecuteAction to work. It said some 'callee error or caller error' in the method in console. Everything was fine in the UI. I am running out of ideas here but thank you for the help anyway!

**Comment by dclaux** [comment] 2020-02-10 17:14
I'm really not sure how to help here. I think the best is to engage with the WebChat folks. @billba is this something you could help with?

**Comment by shalinijoshi19** [comment] 2020-02-11 12:31
@dandriscoll / @ckkashyap thoughts on this one please?

**Comment by billba** [comment] 2020-02-15 18:29
Sorry I haven’t been involved with this project for years.

**Comment by Antti-Leskinen** [comment] 2020-02-21 14:23
Has there been any updates on this?

**Comment by Antti-Leskinen** [comment] 2020-03-20 07:38
Hello, I am still waiting for an update? Any news from this?

**Comment by paulcam206** [comment] 2021-11-29 21:40
Closing as this is a webchat issue, not an Adaptive Cards issue.

**Closed by paulcam206** 2021-11-29 21:40 UTC
Labels: Bug, Partner-MsftBotFramework
