### ISSUE TITLE
Support the ability to run an action as a result of an input's value changing

### ISSUE THREAD

**Issue by dclaux** [microsoft/AdaptiveCards#1731] opened 2018-07-20 01:54 UTC
# Problem
The typical case is the poll scenario. Say a card offers three choices, plus another "other" option, like so:

What do we do for the morale event?
- Whirleyball
- Carting
- Dodgeball
- Other

The idea is that as the "Other" option is selected an extra text input box appears to let the user specify what "other" choice they have in mind.

# Possible solution
Allow an Adaptive action to be associated with an onChange event on any input.

# Who's asking
- Outlook
- Notifications (Feedback Hub)

**Comment by ignacionr** [comment] 2018-07-20 03:02
Can this be restricted to show card actions maybe? Or even better can we list some action types as “implicitly safe” and allow those?

**Comment by andrewleader** [comment] 2018-07-20 04:40
Notifications would find this useful too! When we investigated this in our old XML format, adding a visual state manager seemed like the best option (and then properties on the input values that specify which visual state to go to when selected).

**Comment by andrewleader** [comment] 2019-06-27 23:45
Closing as dupe of #3112 which is tracked through productboard

**Closed by andrewleader** 2019-06-27 23:45 UTC
Labels: Area-Renderers, Area-Schema, Proposal, Proposal-Needed
