### ISSUE TITLE
[Rendering] Adaptive Card doesn't show in iOS mobile if it has an input text field

### ISSUE THREAD

**Issue by fgarciachipi** [microsoft/AdaptiveCards#5878] opened 2021-05-27 00:18 UTC
# Target Platform

Please list the platform(s) that your application is targeting and remove platforms you are not targeting:
- iOS
- Android
- Desktop

# Target Application
MS Teams

# Problem Description

I'm developing an application that uses MS Teams messaging extensions to show an adaptive card with an input field. It was working correctly some days ago in all platforms (iOS, Android, Desktop). However, now is showing a blank page on iOS mobile. I have detected that if I remove the input text field from the adaptive card it renders the others elements in the card. I also did a test with an input number field and it works as expected. 

Current version of the MS Teams iOS mobile is 3.7.0

# Screenshot
![File (1)](https://user-images.githubusercontent.com/8441996/119746456-26a8e580-be56-11eb-989e-095375c3a3f7.jpg)

# Card JSON

``` json
{  
    "type": "AdaptiveCard",  
    "version": "1.2",  
    "body": [    
        {      
            "type": "TextBlock",      
            "text": "Question:",      
            "wrap": true    
        },    
        {      
            "type": "Input.Text",      
            "id": "Question",      
            "value": ""    
        }  
    ],  
    "actions": [    
        {      
            "type": "Action.Submit",      
            "id": "SubmitQ",      
            "data": 
            {        
                "Question": null,        
                "Action": "Start"      
            },      
            "title": "Start"    
        }  
    ]
}
```

# Sample Code

Card creation code:

``` c#
var card = new AdaptiveCard(new AdaptiveSchemaVersion(1, 2));

var message = new AdaptiveTextBlock
{
    Text = $"Question:",
    Wrap = true
};

var question = new AdaptiveTextInput
{
    Id = "Question",
    Value = topic
};

var submit = new AdaptiveSubmitAction
{
    Id = "SubmitQ",
    Title = "Start",
    Data = new CreateData() { Action = "Start" },
};

card.Body.Add(message);
card.Body.Add(question);
card.Actions.Add(submit);

return card;
```

# Version of SDK

AdaptiveCards 2.7.1 (nuget package)

**Comment by jonmill** [comment] 2021-05-27 20:10
@jwoo-msft - can you please take a look and reply back if this is an issue for us or a Teams specific issue? Thanks!

**Comment by jwoo-msft** [comment] 2021-05-27 21:14
@jonmill 
This doesn't repro on the iOS sample app. It's also a dupe of #5870.
<img width="307" alt="Screen Shot 2021-05-27 at 2 11 53 PM" src="https://user-images.githubusercontent.com/4112696/119897582-7f7b8b00-bef5-11eb-8505-03a5f73df5a2.png">

**Comment by jonmill** [comment] 2021-05-27 21:33
Great, thank you!

Closing as dupe of #5870

**Closed by jonmill** 2021-05-27 21:33 UTC
Labels: Area-Renderers, Bug, Platform-iOS, Triage-Investigate
