### ISSUE TITLE
[iOS][Input Evolution] [input validation error messages enabled on the card sent by bot]

### ISSUE THREAD

**Issue by jyoti-ms** [microsoft/AdaptiveCards#4838] opened 2020-09-28 20:48 UTC
# Platform

What platform is your issue or question related to?

* iOS

# Author or host

Host - Teams iOS Client

# Version of SDK

SDK 2.1.0 (Adaptive card v1.3)

# Details

When card is sent by the bot for the first time then error messages are enabled by default and are not visible completely.

Also, an unknown string "Error Massage" is added for inputs even if that is not present in the card JSON. Seems like SDK is picking it up from the inputLabelView.xib and then, adding it to the card view.

PFA screenshots and cardJson for both scenarios mentioned above:
![image](https://user-images.githubusercontent.com/72016168/94480854-83370080-01f4-11eb-9dca-d24e83b6d319.png)
![image](https://user-images.githubusercontent.com/72016168/94483158-19b8f100-01f8-11eb-9363-b746953b36da.png)
[cardJson1.txt](https://github.com/microsoft/AdaptiveCards/files/5294919/cardJson1.txt)
[cardJson2.txt](https://github.com/microsoft/AdaptiveCards/files/5294969/cardJson2.txt)

**Comment by jyoti-ms** [comment] 2020-09-28 21:02
@shalinijoshi19 @dclaux @jwoo-msft  We are facing this issue as we are upgrading to the latest SDK in Teams. Can you please triage and let us know how we can work around this.
FYI: @sowrabh-msft @VikrantSingh01

**Comment by jwoo-msft** [comment] 2020-09-29 21:40
Hi @jyoti-ms,

I tried your payload, and it is not reproducible on the sample app. The logic for the visibility of error message is straightforward. The message is hidden initially,  When send event is triggered, the validation logic happens, then the visibility will get changed if necessary. 

I would suggest to check first that send event of ACRAggregateTarget was not triggered when the card is received. I would also check  `initInputLabelView` of `ACRInputLabelView` to ensure that logic is correctly followed in the custom renderers.

**Comment by jwoo-msft** [comment] 2020-10-06 20:16
@closing, as this is resolved.

**Comment by shalinijoshi19** [comment] 2020-10-07 14:10
@sowrabh-msft / @jyoti-ms could you please take a look at @jwoo-msft 's explanation above, see if it helps ? Thanks

**Comment by jyoti-ms** [comment] 2020-10-07 14:23
@jwoo-msft As we have discussed, you are going to update the "hidden" prop in InputLabelView.xib in this month's release?
The fix that we tried is just a temporary one to unblock ourselves for testing and we are using cocoa pods approach to update the framework so we can't replace binaries (.nib files).

**Comment by sowrabh-msft** [comment] 2020-10-07 14:28
@shalinijoshi19 @jwoo-msft - In addition, in the screenshot below the string "My Error Massage" seems to be coming from the SDK too ( [This file](https://github.com/microsoft/AdaptiveCards/blob/c6cd3586d28d3d9c9456160b90eb8984cec900e2/source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputLabelView.xib#L42) You may want to remove this).

Would this string also come on an inadvertent `send` or `validate` call?

![94483158-19b8f100-01f8-11eb-9363-b746953b36da](https://user-images.githubusercontent.com/58284624/95343810-932aa080-08d6-11eb-9ffa-3e11cc4dc981.png)

**Closed** 2020-10-21 19:03 UTC
Labels: Area-Inconsistency, Bug, Msft-TeamsMobile, MsftTeams-Integration, Platform-iOS, Priority-Now, Triage-Approved for Fix
