### ISSUE TITLE
Selecting properties should not be automatically capitalized (should be “person” and not “Person”)

### ISSUE THREAD

**Issue by KesemZ** [microsoft/AdaptiveCards#7537] opened 2022-06-15 04:57 UTC
Issue with the schema registered with editor control (specified as lowercase, would need regex to be case insensitive), just need to repoint something at an updated schema

**Comment by anna-dingler** [comment] 2024-06-24 17:52
Closing as this is a duplicate of #8591

**Closed by anna-dingler** 2024-06-24 17:52 UTC
Labels: Feature, Area-Designer
