### ISSUE TITLE
[UWP][Memory] [Rendered Cards Leaking Memory]

### ISSUE THREAD

**Issue by andycb** [microsoft/AdaptiveCards#3425] opened 2019-09-06 12:50 UTC
# Platform

* UWP

# Version of SDK

AdaptiveCards.Redering.Uwp  V1.2.2

# Details

When redering an adaptive card, it appears that its memory is not released. The bellow code sample loads an adaptive card, displays it on the UI before removing it and forcing a garbage collection. After 50 itteraltions, an additional 90MB of memory is being used by the test app.

![image](https://user-images.githubusercontent.com/4417762/64429002-f3845880-d0ac-11e9-8ccd-8e768a062e20.png)

```csharp
var renderer = new AdaptiveCardRenderer();
string card = "{   \"$schema\": \"http://adaptivecards.io/schemas/adaptive-card.json\",   \"type\": \"AdaptiveCard\",   \"version\": \"1.0\",   \"body\": [     {       \"type\": \"TextBlock\",       \"text\": \"Publish Adaptive Card schema\",       \"weight\": \"bolder\",       \"size\": \"medium\"     },     {       \"type\": \"ColumnSet\",       \"columns\": [         {           \"type\": \"Column\",           \"width\": \"auto\",           \"items\": [             {               \"type\": \"Image\",               \"url\": \"https://pbs.twimg.com/profile_images/3647943215/d7f12830b3c17a5a9e4afcc370e3a37e_400x400.jpeg\",               \"size\": \"small\",               \"style\": \"person\"             }           ]         },         {           \"type\": \"Column\",           \"width\": \"stretch\",           \"items\": [             {               \"type\": \"TextBlock\",               \"text\": \"Matt Hidinger\",               \"weight\": \"bolder\",               \"wrap\": true             },             {               \"type\": \"TextBlock\",               \"spacing\": \"none\",               \"text\": \"Created {{DATE(2017-02-14T06:08:39Z, SHORT)}}\",               \"isSubtle\": true,               \"wrap\": true             }           ]         }       ]     },     {       \"type\": \"TextBlock\",       \"text\": \"Now that we have defined the main rules and features of the format, we need to produce a schema and publish it to GitHub. The schema will be the starting point of our reference documentation.\",       \"wrap\": true     },     {       \"type\": \"FactSet\",       \"facts\": [         {           \"title\": \"Board:\",           \"value\": \"Adaptive Card\"         },         {           \"title\": \"List:\",           \"value\": \"Backlog\"         },         {           \"title\": \"Assigned to:\",           \"value\": \"Matt Hidinger\"         },         {           \"title\": \"Due date:\",           \"value\": \"Not set\"         }       ]     }   ],   \"actions\": [     {       \"type\": \"Action.ShowCard\",       \"title\": \"Set due date\",       \"card\": {         \"type\": \"AdaptiveCard\",         \"body\": [           {             \"type\": \"Input.Date\",             \"id\": \"dueDate\"           }         ],         \"actions\": [           {             \"type\": \"Action.Submit\",             \"title\": \"OK\"           }         ]       }     },     {       \"type\": \"Action.ShowCard\",       \"title\": \"Comment\",       \"card\": {         \"type\": \"AdaptiveCard\",         \"body\": [           {             \"type\": \"Input.Text\",             \"id\": \"comment\",             \"isMultiline\": true,             \"placeholder\": \"Enter your comment\"           }         ],         \"actions\": [           {             \"type\": \"Action.Submit\",             \"title\": \"OK\"           }         ]       }     }   ] }";

for (var i = 0; i < 50; ++i)
{
    await Task.Delay(1);
    this.ContentControl.Content = null;

    var card = AdaptiveCard.FromJsonString(this.card);

    if (card != null)
    {
        var renderedAdaptiveCard = renderer.RenderAdaptiveCard(card.AdaptiveCard);

        if (renderedAdaptiveCard != null)
        {
            this.ContentControl.Content = renderedAdaptiveCard.FrameworkElement;
        }
    }
    else
    {
        await (new MessageDialog("Card was null", ":(")).ShowAsync();
    }

    await Task.Delay(100);
    GC.Collect(GC.MaxGeneration, GCCollectionMode.Forced);
}
```

**Comment by shalinijoshi19** [comment] 2019-09-06 16:11
@RebeccaAnne, could you take a stab at this see if this is something that @paulcam206 has already addressed or a different one at this point (see offline email thread on this as well) ? Thanks !

**Comment by RebeccaAnne** [comment] 2019-09-13 21:03
Started investigation, found a few things.

1. This is not #3372 recently fixed by @paulcam206. I am able to repro on the latest master which already includes that fix.

2. This does not appear to be a regression of the issue in #2334. Gilles added a test for that case to the test app, which seems to be in order, and is not reporting a recurrence of that leak. Also, that leak repro'd with all cards, whereas this one only repros with some cards. Which brings us to...

2. The below seems to be a min card that repros the leak. Removing the ```"style": "Person"``` property causes the leak not to repro.
```
{
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "Image",
      "style": "Person",
      "url": "https://pbs.twimg.com/profile_images/3647943215/d7f12830b3c17a5a9e4afcc370e3a37e_400x400.jpeg"
    }
  ]
}
```

**Comment by RebeccaAnne** [comment] 2019-09-13 21:40
I am able to repro a leak against the above card in the **1.0.0** nuget package.

**Comment by shalinijoshi19** [comment] 2019-09-16 22:48
Thanks @RebeccaAnne. @andycb it appears that the leak is something that has existed since at least 2017 if not longer. We'll be looking into investigating the cause and mitigating in a subsequent patch _(likely early next month if not sooner) though_ it likely will not make the Sept patch which is supposed to be code complete in the next couple of days. We'll keep you posted. Thanks

**Comment by paulcam206** [comment] 2019-09-19 21:35
Not sure if it's *the* leak, but I'm addressing a couple leaks

https://github.com/microsoft/AdaptiveCards/blob/c9d565500bf43310d5b17cee241bf69794235c78/source/uwp/Renderer/lib/XamlBuilder.cpp#L2432
https://github.com/microsoft/AdaptiveCards/blob/c9d565500bf43310d5b17cee241bf69794235c78/source/uwp/Renderer/lib/XamlBuilder.cpp#L2471

in #3457

**Comment by paulcam206** [comment] 2019-09-19 21:47
and quite a few more `HSTRING` -> `HString`s in 7ce0aff0c4abf5a7a54228aa7223cbd3cf525676

**Comment by barryptak** [comment] 2020-01-09 15:43
Hi. Is there any planned work to look further in to the remaining leaks?
Thanks.

**Comment by chbomtempo** [comment] 2020-01-29 21:28
@barryptak Maybe @shalinijoshi19 have an update on this one...

**Comment by shalinijoshi19** [comment] 2020-04-27 15:20
@paulcam206 could you double check here see if you can still repro it release/1.2 bits (or the latest released).Thanks

**Comment by paulcam206** [comment] 2022-01-27 21:29
Addressing this issue is not currently on our roadmap, so closing. Please feel free to continue the conversation in this issue for future consideration.

**Closed by paulcam206** 2022-01-27 21:29 UTC
Labels: Task, Triage-Approved for Fix

**Comment by barryptak** [comment] 2022-01-28 10:25
Hey, @paulcam206. 
Are you able to be clear on why this P1 bug is this not on the roadmap?
Is it because it's been mitigated significantly and so is not considered a major issue anymore?
Is it because UWP is not being supported going forward?
Is it something else?

Thanks!
