### ISSUE TITLE
Adaptive card schema is missing msteams property

### ISSUE THREAD

**Issue by ebw44** [microsoft/AdaptiveCards#8736] opened 2023-11-06 22:10 UTC
The documentation of Microsoft Teams mentioned the property `msteams` (see [here](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cdesktop%2Cconnector-html#format-cards-with-markdown)). However this property is not part of the json schema of adaptive card. So any card with `msteams` property triggers an error in vscode.
Would it be possible to add this optional property to the schema? 
I hope this is the right place for such request as suggested [here](https://github.com/MicrosoftDocs/msteams-docs/issues/8954#issuecomment-1619969972)

**Comment by anna-dingler** [comment] 2024-06-24 17:24
Closing as this is a duplicate of #8603

**Closed by anna-dingler** 2024-06-24 17:24 UTC
