### ISSUE TITLE
[iOS][Crash] [ADCIOSVisualizer] 

### ISSUE THREAD

**Issue by yanweida99** [microsoft/AdaptiveCards#5209] opened 2020-12-21 08:02 UTC
# Platform

- iOS

# Project

Your demo, ADCIOSVisualizer.

# Version of SDK

2.3.1 from CocoaPods

# Details
run ADCIOSVisualizer, then touch V1.2 -> Scenarios -> FlightDetails.json, it will crash.

2020-12-21 15:52:06.674813+0800 ADCIOSVisualizer[4565:1656621] completed loading elements
2020-12-21 15:52:06.688209+0800 ADCIOSVisualizer[4565:1656621] completed loading elements
2020-12-21 15:52:09.293441+0800 ADCIOSVisualizer[4565:1656621] *** Assertion failure in -[NSLayoutConstraint setPriority:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1556/Foundation/Layout.subproj/NSLayoutConstraint.m:234
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Mutating a priority from required to not on an installed constraint (or vice-versa) is not supported. You passed priority 750 and the existing priority was 1000.'
terminating with uncaught exception of type NSException
2020-12-21 15:52:09.294451+0800 ADCIOSVisualizer[4565:1656621] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Mutating a priority from required to not on an installed constraint (or vice-versa) is not supported. You passed priority 750 and the existing priority was 1000.'
*** First throw call stack:
(0x1ef96bef8 0x1eeb39a40 0x1ef88006c 0x1f036c3e0 0x1f03079bc 0x100be9f20 0x100cbd1b4 0x1f03ddd4c 0x1f03e01e0 0x1f03dfb10 0x1f032ea3c 0x1f03da450 0x10060a668 0x1031e7840 0x1031e8de4 0x1031f6a94 0x1ef8fa1bc 0x1ef8f5084 0x1ef8f45b8 0x1f1b68584 0x21c8b8bc8 0x10062b22c 0x1ef3b4b94)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by jwoo-msft** [comment] 2021-01-06 00:55
@yanweida99,

Thanks for reporting this issue. Can you share the repro steps? I can't repro the issue with our latest.
![IMG_6D7D05D3CD99-1](https://user-images.githubusercontent.com/4112696/103715956-c08af700-4f76-11eb-96cb-76c63faf3190.jpeg)

**Comment by yanweida99** [comment] 2021-01-07 01:27
> @yanweida99,
> 
> Thanks for reporting this issue. Can you share the repro steps? I can't repro the issue with our latest.
> ![IMG_6D7D05D3CD99-1](https://user-images.githubusercontent.com/4112696/103715956-c08af700-4f76-11eb-96cb-76c63faf3190.jpeg)

Steps to reproduce: run ADCIOSVisualizer, then touch V1.2 -> Scenarios -> FlightDetails.json, it will crash immediately.(Reproducibility:Always)
The latest Commit: 794ea64b9a2b4b086bcb1265288aecc8b2f8120b

https://user-images.githubusercontent.com/26455374/103839490-71ee7180-50ca-11eb-8994-f56254e7d4c9.mov

**Comment by jwoo-msft** [comment] 2021-01-08 20:51
Hi @yanweida99,

I'm not sure why you're seeing this issue. I tried the commit hash you provided, and I can't reproduce it. I tried it exactly as you showed me in the video. The error message is saying that a required layout constraint is changed to a value that is something less. But during the image rendering, we don't set a required layout constraint. Have you had any custom code in the sample app? Especially around a resource resolver? Please share your code if you can, I may take a look at it.

Thanks,

**Comment by yanweida99** [comment] 2021-01-12 08:47
> Hi @yanweida99,
> 
> I'm not sure why you're seeing this issue. I tried the commit hash you provided, and I can't reproduce it. I tried it exactly as you showed me in the video. The error message is saying that a required layout constraint is changed to a value that is something less. But during the image rendering, we don't set a required layout constraint. Have you had any custom code in the sample app? Especially around a resource resolver? Please share your code if you can, I may take a look at it.
> 
> Thanks,

Thanks, firstly I didn't have any custom code in the ADCIOSVisualizer. And it still crashed.
But I have some custom code in my demo app, including a resource resolver(SDWebImage). And It works normally after commenting these two lines code.

ACRImageRenderer.mm->configUpdateForUIImageView
//imageHeightConstraint.priority = UILayoutPriorityDefaultHigh;
//imageWidthConstraint.priority = UILayoutPriorityDefaultHigh;

```swift
class AdaptiveCardReslover: NSObject, ACOIResourceResolver {
    func resolveImageViewResource(_ url: URL!) -> UIImageView! {
        let imageView: UIImageView = UIImageView()
        imageView.sd_setImageView(with: url, placeholderImage: nil)
        return imageView
    }

    func resolveBackgroundImageViewResource(_ url: URL!, hasStretch: Bool) -> UIImageView! {
        let imageView: UIImageView = UIImageView()
        imageView.sd_setImageView(with: url, placeholderImage: nil)
        return imageView
    }
}
```

**Comment by jwoo-msft** [comment] 2021-01-13 04:52
@yanweida99,
Thanks for reporting the issue. Setting height and width constraint to Required (1000) are not recommended.  In adaptive card, image's intrinsic content size is rarely get used. It certainly will get scaled. That's why we are setting them to 750 level. 

Is it possible to return a UIImageView, and when image is ready via SDWebImage, assign UIImage in SDWebImage to the UIImageView? I'm assuming the required priority is set by SDWebImage, and trying to find a way to remove or inactivate those constraint with the required priority. 

When you have your image ready, may be in a completion method of SDWebImage, perhaps you can set the SDWebImage's UIImage to the UIImageView that was returned to AdaptiveCard renderer. Of course, I don't know about SDWebImage, but hope it's useful.

**Comment by yanweida99** [comment] 2021-01-20 03:10
> SDWebImage

I reconfirmed that SDWebImage did not set priority, so I am not sure where the problem occurred now. And the first crash occurred when the original ADCIOSVisualizer was running on iPhone7 & iOS 12.0.1.

**Comment by yanweida99** [comment] 2021-01-20 09:03
I run

**Comment by yanweida99** [comment] 2021-01-20 09:38
It seems that this problem can be solved perfectly by adjusting the position of setting priority to the front of setting active.

**Comment by paulcam206** [comment] 2021-02-03 18:58
@jwoo-msft - is this behavior expected, or is there something we need to fix here?

**Comment by jwoo-msft** [comment] 2021-02-08 18:56
@yanweida99 
Hi,

I'm really sorry for the late response. I didn't get the e-mail notification because of my filtering rule. What you have shown me indicates that when the constraint is set to active, it's activated then and gets the default priority of 1000 since the priority was set, and the setting priority at the next line caused the exception. But it also appears that it's a weird timing issue since it doesn't happen with all of the Images with "auto" size. BTW thanks for reporting this weird issue. If you try 2.5.0, this issue should be fixed. I will close this issue, and please feel free to open it again if the new package didn't fix the issue for you. thank you again & am really sorry for the late response.

c.c. @paulcam206

**Closed by jwoo-msft** 2021-02-08 18:56 UTC
Labels: Bug, Needs: Attention :wave:, Resolution-No Repro
