### ISSUE TITLE
[Teams] [Adaptive Card in Microsoft teams getting trimmed]

### ISSUE THREAD

**Issue by HindoliyaYogesh** [microsoft/AdaptiveCards#3388] opened 2019-08-26 10:18 UTC
# Platform

* .NET HTML

# Author or host
Microsoft Teams Client

# Version of SDK
SDK Version : 1.2

# Details
## Version
Bot framework : v3
Adaptive Cards : 1.0

## Describe the bug
We have a customer who needs the user profile cards to be displayed like the attached. At the bottom of the card should be two icons :

- Chat - Should take the user to the teams chat of the user being reported in the user profile card
- Email - Should open default email client with user being reported in the user profile card in To.

Now when I send this card, the two icons have been rendered inside a Column Set which in-turn is placed inside a container. The card when received in web-chat, works fine, but in Teams, the icons are trimmed as shown in the screenshot. I have to scroll up and down a bit, or minimize and restore teams window to get the cards to render in full (without trimming the icons)

## To Reproduce

1. Create a adaptive card
2. Create three containers for body
3. Add something to the first two containers
4. Add a column set to the third container and add three columns
5. Add Images to the first two columns and leave the third empty
6. Send the card to teams client

## Expected behavior
I would expect the card to be shown fully without trimming the bottom.

## Additional Information
I think, because the icons are images fetched from a URL, it takes time for the teams client to load the images, hence the card gets trimmed. This should not happen however, if the images are load async, the card should auto-resize and the user should be able to see the full card with icons. like the following
![card_bug](https://user-images.githubusercontent.com/40543539/63683763-d92ebd00-c818-11e9-98a5-350eaa6953c0.png)
![card_bug_2](https://user-images.githubusercontent.com/40543539/63683764-d92ebd00-c818-11e9-81d1-164ccec55c84.png)

**Comment by HindoliyaYogesh** [comment] 2019-08-26 18:56
Hi @matthidinger  thanks for the quick response. Here is the sanitized version of the Adaptive Card I am sending across to teams client.

{
	"attachments": {
		"contentType": "application/vnd.microsoft.card.adaptive",
		"content": {
			"type": "AdaptiveCard",
			"version": "1.0",
			"height": "auto",
			"body": [{
					"type": "Container",
					"items": [{
						"type": "TextBlock",
						"size": "large",
						"weight": "bolder",
						"color": "accent",
						"text": "User Information",
						"height": "auto"
					}],
					"bleed": true,
					"height": "auto"
				},
				{
					"type": "Container",
					"items": [{
							"type": "ColumnSet",
							"columns": [{
									"type": "Column",
									"width": "80",
									"items": [{
											"type": "TextBlock",
											"size": "large",
											"weight": "bolder",
											"isSubtle": true,
											"text": "Name of user",
											"height": "auto"
										},
										{
											"type": "TextBlock",
											"color": "dark",
											"isSubtle": true,
											"text": "Department",
											"wrap": true,
											"spacing": "none",
											"height": "auto"
										}
									],
									"height": "auto"
								},
								{
									"type": "Column",
									"width": "20",
									"items": [{
										"type": "Image",
										"url": "user profile image url",
										"style": "person",
										"horizontalAlignment": "right",
										"altText": "No photograph",
										"width": "45px",
										"height": "45px"
									}],
									"height": "auto"
								}
							],
							"height": "auto"
						},
						{
							"type": "FactSet",
							"facts": [{
									"title": "Department",
									"value": ""
								},
								{
									"title": "Office",
									"value": ""
								},
								{
									"title": "Phone",
									"value": ""
								},
								{
									"title": "Mail",
									"value": ""
								},
								{
									"title": "Location",
									"value": ""
								}
							],
							"separator": true,
							"height": "auto"
						}
					],
					"separator": true,
					"height": "auto"
				},
				{
					"type": "Container",
					"items": [{
						"type": "ColumnSet",
						"columns": [{
								"type": "Column",
								"width": "10",
								"items": [{
									"type": "Image",
									"url": "icon url",
									"selectAction": {
										"type": "Action.OpenUrl",
										"url": "mailto:",
										"title": "Send email"
									},
									"height": "auto"
								}],
								"height": "auto"
							},
							{
								"type": "Column",
								"width": "10",
								"items": [{
									"type": "Image",
									"url": "icon url",
									"selectAction": {
										"type": "Action.OpenUrl",
										"url": "teams deep link",
										"title": "Chat"
									},
									"height": "auto"
								}],
								"height": "auto"
							},
							{
								"type": "Column",
								"width": "80",
								"items": [],
								"height": "auto"
							}
						],
						"height": "auto"
					}],
					"separator": true,
					"height": "auto"
				}
			],
			"actions": []
		}
	}
}

**Comment by HindoliyaYogesh** [comment] 2019-09-03 08:21
Hi,

Any update on this? In case you need me to look into something from my end, please advise.

Thanks,
Yogesh

**Comment by siduppal** [comment] 2019-09-11 23:51
Support for explicit image sizes was added in Adaptive Cards 1.1 ([ref](https://github.com/Microsoft/AdaptiveCards/issues/536)) which is not supported in Teams yet. We hope to address this issue when we support Adaptive Cards 1.2.

**Comment by shalinijoshi19** [comment] 2019-09-16 22:45
@siduppal FYI a followup question from the customer here. Is the AC trimming in this scenario by design? Is there a work around for them at all while Teams upgrades to 1.2.* ? Is this behavior documented someplace?

**Comment by cconrado** [comment] 2019-09-17 21:29
@siduppal when is teams upgrading to 1.2?

**Comment by matthidinger** [comment] 2019-09-27 17:18
Hi @cconrado, we are actively working with Teams to update, hopefully not much longer. Please subscribe to #3480 which we will close as soon as the roll out is complete

**Comment by cconrado** [comment] 2019-09-27 18:54
@matthidinger lets pray its rdy for Ignite 👍

**Comment by HindoliyaYogesh** [comment] 2019-10-11 19:15
@matthidinger @shalinijoshi19 : If we are tracking the issue under #3480 , do you want to close this one?

**Comment by cconrado** [comment] 2020-01-10 04:46
@matthidinger any update on this? I kno 1.2 is close can we test this on the dev mode of teams?

**Comment by shalinijoshi19** [comment] 2020-01-13 19:49
Closing this as duplicate of #3480 which is tracking teams update to 1.2 (Note: Teams Desktop is already in preview mode using AdaptiveCards 1.2).

**Closed by shalinijoshi19** 2020-01-13 19:49 UTC
Labels: Bug, External, MsftTeams-Integration, Triage-Investigate, no-recent-activity
