### ISSUE TITLE
Adaptive Card mark down parser fails to indent and add bullets to markdown text

### ISSUE THREAD

**Issue by Aditya0603** [microsoft/AdaptiveCards#2666] opened 2019-04-11 12:49 UTC
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android
* iOS

# Author or host
Host

If you're an author, who are you sending cards to?

1.1/1.0.3

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...

# Issue

Adaptive Card mark down parser fails to indent and add bullets to markdown text

{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "Container",
            "items": [
                {
                    "type": "Image",
                    "url": "https://cixdoq.bn.files.1drv.com/y4mswnHfii0b0TH6lDflshlunlPiT0Xu8_Ncrbjr3bSFfCF8gV8IyIDUl8zA8rZWFgryCXQ6gJ-JImjNfLkM8NgQIxqsbeIgI9vwcNRg4GoWSPchAjX9beEYdncTExDslPlkAULCcy67-D7qvAaIGVnY38JoNekYOiKlUqp68gxZ2EINJIu_LN-PdBzPtlkpnGC?width=1373&height=242&cropmode=none"
                },
                {
                    "type": "TextBlock",
                    "weight": "Bolder",
                    "text": "Reach people right where they collaborate. "
                },
                {
                    "type": "TextBlock",
                    "text": "Get the message out to employees using Microsoft Teams. Send announcements to a set of employees, stores, roles or locations in one or more channels or individually.\nUsing this app, you can:",
                    "isSubtle": true,
                    "wrap": true
                },
                {
                    "type": "TextBlock",
                    "size": "Small",
                    "text": "* Collaborate and communicate with large employee groups\n* Target announcements via 1:1 chats for select employees\n* Post in Channels to encourage discussion and feedback\n* Deliver announcements to desktop, web clients or mobile clients of Microsoft Teams  – wherever users are\n* Track and report employee engagement on what you post\n* Track and report employee’s “read receipt” if requested ",
                    "isSubtle": true,
                    "wrap": true
                },
                {
                    "type": "TextBlock",
                    "text": "Take your pick to get started:",
                    "isSubtle": true
                }
            ]
        }
    ],
    "actions": [
        {
            "type": "Action.Submit",
            "id": "createmessage",
            "title": "📢 Create Message"
        },
        {
            "type": "Action.Submit",
            "id": "showscheduled",
            "title": "⏱️ View Scheduled"
        },
        {
            "type": "Action.Submit",
            "id": "viewall",
            "title": "📄 View All"
        },
        {
            "type": "Action.Submit",
            "id": "viewstatistics",
            "title": "👁‍🗨 View Statistics"
        },
        {
            "type": "Action.Submit",
            "id": "adminpanel",
            "title": "⚙️ Admin Panel"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}

**Comment by BalajiR** [comment] 2019-04-11 13:21
You have to use `-` for bullet list instead of `*`
(https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/text-features#markdown)

**Comment by shalinijoshi19** [comment] 2019-04-11 23:47
@BalajiR , aer you saying this is by-design? Also @nesalang can you take a look real quick and see if this is something related to and potentially addressed with changes for https://github.com/Microsoft/AdaptiveCards/issues/2651 at all?

**Comment by nesalang** [comment] 2019-04-17 16:35
@shalinijoshi19 @BalajiR is correct. it's by design.

**Comment by VikrantSingh01** [comment] 2019-11-05 19:23
Need #MsftTeams-Integration label @shalinijoshi19

**Comment by matthidinger** [comment] 2020-06-18 15:27
Hi everyone, this was fixed in #4175 and will be available in the next 1.2.x patch at the end of the month

**Closed by matthidinger** 2020-06-18 15:27 UTC
Labels: no-recent-activity
