### ISSUE TITLE
[NodeJS/All] Add "Link" to ActionStyle and TextColor to Action

### ISSUE THREAD

**Issue by scottlovegrove** [microsoft/AdaptiveCards#5530] opened 2021-03-10 14:50 UTC
**What platform is your feature request related to? (Delete other platforms).**

- [ ] .NET HTML
- [ ] .NET WPF
- [ ] Android
- [ ] iOS
- [ ] JavaScript
- [ ] UWP

**Is your feature request related to a problem? Please describe.**
Basically I want a quick and easy way to create a button that is just text (like a hyperlink).

**Describe the solution you'd like**
I mostly deal with nodejs, but this would likely affect all platforms

What I would like to see is are two relatively small changes to Actions:
- Add a "Link" style to the ActionStyle enum, so this would give "Default", "Positive", "Destructive", and "Link". This would render the Action's title as a text hyperlink, rather than an actual button. (In UWP terms, think HyperlinkButton vs Button).
- Add a `color` field to the Actions which would only be used when the ActionStyle is "link". This would use the existing TextColor enum ("default", "subtle", etc) which would allow that rendered link to appear in the requested color.

With the requested changes, the json for a text-based button would then look like:

``` json
{
    "type": "Action.Submit",
    "title": "link to something",
    "id": "myAction",
    "style": "link",
    "color": "attention"
}
```

**Describe alternatives you've considered**
When I want to create an Action that is just text, I'm having to use the following json:

``` json
{
    "type": "ColumnSet",
    "columns": [
        {
            "type": "Column",
            "width": "stretch",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "Link to something",
                    "wrap": true,
                    "color": "attention"
                }
            ],
            "selectAction": {
                "type": "Action.Submit",
                "id": "myAction"
            }
        }
    ]
}
```

This means when displaying a list of items that may have, say, two of these types of links, the amount of json that is being sent to the host is growing at quite a large rate

I know another workaround that would reduce the json a little more would be to use a RichTextBlock, so the json would be
``` json
"type": "RichTextBlock",
"inlines": [
    {
        "type": "TextRun",
        "text": "New RichTextBlock",
        "selectAction": {
            "type": "Action.Submit",
            "id": "myAction"
        }
    }
]
```

But this still feels like a workaround when just having a link type for action would make much better sense and would be a bit more obvious over how to actually create this type of linked button.

**Additional context**
As an example, in one of the integrations I've written using adaptive cards, having the "Cancel" button as a link rather than a button was a style choice from our designers, but was not something that is simple to do without getting a little creative
![image](https://user-images.githubusercontent.com/25244878/110647565-d81d7080-81af-11eb-8437-2bf0f5d23108.png)

**Comment by paulcam206** [comment] 2021-03-10 16:37
@matthidinger - care to chime in? :)

**Comment by RebeccaAnne** [comment] 2021-03-11 21:26
We will consider this for our upcoming 1.5 release but won't know for sure for a few weeks.

**Comment by matthidinger** [comment] 2021-03-16 18:36
Thanks for filing Scott. Closing this as duplicate of #5548 and tracking there.

**Closed by matthidinger** 2021-03-16 18:36 UTC
Labels: Partner-Doist, Request, Triage-Reviewed-21.03
