### ISSUE TITLE
[MSTeams][Input.Time] Input.Time property is not showing 24 hours time format.

### ISSUE THREAD

**Issue by TejaReddy0226** [microsoft/AdaptiveCards#3882] opened 2020-03-27 10:21 UTC
# Platform

* NET
* Bot Framework V4

# Author or host

* Ms Teams

Hi,

We are using Input.Time property in bot but this property  is not showing 24 hours time format.

Please help with this.

Thanks

![24hoursformat](https://user-images.githubusercontent.com/62458014/77746506-0491b880-7043-11ea-8987-8424c493c242.PNG)

**Comment by shalinijoshi19** [comment] 2020-03-27 16:50
Thanks for reporting @TejaReddy0226.. @dclaux / @susanshen96 / @siduppal I tried the control in adaptivecards.io/designer and noted a 12 hour clock there as well.. Is there a separate configuration on the host that can enable 24 hour format for Input.Time at all or is it something the card author can configure ( I couldn't find anything to help on the schema page here https://adaptivecards.io/explorer/Input.Time.html) .. Thanks!

**Comment by SiarheiKuchukBelitsoft** [comment] 2020-04-13 15:11
Can it be linked with https://bugs.chromium.org/p/chromium/issues/detail?id=1051505 ?

**Comment by berhen** [comment] 2020-09-18 05:15
@shalinijoshi19 Hi, is there any update on this issue?

**Comment by shalinijoshi19** [comment] 2020-09-21 20:01
Interesting - @berhen have you checked out @SiarheiKuchukBelitsoft 's link above? @dclaux thoughts here? Thanks

**Comment by berhen** [comment] 2020-09-22 06:59
@shalinijoshi19 Yes I did. @SiarheiKuchukBelitsoft's leads to a closed bug report for Chromium, that apperently was a duplicate of a bug report that was closed without fix (at least that's how I read that bug report, please correct me if that's wrong). Besides that I could not find any comment from @dclaux here.

We are facing this issue in the Windows 10 Teams client (using a Bot Framework Teams app), not in any browser. Our customers are German, so this is something that's not optimal from a UX perspective.

I would appreciate it If you could clarify how it is planned to deal with this bug and if there are any workarounds we could try out.

**Comment by berhen** [comment] 2021-05-11 10:10
Hi, is there any update on this issue?

**Comment by RebeccaAnne** [comment] 2021-09-09 20:59
This is external to Adaptive Cards and would need to be fixed in Chromium.

**Closed by RebeccaAnne** 2021-09-09 20:59 UTC
Labels: Bug, Area-Inputs
