### ISSUE TITLE
Inline actions

### ISSUE THREAD

**Issue by dclaux** [Microsoft/AdaptiveCards#1730] opened 2018-07-20 01:49 UTC
# Problem
In many cases, a card author might want to make part of a line of text clickable and have it execute a custom action rather than simply follow a link.

# Who's asking
- Outlook

# Proposed design
An "inline" action is one that is represented as a link within a string of text. Inline actions are done via markup and the addition of a "resources" section to a card.

### Example:
```
{
	"type": "AdaptiveCard",
	"body": [
		{
			"type": "TextBlock",
			"text": "If you [click here](action:inlineActionId) something cool will happen."
		}
	],
	"resources": {
		"actions": [
			{
				"type": "Action.Http"
				"id": "inlineActionId",
				"url": "https://…"
			}
		]
	}
}
```

As is illustrated above, the inline action is rendered via a markdown link. The host needs to handle all links before handing them to the system. If a link starts with "action:" then it represents a reference to an Adaptive action declared in the `resources` section of the card. **action:** is followed by the Id of the action in question, in the above example, `inlineActionId`. The referenced action can be any supported Adaptive action. Initially, the "resources" property will only contain an "actions" property, a collection of Action objects.

**Comment by ignacionr** [comment] 2018-07-20 03:07
For what I understand then, actions under “resources” are described but not rendered (so they’re called not through buttons but by some other means).
This is very interesting and would help some specific strategies which now require preprocessing (before rendering).
Please allow actions in resources to be included even if not explicitly tied to a link.

**Comment by andrewleader** [comment] 2018-07-20 04:44
This is a dupe of #865. Closing this new issue as we have several things linking to the old one. Please copy any important details over to the old one! Seems like the old one had just as much (if not more info).

**Closed by andrewleader** 2018-07-20 04:44 UTC
Labels: Area-Renderers, Area-Schema, Status-Ready for Review
