### ISSUE TITLE
[.NET] Low resolution images in an image set don't stretch as they do on other platforms

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#2849] opened 2019-05-03 21:55 UTC
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET WPF

# Issue

The below card renders differently on .NET compared to UWP and Javascript.

Javascript behavior (UWP is similar):
![image](https://user-images.githubusercontent.com/9091833/57167646-57231000-6db3-11e9-8404-7f1473667963.png)

.NET behavior
![image](https://user-images.githubusercontent.com/9091833/57167677-70c45780-6db3-11e9-8322-fd04fa31ae2e.png)

Json:
```
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.2",
  "body": [
    {
      "type": "ImageSet",
      "images": [
        {
          "type": "Image",
          "url": "http://messagecardplayground.azurewebsites.net/assets/person_w1.png"
        },
        {
          "type": "Image",
          "url": "http://messagecardplayground.azurewebsites.net/assets/person_m1.png"
        },
        {
          "type": "Image",
          "url": "http://messagecardplayground.azurewebsites.net/assets/person_w2.png"
        },
        {
          "type": "Image",
          "url": "http://messagecardplayground.azurewebsites.net/assets/person_m2.png"
        }
      ]
    }
  ]
}
```

**Comment by shalinijoshi19** [comment] 2019-05-19 13:26
@andrewleader FYI.

**Comment by andrewleader** [comment] 2019-05-20 17:35
@shalinijoshi19 @RebeccaAnne was this pushed out because we confirmed this was existing behavior in 1.1, and not a regression?

**Comment by shalinijoshi19** [comment] 2019-05-20 17:37
@Andrewleader I pushed this out because it didnt appear to be a ship blocker at this point in time.  Do you guys think we should block 1.2 RTM for this or can this be handled separately as a patch or a 1.3 release?

**Comment by shalinijoshi19** [comment] 2019-05-20 17:38
Also because there was still ambiguity around the spec for it that has not yet been resolved and I didnt see any activity on it since it had been filed.

**Comment by andrewleader** [comment] 2019-05-20 17:42
A patch can be fine, but we should be clear on whether this was a regression or not. If it was a regression, we definitely need to patch it. If .NET always behaved like this, we could wait till 1.3.

JavaScript and UWP behavior is correct, setting the "size" property to one of the sizes (small/medium/large) should force the image to that size, even if it means upscaling the image.

**Comment by shalinijoshi19** [comment] 2019-05-20 17:45
Sounds fair @andrewleader ; Can you help update the spec with the expected behavior and I will take care of assigning this for more investigation next week after we are freed up from 1.2 release formalities.

**Comment by andrewleader** [comment] 2019-05-20 17:46
There is no spec since this was an original 1.0 feature, but sounds good!

**Comment by shalinijoshi19** [comment] 2019-05-20 17:49
@almedina-ms assigning to you for post 1.2 investigation and fixing. We need to figure out if this is a regression or not. If it is, then it makes the case for a post 1.2 patch release else we can include it for 1.3 directly.

**Closed** 2019-07-16 22:32 UTC
Labels: Bug, BugBash, Inconsistency, Platform-.NET, Potential-1.2.1, Potential-1.3, SpecBug, Status-In Code Review, Triage-Approved for Fix
