### ISSUE TITLE
[Javascript][Fallback Requires] Element requires are not respected

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#3419] opened 2019-09-04 20:59 UTC
# Platform

What platform is your issue or question related to? (Delete other platforms).

* JavaScript

# Details

When rendering the [Element.Requires.json](https://github.com/microsoft/AdaptiveCards/blob/master/samples/v1.2/Tests/Element.Requires.json) test file, we get the following result:

![image](https://user-images.githubusercontent.com/9091833/64290913-da986d80-cf1b-11e9-808e-6f2254e2f378.png)

The expected result (from .NET) is:
![image](https://user-images.githubusercontent.com/9091833/64291016-0f0c2980-cf1c-11e9-81fa-da475f518541.png)

It looks like javascript is not performing fallback when requirements are not met.

**Comment by dclaux** [comment] 2019-09-04 21:36
So there are a couple things going on here:
- The designer **in design mode** doesn't fallback. That is by design.
- The designer **in preview mode** does fallback just fine (and the payload mentioned in this issue is handled properly) and therefore the renderer's fallback logic works fine
- There is already an issue opened for proper fallback support in the designer: https://github.com/microsoft/AdaptiveCards/issues/2502
- There is a bug in the designer whereas when you switch from design mode to preview mode and some elements need to fallback they do not. If you switch to preview mode and then paste the payload it works just fine
- The designer should probably issue a warning in design mode that fallback isn't handled

**Comment by matthidinger** [comment] 2019-09-23 18:33
This bug tracks bullets 4 and 5 above, @RebeccaAnne will file a bug to track the last bullet on non-JS renderers.

**Comment by RebeccaAnne** [comment] 2019-09-25 16:40
Logged #3490 to track version handling inconsistency.

**Comment by mokandre** [comment] 2020-06-11 06:13
Does fallback and requires working in the JS platform?

**Comment by jonmill** [comment] 2021-11-11 21:18
Closing due to lack of fallback use

**Closed by jonmill** 2021-11-11 21:18 UTC
Labels: Triage-Approved for Fix
