### ISSUE TITLE
[Samples][Accessibility] Inputs in samples don't use labels

### ISSUE THREAD

**Issue by golddove** [microsoft/AdaptiveCards#4612] opened 2020-08-18 23:35 UTC
# Platform

* All platforms

# Version of SDK

latest main

# Details

Tracking this as a reminder to "activate" the new samples created as part of #4552 to show them on the schema explorer. This is blocked on a critical mass of hosts support schema 1.3.

**Comment by almedina-ms** [comment] 2020-11-05 21:29
assigning to @jwoo-msft

**Comment by RebeccaAnne** [comment] 2021-02-11 22:03
We need to at least get this in PR for 21.03 to be reviewed by the accessibility team.

**Comment by golddove** [comment] 2021-08-19 15:29
@RebeccaAnne @jonmill should probably combine this with #4552 at this point.

**Comment by jonmill** [comment] 2021-08-19 15:41
Dupe of #4552

**Closed by jonmill** 2021-08-19 15:41 UTC
Labels: Bug, Triage-Approved for Fix, Area-Accessibility
