### ISSUE TITLE
[Designer] Toggle Visibility stopped working in show card

### ISSUE THREAD

**Issue by mukuagar** [microsoft/AdaptiveCards#8066] opened 2022-11-20 16:03 UTC
Action.Toggle Visibility stopped working when in a showcard sometime around last Friday(18th Nov 2022).
Here is a sample json to test
```
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.3",
    "actions": [
        {
            "type": "Action.ShowCard",
            "title": "Action.ShowCard",
            "card": {
                "type": "AdaptiveCard",
                "version": "1.3",
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "body": [
                    {
                        "errorMessage": "error message error message error message error message ",
                        "height": "stretch",
                        "id": "11",
                        "isRequired": true,
                        "label": "Hello this is label",
                        "type": "Input.Date",
                        "isVisible": true
                    },
                    {
                        "errorMessage": "error message error message error message error message ",
                        "height": "stretch",
                        "id": "33",
                        "isRequired": true,
                        "label": "This is label",
                        "type": "Input.Time",
                        "isVisible": true
                    },
                    {
                        "actions": [
                            {
                                "targetElements": [
                                    "11",
                                    "33"
                                ],
                                "title": "Action.ToggleVisibility",
                                "type": "Action.ToggleVisibility"
                            }
                        ],
                        "id": "22",
                        "type": "ActionSet"
                    }
                ]
            }
        }
    ]
}
```

**Comment by paulcam206** [comment] 2022-11-29 21:29
Closing as duplicate of #8086

**Closed by paulcam206** 2022-11-29 21:29 UTC
