### ISSUE TITLE
Autocomplete setting for Input.ChoiceSet

### ISSUE THREAD

**Issue by tsuwandy** [microsoft/AdaptiveCards#1068] opened 2018-01-10 21:50 UTC
When Input.ChoiceSet has large number of items, displaying as checkboxes or radio is not very practical and takes too much screen real estate.  Will be great to be able to specify rendering them as auto complete control.

**Comment by dclaux** [comment] 2018-01-10 22:02
You should be able to specify the "style" property of your ChoiceSet and set it to "compact" which should result in it displayed as a ComboBox. I do not believe it does auto-complete though.

"compact" should actually be the default style.

If "style": "compact" does not work for you, there is a problem. Which client is rendering your cards?

**Comment by matthidinger** [comment] 2020-12-08 21:11
This feature is being tracked in another issue.

Duplicate of #3924

**Closed by matthidinger** 2020-12-08 21:11 UTC
Labels: Area-Schema, Request
