### ISSUE TITLE
Any ways to Displays an Authenticated images in AdaptiveCards ?

### ISSUE THREAD

**Issue by rjgmail88** [microsoft/AdaptiveCards#2170] opened 2018-11-14 02:44 UTC
# Platform

What platform is your issue or question related to? (Delete other platforms).

Nodejs

# host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards?

# Version of SDK

Bot builder v3

# Issue
Based on [adaptive cards schema document][2] looks like we should use URL property where value should be direct URL to the image Or Data URIs are already supported by the nodejs Adaptive Card renderer. 

I have BOT web app built using bot builder v3 sdk. I am planning to use adaptive cards to display users profile images which are stored on our secured server (most likely behind the firewall or azure blog storage ) and these are not available anonymously. 

I would like to know if Adaptive Card's renderer will be able to parse/download authenticated images
if they are using same [Bot Framework authentication](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-security?view=azure-bot-service-3.0)

  [2]: https://adaptivecards.io/explorer/Image.html

```
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "Image",
            "style": "Person",
            "url": "",
            "size": "Small"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}
```

**Comment by matthidinger** [comment] 2018-11-14 18:35
Hi @rjgmail88, are you rendering the cards yourself using WebChat, or are these bot messages expected to work inside Teams or other clients?

If you're rendering the cards yourself using WebChat, you should be able to use our existing APIs to custom render Image elements and append authorization headers or inject custom logic along the way. 

If your cards are expected to work in Teams, I'm not sure this is a supported feature right now. I see you have another issue on Data URIs, is this related, or would that feature work for both your issues?

**Comment by rjgmail88** [comment] 2018-11-14 21:03
Hey @matthidinger , 
Sorry I forgot to mention about the channels. We are using MS teams , Cortana for azure bot service. However, the plan is to go towards WebChat channel as well so we can drop this bot on our WebApps. 

Can you point me to document or sample for **existing APIs to custom render Image elements and append authorization headers**

For MS teams bot we are using this [Ms Graph AI](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/profilephoto_get) to pull  users profile image.  But this API gives us raw bytes & I am not able to get it working with URI format & base64 conversation seems to be incorrect. 

Here is the code. 
```
let **dataBuffer** = new Buffer(body); --- body = binary data of an image. 
let **dataBase64** =  new Buffer(**dataBuffer**).toString('base64'); 
const imagData = 'data:image/png;base64,' +**dataBase64**;
```

Few questions we would like to know:

1. In case of images , is Adaptive cards render resolving/downloading bobs & sending back to Ms teams , cortana to just render HTML or it's up to clients ( ms teams ) to handle it ? 
2. If bot builder nodejs sdk is responsible to do this rendering then is there a way to use custom bot authentication to pull such images on the fly ?

**Comment by vman** [comment] 2019-10-02 16:12
@matthidinger Is there a solution for this yet? We are storing images in SharePoint and want to show them on Adaptive Cards in Teams. It works fine if the user is logged in to SharePoint but the images don't load if the user is not signed in. Any way to handle this scenario?

**Comment by dclaux** [comment] 2019-10-02 16:56
@billbliss this would be a question for you.

**Comment by VMey** [comment] 2020-11-14 00:01
Have any more details on this been worked out?  I'm having a similar issue trying to use the adaptive cards designer and render an image from MS Graph API

**Comment by matthidinger** [comment] 2020-11-24 17:09
Hi folks, I'm going to close this as a duplicate of #4763 - but we don't have a plan to solve it just yet. It is higher up on the priority stack though, so hopefully we can make some traction on it in 2021.

**Comment by matthidinger** [comment] 2020-11-24 17:09
Dupe of #4763

**Closed by matthidinger** 2020-11-24 17:09 UTC
Labels: Request
