### ISSUE TITLE
[UWP] Choice set placeholder text is not shown

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#2938] opened 2019-05-17 20:48 UTC
# Platform

What platform is your issue or question related to? (Delete other platforms).

* UWP

# Issue

Compact choice sets are not displaying the placeholder text on UWP.

Json:
```
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "Input.ChoiceSet",
            "id": "ChoiceSet",
            "placeholder": "Placeholder text",
            "choices": [
                {
                    "title": "Choice 1",
                    "value": "Choice 1"
                },
                {
                    "title": "Choice 2",
                    "value": "Choice 2"
                }
            ]
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}
```

Result (UWP):
![image](https://user-images.githubusercontent.com/9091833/57955266-42ae3f80-78aa-11e9-9ef6-596973b1bcbb.png)

Expected result (Javascript):
![image](https://user-images.githubusercontent.com/9091833/57955292-55287900-78aa-11e9-82d0-67785d97c580.png)

**Comment by shalinijoshi19** [comment] 2019-05-19 13:51
@RebeccaAnne / @nesalang FYI moved this out 1.2 at this point but approving this for fix for post 1.2 tackling

**Comment by nesalang** [comment] 2019-07-03 00:01
@shalinijoshi19 & @RebeccaAnne 
According to schema, ChoiceSet.Input doesn't have place holder text.
So UWP is handling things correctly.
FYI, Text/Number/Date.Input have place holder texts.

**Comment by RebeccaAnne** [comment] 2019-07-03 16:41
I think a placeholder text could be useful on a compact choice set. @andrewleader @matthidinger any thoughts on adding this? (right now it works in javascript but not other platforms and is not in the schema)

**Comment by andrewleader** [comment] 2019-07-03 17:14
placeholder text on compact ChoiceSet seems like a useful addition, I think that'd be a great 1.3 feature. @matthidinger @dclaux thoughts?

This does mean yet another meaningless property when it's in expanded or multi-select mode though. But I don't see any better option, so I'm in favor of adding placeholder text.

**Comment by matthidinger** [comment] 2019-07-09 17:12
I'm cool with adding `placeholderText` to Input.ChoiceSet

**Comment by andrewleader** [comment] 2019-07-12 17:36
Closing as dupe of #3198 (unfortunately right now for features to be tracked through productboard, they have to originate from productboard first... they're working on adding support for importing existing issues from GitHub but it's not there yet)

**Closed by andrewleader** 2019-07-12 17:36 UTC
Labels: BugBash, Feature, Inconsistency, Platform-UWP, Triage-Approved for Fix
