### ISSUE TITLE
Greater symbol (">") in a textblock doesn't render in the web designer.

### ISSUE THREAD

**Issue by ldounis** [Microsoft/AdaptiveCards#2695] opened 2019-04-16 07:06 UTC
# Platform

What platform is your issue or question related to? (Delete other platforms).

* JavaScript

# Author or host

Both

If you're an author, who are you sending cards to?

Teams

# Version of SDK

1.1

# Issue

The greater symbol (">") in a textblock doesn't render in the web designer.
Load the below to the designer, the 3rd column doesn't render when the text block has only the ">" as text.

{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
		{
			"type": "Container",
			"items": [
				{
					"type": "ColumnSet",
					"columns": [
                        {
                            "type": "Column",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "size": "Small",
                                    "color": "Accent",
                                    "text": "<"
                                }
                            ]
                        },
                        {
                            "type": "Column",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "size": "Small",
                                    "text": "1 of 2"
                                }
                            ]
                        },
                        {
                            "type": "Column",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "size": "Small",
                                    "color": "Accent",
                                    "text": ">"
                                }
                            ]
                        }
					]
				}
			]
		}
	]
}

**Comment by dclaux** [comment] 2019-04-19 17:29
This is an artifact of the Typescript renderer being too permissive when it comes to Markdown. The ">" character denotes the start of a "block quote" in Markdown.

Closing as it is basically a duplicate of https://github.com/Microsoft/AdaptiveCards/issues/910

**Closed by dclaux** 2019-04-19 17:29 UTC
Labels: Area-Tooling
