### ISSUE TITLE
[JS and C#][Templating Functionatity] [IsMatch AEL is not parsing RegEx properly]

### ISSUE THREAD

**Issue by niravk-microsoft** [microsoft/AdaptiveCards#5032] opened 2020-11-04 09:55 UTC
# Platform

- [ ] JavaScript
- [ ] .Net

# Author or host

We are using JS Renderer to render adaptive cards into Web application as well as we are sending Adaptive Cards to Outlook as well.

# Version of SDK

Adaptive Cards Templating Version 1.1.0

# Details

We are using isMatch AEL function. We tried to provide below regex to that and realize that we are not reaching to expected results.
E.g.
1. [0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])
2. [0-9]{2}[-|\/]{1}[0-9]{2}[-|\/]{1}[0-9]{4}
3. /\\d{4}-\\d{2}-\\d{2}/
4. ^(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])-[0-9]{4}$

Also we have observed that isMatch is working if we utilize with $When condition however same is not working when we embed inside If Condition

E.g. : 
1. ${if(isMatch(propertyValue, '[-+]?[0-9]*\\.?[0-9]+'), formatNumber(float(propertyValue), 2), propertyValue)}

**Comment by shalinijoshi19** [comment] 2020-11-13 16:23
@dclaux is this on your radar for 20.11 for JS? @RebeccaAnne I may need you to pitch in to help fix this for .NET in AEL

**Comment by dclaux** [comment] 2020-11-13 16:56
This looks like a dupe of this: https://github.com/microsoft/AdaptiveCards/issues/5033

Can we close this? I added comments to the other issue. I am not able to repro in JS (haven't tested .NET templating/AEL though).

**Comment by niravk-microsoft** [comment] 2020-11-17 21:09
Closing this as it is duplicate of #5033

**Closed** 2020-11-17 21:08 UTC
Labels: AdaptiveCards v20.11, Area-Inconsistency, Bug, Priority-Now, Triage-Investigate
