### ISSUE TITLE
[Android][Column/ColumnSet rendering] [The height and width allocation in columns has been changed]

### ISSUE THREAD

**Issue by dipja** [microsoft/AdaptiveCards#5061] opened 2020-11-09 14:09 UTC
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] Android

# Author or host

Microsoft Teams

# Version of SDK

2.3.0/2.3.1

# Details

The column width has been affected due to the latest implementation of columns inside FlexBoxLayout. If column width specified in the adaptive card json, it is not allocated the same in the UI. Hence, the elements inside the column overflow the column.
Screenshots of various such cards can be found in this [document](https://microsoft-my.sharepoint.com/:w:/p/dipja/EbsnNdGwVexFo79NFSNwGpYBM4dX5M-bpQEnZttIsvHW_Q?e=tReWtv).

[Bleed.json](https://microsoft-my.sharepoint.com/:t:/p/dipja/ERSxr4PHgktGkNiiWVrX2SYBddTrjuybr1TxTAN4lmb1BQ
)
[TwoColumns.json](https://microsoft-my.sharepoint.com/:t:/p/dipja/ET519T4oQWJKunkUeLOvcgEBjjGLhWL61GqSO4DK8XaGSw)
[ThreeColumns.json](https://microsoft-my.sharepoint.com/:t:/p/dipja/EVSni-ZZTulNkZPf333cuK8BiCrhbbIMW6qkQQ1TknFM-w)
[ImageOverlap.json](https://microsoft-my.sharepoint.com/:t:/p/dipja/EdWrxdVpZTtKmA9YiHWPZuABopSb09Lf5XH_3PZ91YHw2w)
The image in left column is overlapped with the right column with TextBlocks. Even if the image renderer handles that the image should not overflow the outer container (in this case column), the image width becomes squeezed and height remains the same. The bug here is due to the column width is not allocated as it should be according to the value provided in the adaptive card json which is leading to image overflow.

**Note:** 
Even if the host tries to override the column and columnSet renderers to use LinearLayout instead of the FlexBoxLayout, it does not work. This is because the parent container for columns is hardcoded to be FlexBoxLayout (LinearLayout for all other elements) inside the SDK code. It would be great if this control should be provided to the host.

**Comment by shalinijoshi19** [comment] 2020-11-13 15:58
@golddove moving ths back into 12.11 since this is one of the Teams 1.3 upgrade blockers. @dipja pls confirm. Thanks!

**Comment by golddove** [comment] 2020-11-13 22:03
`bleed.json` duplicate of #5050
Second card in docx is dup of #5056
All others seem to be duplicate of #4988

**Comment by shalinijoshi19** [comment] 2020-11-16 20:19
@dipja closing this one out since we have the ones above tracking the issues raised in this combined bug. 
#duplicate #5050, #5052, #4988

**Closed by shalinijoshi19** 2020-11-16 20:19 UTC
Labels: AdaptiveCards v20.11, Area-Inconsistency, Bug, Msft-TeamsMobile, MsftTeams-Integration, Priority-Now, Teams 1.3 Upgrade Blocker, Triage-Investigate
