### ISSUE TITLE
Adaptive Toggle input not showing correctly in teams dark mode Android

### ISSUE THREAD

**Issue by sudoaccessdenied** [microsoft/AdaptiveCards#5402] opened 2021-02-18 20:06 UTC
### I have used  a simple toggle input but it is not showing correctly in Microsoft teams  dark mode )while opening in task module from compose box.
![WhatsApp Image 2021-02-19 at 1 25 48 AM](https://user-images.githubusercontent.com/30634773/108413802-75d8ec00-7251-11eb-9918-152ad0cf90a6.jpeg)

I have used the following code to create adaptive card.
![image](https://user-images.githubusercontent.com/30634773/108414840-bab15280-7252-11eb-8c0e-9be8472160a0.png)

**Comment by paulcam206** [comment] 2021-02-25 20:16
@sudoaccessdenied - what host application are you using here?

**Comment by sudoaccessdenied** [comment] 2021-02-27 08:41
@paulcam206  Microsoft teams in dark mode.

**Comment by paulcam206** [comment] 2021-03-01 03:21
sorry -- I totally missed that in your description (I blame lack of coffee) :)

@golddove - can you repro this in the Android visualizer?

also adding Teams folks in case this is a known issue on their side...

**Comment by RamaMohanaChary** [comment] 2021-03-08 13:49
Hi @sudoaccessdenied ,

We are unable to reproduce the issue. Could you please have a look on below image and code snippet.
![image](https://user-images.githubusercontent.com/71380905/110329557-c5d1f400-8042-11eb-9c7a-5e588fd56c1f.png)
![image](https://user-images.githubusercontent.com/71380905/110329702-f74abf80-8042-11eb-891a-01ec0cd07f3a.png)

Seems your issue is related to css, could you please check from your end.

**Comment by sudoaccessdenied** [comment] 2021-03-08 15:01
@

> Hi @sudoaccessdenied ,
> 
> We are unable to reproduce the issue. Could you please have a look on below image and code snippet.
> ![image](https://user-images.githubusercontent.com/71380905/110329557-c5d1f400-8042-11eb-9c7a-5e588fd56c1f.png)
> ![image](https://user-images.githubusercontent.com/71380905/110329702-f74abf80-8042-11eb-891a-01ec0cd07f3a.png)
> 
> Seems your issue is related to css, could you please check from your end.

@RamaMohanaChary I am not using any html/css page .I am using Adaptive card in task module and it is unrelated to css . Also this  issue occurs in task module not in the chat.  As you can see I have attached the screenshot of task module above not the chat. Since you are using teams task module sample to repro this so you are very close to repro this issue. Use the following Repro steps ;-

1. Clone this repo : [teams task module](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/54.teams-task-module) 

2. Add the toggle Input in `/Resources/adaptiveCard.json`  json file.

3. Run the bot.

4. Send `hi` to the bot it will send two cards.

5. Click on `Adaptive Card` button of hero or adaptive card in mobile  with dark mode theme it will trigger task module.

6. You will see the issue that title of task module is in black color which should be white and label of the toggle input is hidden.

**Comment by RamaMohanaChary** [comment] 2021-03-16 12:06
Hi @sudoaccessdenied,

Thank you for sharing proper repro steps!
It helps us a lot to repro the issue, we are able to repro the issue in Android mobile.

![image](https://user-images.githubusercontent.com/71380905/111306213-f1c22a80-867d-11eb-9605-6c978d9c7115.png)
![image](https://user-images.githubusercontent.com/71380905/111306240-fbe42900-867d-11eb-980d-ffeb52be25c0.png)

So, we took this high priority and raised a bug for this, concerned team will work on this.
At present we don't have any ETA to share with you.

**Comment by sudoaccessdenied** [comment] 2021-05-10 18:57
@RebeccaAnne  when it will be resolved. I have waited for more than two months still did not get any ETA.

**Comment by Jagadeesh-MSFT** [comment] 2021-05-12 07:39
Hi @sudoaccessdenied, you clarify whether using the issue also repros in iOS dark mode or desktop dark mode, to help us isolate the issue.

**Comment by sudoaccessdenied** [comment] 2021-05-13 12:53
@Jagadeesh-MSFT, It's working fine in desktop dark mode.  I don't have an ios device so you can test the same on your side.

**Comment by jonmill** [comment] 2021-05-13 20:45
@Jagadeesh-MSFT, @sudoaccessdenied - this is a Teams bug and is being tracked internally by them. Closing the issue but please feel free to continue communication here while the bug is being resolved by Teams. Thanks!

**Closed by jonmill** 2021-05-13 20:45 UTC
Labels: MSTeams-Developer-Support, Resolution-External
