### ISSUE TITLE
[.NET] AdaptiveCards nuget not support Newtonsoft.Json 13.0.1

### ISSUE THREAD

**Issue by vmadurga** [microsoft/AdaptiveCards#5671] opened 2021-04-15 07:43 UTC
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] .NET

# Author or host

Developer

# Version of SDK

What version are you using? AdaptiveCards v2.7.1

# Details

Latest nuget doesn't support Newtonsoft.Json 13.0.1 version
![imagen](https://user-images.githubusercontent.com/25466105/114832386-b75bc280-9dce-11eb-9ad7-ae7e42bc5d42.png)

**Comment by jonmill** [comment] 2021-05-06 20:09
Dupe of #5575

**Closed by jonmill** 2021-05-06 20:09 UTC
Labels: Bug, Triage-Investigate
