### ISSUE TITLE
[JS][bug] [video player button takes three clicks to work on iOS Safari]

### ISSUE THREAD

**Issue by mindmodel** [microsoft/AdaptiveCards#4032] opened 2020-05-19 13:13 UTC
# Platform
Back end: C#, .Net Core 2.1. Microsoft Bot Framework 4.9.1 (NuGet packages).
Microsoft travel bot sample (back end). Microsoft web chat client sample (front end).

# Author or host
Sending adaptive cards to web host.
Bot code is Microsoft travel bot sample.
Card markup is product details sample from adaptive card designer.
Demo page is here:
https://dnctestbot.z13.web.core.windows.net

Type any message (eg hi) to wake up the bot.
On iOS (iPhone 6, iPhone 7+), the first time the user clicks the video play button nothing happens.  The video is not loading.  It doesn't matter how long you wait.
Then click the button again to pause.  Then click the button again to play.  The video starts playing immediately.

This happens on iOS in Safari, not on Windows in any web browser.

# Version of SDK
Microsoft Bot Framework 4.9.1

**Comment by mindmodel** [comment] 2020-05-19 17:42
Here's a link to the question I posted on StackOverflow for this issue and one other.

https://stackoverflow.com/questions/61829070/microsoft-bot-framework-adaptive-card-1-1-media-play-button-doesnt-display-co/61878406

**Comment by shalinijoshi19** [comment] 2020-06-03 16:11
@ckkashyap what does the webchat rendering flow look like here esp on mobile platforms? Is the AdaptiveCards' iOS renderer kicking in here at all or is it all still web and an apparent Safari quirk that Adam's running into ? 
@jwoo-msft are you able to try looking at this repro page (https://dnctestbot.z13.web.core.windows.net/) on iOS to offer some insights too? Repro steps and bot trigger instructions also included above in their issue description.. 
Thanks

**Comment by jwoo-msft** [comment] 2020-06-19 00:01
@matthidinger Do you know which SDK "Microsoft web chat client sample" uses?
It sounds like SDK being used could be JS renderer. Can you confirm?
cc @shalinijoshi19

**Comment by mindmodel** [comment] 2020-07-09 14:44
I don't understand how my editing the title of the issue to change the number of clicks unassigns someone.  I don't work for Microsoft.  I'm not a contributor to the code of this project.  Just reporting the issue.  Thanks!

**Comment by jwoo-msft** [comment] 2020-07-09 16:31
@shalinijoshi19 @matthidinger  Although until we know what SDK MS webchat client sample uses, we won't know it for sure, this sounds like .NET HTML issue since we had a similar issue in JS renderer, and got fixed. .NET HTML probably has to do similar changes. #3723. cc @dclaux

**Comment by mindmodel** [comment] 2020-08-05 10:40
Has there been any progress on fixing this bug?  I just checked and the demo bot showing the problem is still functioning and still shows the problem.

**Comment by mindmodel** [comment] 2020-10-11 12:06
Another 9 weeks.  No reported progress on fixing this bug.

**Comment by dclaux** [comment] 2020-10-12 04:58
@jwoo-msft this is WebChat, so it is the JS SDK.

@mindmodel sorry this was left unanswered for so long. I fixed a similar issue (the same issue?) a while ago (before Covid); there must be something I missed.

@jwoo-msft it is hard for me to work on this as I do not have any iOS device. This problem is very specific to Safari on iOS as Apple imposes a specific behavior to the `<media>` HTML5 element. I am not even sure there is a solution to this problem. Could you please take a look? I am happy to assist as necessary.

**Comment by dclaux** [comment] 2020-10-12 05:10
More info as I took a look at the fix I wrote before Convid:

The answer listed on StackOverflow is inaccurate. The JS SDK initially renders the "poster" of the media only, with a play button overlayed, not the `<media>` element itself. When the user clicks the play button, the `<media>` element is created and added to the document with its "autoPlay" and "mute" properties set to true.

A while back (I believe it was iOS 4 or something like that) Apple completely disallowed auto-play for the <media> element in Safari on iOS. Later on, they changed their policy so as to allow auto-play _only_ if the audio/video is initially muted, which is what the JS SDK does.

@mindmodel what version of the WebChat control are you using? I can think of two main reasons why you're seeing this issue:
- You're using an older version of WebChat that relies on a version of the AC JS SDK that doesn't include the fix
- Or there are new policies/changes in the way Safari on iOS handles the `<media>` element that we will need to work around

**Comment by mindmodel** [comment] 2020-10-12 11:49
@dclaux Thank you for your reply!

> what version of the WebChat control are you using?

The source of the sample page

https://dnctestbot.z13.web.core.windows.net

is available in View Source.  Not obfuscated.

https://cdn.botframework.com/botframework-webchat/latest/webchat.js

What is the URL and doc page for the version I should be using?

Adam

**Comment by dclaux** [comment] 2020-10-12 15:23
That should be the latest version of WebChat, which I believe uses a version of AC with the fix. So not quite sure what's going on, unless again I've missed something when implementing the fix or Apple has changed things again.

@jwoo-msft would really appreciate help here, again I do not have any iOS device.

**Comment by dclaux** [comment] 2020-10-12 15:26
@mindmodel could you confirm the version of iOS running on your device(s)?

**Comment by mindmodel** [comment] 2020-10-13 20:38
Just cleared Safari cache and verified on iPhone 7+, iOS version 14.0.1.

The bug was also present on whatever the up-to-date iOS versions were when the comments above were posted.

**Comment by jwoo-msft** [comment] 2020-10-14 23:19
> That should be the latest version of WebChat, which I believe uses a version of AC with the fix. So not quite sure what's going on, unless again I've missed something when implementing the fix or Apple has changed things again.
> 
> @jwoo-msft would really appreciate help here, again I do not have any iOS device.

@dclaux, sorry for the late response. I just saw this. Let me know how I can help you with this issue.

**Comment by mindmodel** [comment] 2020-10-15 10:37
.Net Core 2.1
Microsoft.Bot.Builder.Dialogs version 4.9.1
Microsoft.Bot.Builder.Integration.AspNetCore version 4.9.1

**Comment by mindmodel** [comment] 2020-10-15 10:38
Markup for the adaptive card:

{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.1",
  "fallbackText": "This card requires Media to be viewed. Ask your platform to update to Adaptive Cards v1.1 for this and more!",
  "body": [
    {
      "type": "Media",
      "sources": [
        {
          "mimeType": "video/mp4",
          "url": "https://adaptivecardsblob.blob.core.windows.net/assets/AdaptiveCardsOverviewVideo.mp4"
        }
      ]
    }
  ],
  "actions": [
    {
      "type": "Action.OpenUrl",
      "title": "Learn more",
      "url": "https://adaptivecards.io"
    }
  ]
}

**Comment by mindmodel** [comment] 2020-10-15 10:39
Code to send the card:

var welcomeCard = CreateAdaptiveCardAttachment();

var response = MessageFactory.Attachment(welcomeCard);

await turnContext.SendActivityAsync(response, cancellationToken);

**Comment by mindmodel** [comment] 2020-10-15 10:39
private Attachment CreateAdaptiveCardAttachment()
        {
            string cardResourcePath = "TestCoreBot.Cards.testCard.json";

            using (var stream = GetType().Assembly.GetManifestResourceStream(cardResourcePath))
            {
                using (var reader = new StreamReader(stream))
                {
                    var adaptiveCard = reader.ReadToEnd();
                    return new Attachment()
                    {
                        ContentType = "application/vnd.microsoft.card.adaptive",
                        Content = JsonConvert.DeserializeObject(adaptiveCard),
                    };
                }
            }
        }

**Comment by dclaux** [comment] 2020-10-15 15:26
@jwoo-msft it would be great if you could try and identify the actual problem on an iOS device. I do not have one. I am happy to fix once I understand what to do, but feel free to fix yourself if you feel like it.

**Comment by jwoo-msft** [comment] 2020-10-16 00:41
@mindmodel 

Can you give me a repro step for your issue?

I tried https://dnctestbot.z13.web.core.windows.net.

It opens a chat app, but I don't how to make the bot to send a media card.

Thanks

**Comment by jwoo-msft** [comment] 2020-10-16 00:58
@dclaux 

I took a few screen captures in chronological order.

It starts with a poster. When you press the play icon, you get to the next image.
Notice how play button is set to pause. It appears that media should have been playing at this stage.
To get the media to play, you have to touch the pause button to make it a play button. Take a look at the third screenshot.
When the play button is touched, media starts playing.

![IMG_787A4050EED6-1](https://user-images.githubusercontent.com/4112696/96200562-0c497980-0f0f-11eb-807d-55bf650c280d.jpeg)
![IMG_823ADAFBDACB-1](https://user-images.githubusercontent.com/4112696/96200550-06539880-0f0f-11eb-97a8-a9e31d5141bd.jpeg)
![IMG_175A8C9D6BC1-1](https://user-images.githubusercontent.com/4112696/96200545-00f64e00-0f0f-11eb-944d-94e9e843aa2d.jpeg)

**Comment by mindmodel** [comment] 2020-10-16 01:11
Send it any message.

**Comment by jwoo-msft** [comment] 2020-10-16 01:13
>> I tried their while back (I believe it was iOS 4 or something like that) Apple completely disallowed auto-play for the element in Safari on iOS. Later on, they changed their policy so as to allow auto-play only if the audio/video is initially muted, which is what the JS SDK does.

I tried this linkhttps://dnctestbot.z13.web.core.windows.net from Chrome and Safari on Mac. The sound wasn't muted on Chrome. Could It be possible that the unmuted sound is the reason why autoplay is not working on Safari?

**Comment by mindmodel** [comment] 2020-11-01 11:04
Any news?

Adam

**Comment by mindmodel** [comment] 2020-11-11 09:39
?

**Comment by cleemullins** [comment] 2021-05-21 20:48
I've asked @matthidinger to take a look at this and see what next steps may look like.

**Comment by mindmodel** [comment] 2021-06-11 09:40
Any news?

**Comment by jwoo-msft** [comment] 2021-06-30 00:45
@mindmodel,
Hi,
I tried this issue and I couldn't repro it on 6S and 12 pro. It didn't work on 6S before, and it seems to be fixed. Does this issue only reproducible on 6 and 7?
Thanks

**Comment by mindmodel** [comment] 2021-06-30 01:13
@jwoo-msft It's working now on my iPhone 7+, which it hasn't before.

It's also working on my iPhone 6, which it hasn't before.

So unless I find any recent iPhones or other recent mobile devices where it
doesn't work, we should be ok.

Thanks!

Adam



<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jwoo-msft** [comment] 2021-06-30 01:25
awesome, I'm closing this issue then.

**Closed** 2021-06-30 01:28 UTC
Labels: Bug, Platform-iOS, Triage-Approved for Fix
