### ISSUE TITLE
[iOS 13.3][ACRRenderer freezes UI thread]

### ISSUE THREAD

**Issue by emelyanovkirill** [microsoft/AdaptiveCards#3930] opened 2020-04-15 17:57 UTC
# Platform

What platform is your issue or question related to? (Delete other platforms).
* iOS

# Author or host

Microsoft

# Version of SDK

CocoaPods, 1.2.7

# Details

ACRRenderer.render() method cannot be performed in non-UI thread. But when it is performing, my UI thread freezes 0.2-0.5 sec.

**Comment by jwoo-msft** [comment] 2020-04-15 18:22
@emelyanovkirill 
Hi,
Have added resource resolver to your renderer? We use resolvers for image downloading, and etc.
Here is [an example]( https://github.com/microsoft/AdaptiveCards/blob/master/source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m#L120-L124)

**Comment by emelyanovkirill** [comment] 2020-04-15 18:43
I have not classes with ADC prefix. How can I get it?

**Comment by jwoo-msft** [comment] 2020-04-15 18:53
> I have not classes with ADC prefix. How can I get it?

If you mean ADCResolver, you have to implement your resolver. You can use the sample resolver defined in [ADCResolver.m](https://github.com/microsoft/AdaptiveCards/blob/master/source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ADCResolver.m) and [ADCResolver.h](https://github.com/microsoft/AdaptiveCards/blob/master/source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ADCResolver.h)

**Comment by emelyanovkirill** [comment] 2020-04-16 10:18
Started to load faster, but still feel small brakes when scrolling collection view horizontally with reusable cells where the ACRRenderer.render() method is called every time. Сan I fix this somehow?

**Comment by jwoo-msft** [comment] 2020-04-16 18:32
> Started to load faster, but still feel small brakes when scrolling collection view horizontally with reusable cells where the ACRRenderer.render() method is called every time. Сan I fix this somehow?

There are few things you can try.
Try with cards that has only text elements, and see if this help you, this will be your baseline.
Try with cards with images. Take note if there are any differences between the two types of cards. If you notice significant differences between the two, you may consider caching the images.

Try re-use rendered card as much as possible. In your UITableView, render the cards only if you have to. When a cell is needed to be displayed, make sure that the cell's content view really need to render an AdaptiveCards especially during scrolling, and consider caching the rendered cards.

**Comment by emelyanovkirill** [comment] 2020-04-17 09:12
Thanks! 
How can I find out the actual height of ACRView? It always has bounds (0,0, kACRWidth, 0), even after rendering and adding to view hierarchy?

**Comment by jwoo-msft** [comment] 2020-04-20 19:13
> Thanks!
> How can I find out the actual height of ACRView? It always has bounds (0,0, kACRWidth, 0), even after rendering and adding to view hierarchy?
> I want to get a ready rendered view with correct frame size before adding it to the self-sizing cell, because if the ACRView resizes after adding, the cell does not change its height anymore.
> I do not want to use tableView.beginUpdates(), tableView.reloadRows() methods, became it has unwanted UI side effects, for example when user is scrolling in this time.

@emelyanovkirill 
The reason that you're not seeing the height is because at the time you're rendering with AdaptiveCards SDK, update cycle hasn't started. AdaptiveCards uses auto layout, so you wouldn't see the frame dimension until update cycle is finished, so setting appropriate layout constraints is required. If you call intrinsicContentSize, it will return its intrinsic content size.  If you really want to get the frame size and render it then, you can call layoutifneeded on an AdaptiveCards. Can you elaborate more on **the ACRView resizes after adding, the cell does not change its height anymore**? Why does ACRView resizes after adding?

**Comment by emelyanovkirill** [comment] 2020-04-23 11:26
ACRView resizes after adding, because it contains image and title below. When image not downloaded yet, ACR view show title only, and after downloading of image (didLoadElements->cardView.layoutIfNeeded), image appears and title not visible anymore.

**Comment by emelyanovkirill** [comment] 2020-04-23 11:31
Now I add acrView before adding to the cell, but there is a problem. I wait for didLoadElements (), and after that I add acrView to the cell. But if the image is already cached, didLoadElements () is not called. And I don't know if didLoadElements () will be called or not.

**Comment by shalinijoshi19** [comment] 2020-04-24 13:15
@jwoo-msft let's chat about this issue a bit. Thanks for looking into.. @emelyanovkirill thanks for the details here btw! Appreciate it.

**Comment by jwoo-msft** [comment] 2020-10-29 21:21
@emelyanovkirill 
Sorry about the late response. a new fix is added to iOS SDK that may help you. it still needs another piece, but you may be able to implement the piece by yourself. that is you pull image URLs from AdaptiveCards, and asynchronously load them into your app, in that way images are ready before cards are rendered. 

in your resource resolver, you can return the cached image based on the URL of the AdaptiveCards element. With this, returned the AdaptiveCards view will not change its size with images. Previously, using the cached images was not loaded in the same task block, so it could resize the AdaptiveCards view.

I'm closing this issue as I provided a workaround. It would have been a fix if we had provided you with the first part as well. but if you feel that the first part is really needed, the issue is tracked by https://github.com/microsoft/AdaptiveCards/issues/4974, please leave comments in the support of this feature if you like to see get expedited.

**Closed by jwoo-msft** 2020-10-29 21:21 UTC
Labels: Bug
