### ISSUE TITLE
[MS Teams][Extensibility] [AssociatedInputs not supported for custom actions]

### ISSUE THREAD

**Issue by dipja** [microsoft/AdaptiveCards#5233] opened 2021-01-06 07:10 UTC
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] Android
- [ ] iOS

# Author or host

MS Teams

# Version of SDK

2.4.0 (latest)

# Details

Custom action are built extending the baseActionElement in android and iOS. The newly added associated inputs are supported for submit action specifically. The same is not possible with custom actions, hence a card writer cannot mention if the custom action should perform input validation (associatedInputs: auto) or not (associatedInputs: none).

**Comment by shalinijoshi19** [comment] 2021-01-15 02:12
@RebeccaAnne was this an oversight or by design?

**Comment by RebeccaAnne** [comment] 2021-01-19 21:53
Associated Inputs should work on custom actions. Need further investigation to determine whether they actually do on any platform.

**Comment by RebeccaAnne** [comment] 2021-01-21 22:11
Scheduling for 21.02 as this is a P0 Teams bug.

**Comment by RebeccaAnne** [comment] 2021-01-21 22:16
We currently only support associated inputs on Submit Actions, so we did not make it a part of the base action class. One possibility would be to have this property available on all action types (by making it part of the base class) but having it default to "none" for non-submit types. I think long term as we build out associated inputs we will want it on all types (show card or toggle for example may indicate progress through a scenario which may desire validation before proceeding) so this seems like a reasonable approach to me which would allow it to be present on custom action types.

**Comment by RebeccaAnne** [comment] 2021-02-25 18:49
Per discussion, the ask here is in support of Action.Execute rather than something that is currently needed for other custom actions. Team's scenario would be supported by adding Action.Execute with support for associatedInputs to the relevant renderers. We are in theory okay with adding associated inputs to the base class to support it on custom actions generally, but assuming we add the Action.Execute support that work would be lower priority.

**Comment by jwoo-msft** [comment] 2021-04-26 16:59
closing this with Action.Execute changes.

**Closed by jwoo-msft** 2021-04-26 16:59 UTC
Labels: Bug, High Priority, Partner-MsftTeamsMobile, Platform-Android, Platform-iOS, Triage-Investigate
