### ISSUE TITLE
[MS Teams][Adaptive Cards] [TextBlock type doesn't support line breaks \n]

### ISSUE THREAD

**Issue by stroganovmaxv** [microsoft/AdaptiveCards#5538] opened 2021-03-12 00:11 UTC
Source code:
```json
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "Container",
      "items": [
        {
          "type": "TextBlock",
          "text": "one\ntwo\nthree",
          "wrap": true
        }
      ]
    }
  ]
}
```

Expected result:
![07](https://user-images.githubusercontent.com/75748513/110872325-3fcedb00-82d8-11eb-928e-b0703d52630a.jpg)

Actual result:
![06](https://user-images.githubusercontent.com/75748513/110871860-d949bd00-82d7-11eb-9cf8-0a6766a10750.jpg)

**Comment by dclaux** [comment] 2021-03-12 00:42
@stroganovmaxv as explained in https://github.com/microsoft/AdaptiveCards/issues/5086, this is by design. TextBlock is processed with Markdown, and Markdown requires two consecutive \n characters.

```
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "text": "abc\n\ndef\n\nghi",
            "wrap": true
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3"
}
```
![image](https://user-images.githubusercontent.com/1334689/110822702-2e3cf300-8246-11eb-90fb-993a22ebc266.png)

**Comment by dclaux** [comment] 2021-03-12 00:44
I am closing this as "by design". If you would like to make a feature request, please reopen.

**Comment by stroganovmaxv** [comment] 2021-03-12 02:47
> Please verify that the above card with the double \n works as expected in Teams and report your finding here.

double \n works, but in this case we receive the extra empty lines between lines with text and such result doesn't resolve the issue:

{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "Container",
      "items": [
        {
          "type": "TextBlock",
          "text": "one\n\ntwo\n\nthree",
          "wrap": true
        }
      ]
    }
  ]
}

![08](https://user-images.githubusercontent.com/75748513/110884120-3bf98380-82ed-11eb-920a-09ef39ac4dff.jpg)

**Comment by dclaux** [comment] 2021-03-12 08:07
That too is by design. In Markdown, you cannot simply insert a line break, only create new paragraphs.

**Comment by dclaux** [comment] 2021-03-12 17:00
To be accurate, inserting just a new line in Markdown can be done by using `<br>` but it is not officially supported by Adaptive Cards (AC only supports a subset of Markdown).

**Closed** 2021-03-12 17:39 UTC
Labels: Bug, Triage-Needed

**Comment by abrbon** [comment] 2023-08-18 17:39
Hi, 
Found this old issue and having similer issue.

I am using a variable of type string to insert some text in my adaptive card in a TextBlock to post message in MS Teams.
Problem is if i use the '\n\n' to add a linebreak in my variable it is automatically transformed to '\\n\\n' 
so the linebreaks do not work :( 

Example:
`{
                    "type": "TextBlock",
                    "text": "\n\nTEST\n\n@{join(variables('AccountNames_Array'), '\n\n')}\n\nTEST-2\n\n",
                    "wrap": true,
                    "weight": "Default"
 }`

The output looks something like this:

`{
                    "text": "\n\nTEST\n\nJohn.doe@example.com\\n\\nJohn-2.doe@example2.com\\n\\n\n\nTEST-2\n\n",
                    "type": "TextBlock",
                    "weight": "Default",
                    "wrap": true
}`

How can i fix this so it will not change the '\n' in '\\n' ?

I have tried to fix this for the last 1,5 hour and it is driving me crazy!

**Comment by kevinpohlmeier** [comment] 2024-10-08 19:46
I worked around this by adding TextBlock items to the Container with "spacing = none" instead of using a single TextBlock item.

**Comment by ankit-yadav-codes** [comment] 2025-08-01 17:29
I encountered this issue as well and wanted to share my findings and solution.

When using \n\n inside a TextBlock, it results in two line breaks, which introduces an empty line between text segments effectively rendering them as separate paragraphs. This behavior aligns with Markdown parsing, where multiple newlines are treated as paragraph breaks.

However, if your intention is to render a single line break without the extra spacing, using \\\n (i.e., triple backslash followed by n) works as expected in MS Teams. It inserts a line break without introducing an additional empty line.

<img width="1509" height="728" alt="Image" src="https://github.com/user-attachments/assets/d384eeaf-3a95-40ee-a61c-81c67fdf277e" />
