### ISSUE TITLE
IOS- iphone and ipad MS Teams App Adaptive Cards not loading

### ISSUE THREAD

**Issue by RajaniJillaGit** [microsoft/AdaptiveCards#3799] opened 2020-02-23 10:06 UTC
# iOS

Hi Team,

We are using v4 bot framework SDK and rendering adaptive cards on MS teams channel. It is working fine in Desktop and Android but not on IOS. Upgraded to 1.2.3 for the adaptive cards nuget package in the SDK and device details are as below.

1. iphone 6 
version - 12.4.5
ms teams app version - 2.0.2

2. ipad mini
version - 12.4.5
ms teams app version -2.0.2
[CreateCase.txt](https://github.com/microsoft/AdaptiveCards/files/4240803/CreateCase.txt)

Behavior is app is getting crashed when bot is trying to render the card. PFA for reference of the payload. Kindly please check and comment as this is a road block for all the features in the Bot.

**Comment by RajaniJillaGit** [comment] 2020-02-24 22:52
Hi Team,

Could you please help responding to the above ?

**Comment by shalinijoshi19** [comment] 2020-02-25 06:43
Thanks for reporting this @RajaniJillaGit . @VikrantSingh01 what version of AC is being used here in the repro would you know (they are using msteams version 2.0.2) ? Meanwhile, @almedina-ms are you able to help test the attached payload out on the latest nightly release of our Visualizer test app please to see if the crash that is being reported here repro's for just the raw AC renderer stack? thanks. @nesalang  FYI.

**Comment by nesalang** [comment] 2020-02-25 17:00
@shalinijoshi19 ,
Crash happened with the payload because of '*'.
This was fixed by [#3779](https://github.com/microsoft/AdaptiveCards/pull/3779), confirmed it worked on 1.2.7 branch (jwoo/rel/1.2).

**Comment by RajaniJillaGit** [comment] 2020-02-26 18:15
Hi Team,

Do we need to upgrade the nuget package ? Please confirm necessary steps to be taken.

**Comment by shalinijoshi19** [comment] 2020-02-27 13:32
Hi @RajaniJillaGit our fix would be absorbed by the Teams iOS app and once that's done your scenario should just work once you get the fixed version id the Teams ios app. We're slated to publish our iOS updates eow this week, and Teams will follow suit later in the next few weeks.. @VikrantSingh01 for fyi/ comment as well. Please stay tuned and thanks for your patience!

**Comment by shalinijoshi19** [comment] 2020-03-04 22:11
@nesalang did this ship with AdaptiveCards v1.2.7 last week? I dont see this tagged right if it did? @VikrantSingh01 on the timeline for absorbing 1.2.7 on the Teams app side at their end..

**Comment by nesalang** [comment] 2020-03-04 22:43
> @nesalang did this ship with AdaptiveCards v1.2.7 last week? I dont see this tagged right if it did? @VikrantSingh01 on the timeline for absorbing 1.2.7 on the Teams app side at their end..

@shalinijoshi19 Yes, this is shipped. This issue was dupe of #3776, and the fix for #3776 was shipped as part of 1.2.7

**Comment by shalinijoshi19** [comment] 2020-03-05 02:45
Ok so this should have been resolved as such. @RajaniJillaGit FYI that this issue is a #duplicate of #3766 shipped as part of [AC 1.2.7](https://github.com/microsoft/AdaptiveCards/issues/3776#issuecomment-592806257), currently in testing by the Teams iOS team. There should be no nuget package update needed at your end for this issue specifically since it's the Teams host app that will need to consume the latest AC cocoapod framework package. @VikrantSingh01 what is the recommended update channel here that we can point folks to for Teams updates esp wrt AdaptiveCards intake?

**Closed by shalinijoshi19** 2020-03-05 02:45 UTC
Labels: Bug, Msft-TeamsMobile, MsftTeams-Integration, Platform-iOS

**Comment by RajaniJillaGit** [comment] 2020-03-06 04:40
@shalinijoshi19 Kindly please suggest the version to upgrade the teams app ?

**Comment by shalinijoshi19** [comment] 2020-03-06 16:45
@RajaniJillaGit a representative from Microsoft will be reaching out to you with workaround details here while Teams works on upgrading to 1.2.7 in the next month. (it's not ready or released for you to be picked up); Meanwhile also attaching the proposed workaround from @nesalang here: 
<snip>
Instead of using the plain wildcard character (*) in your inline textrun's for the RichTextBlock, can you try using ***** (escaped markdown sequence for bold? ) or italics instead? 
</snip>

**Comment by Sujit-Gaikwad** [comment] 2020-04-29 10:12
@shalinijoshi19 is the update (1.2.7) given for MsTeams ?

**Comment by BrunoFerreiraBastos** [comment] 2020-05-06 17:56
Hi, 

I'm using version 2.0.9, and it's still not working on IOS.

Tks.

**Comment by Sujit-Gaikwad** [comment] 2020-05-08 07:13
@Subhasish-msft/@shalinijoshi19 , with V2.0.9 teams update this is working for iPhone 10 but with same update it is not working for iPhone 6

can you tell me for which all iPhone version it will support???
