### ISSUE TITLE
[UWP JS] Spacing at the begining of a value in a factSet

### ISSUE THREAD

**Issue by utsavlathia** [microsoft/AdaptiveCards#3010] opened 2019-05-31 22:17 UTC
# Platform

What platform is your issue or question related to? (Delete other platforms).

* JavaScript
* UWP

# Issue

```
A factSet with spaces before the value doesn't show the spaces on JavaScript (Using the visualizer to verify). On UWP the spaces are shown.  
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
		{
			"speak": "<s>Tom's Pie is a     Pizza restaurant which is rated 9.3 by customers.</s>",
			"type": "ColumnSet",
			"columns": [
				{
					"type": "Column",
					"width": 2,
					"items": [
						
{
                    "type": "FactSet",
                    "facts": [
                        {
                            "title": "Fa 1",
                            "value": "  Value ow that we have defined the main rules and features of the format, we need to produce a        "
                        }
                    ]
                }
					]
				}
				
			]
		}
	]

}

```

On UWP
![Spaces_UWP](https://user-images.githubusercontent.com/43022566/58737704-6c418d80-83b7-11e9-90a2-cb31183ecad3.PNG)

On JavaScript

![Spaces_JavaScript](https://user-images.githubusercontent.com/43022566/58737514-c1c96a80-83b6-11e9-9914-93ddfd60839f.PNG)

#Result 
There is an inconsistency between platforms.

**Comment by dclaux** [comment] 2019-05-31 22:20
In JS at least, that is because Markdown is enabled for FactSet values. Markdown collapses spaces, that's by design.

**Comment by shalinijoshi19** [comment] 2019-07-05 23:20
@RebeccaAnne / @nesalang / @almedina-ms what's the behavior in this scenario on other platforms in addition to UWP? If JS is the only one that enables markdown and hence whitespace normalization, then perhaps we can have JS to not default to that  (@dclaux )? Marking this Investigate for now to figure out the behavior on other non-JS/non-UWP platforms first.

**Comment by RebeccaAnne** [comment] 2019-07-05 23:44
Part of the issue here is that javascript uses a full markdown parser, whereas shared model platforms are supporting only a limited subset of markdown (by design). We therefore do not see additional markdown behavior such as this. Someone can correct me if I'm wrong, but my understanding is that the by-design behavior for markdown in Adaptive Cards is to only support a very limited subset, but that javascript is using a standard markdown library due to the cost of writing the custom one that would be required to support the by-design behavior.

**Comment by shalinijoshi19** [comment] 2019-07-06 05:03
Interesting. Thanks @RebeccaAnne. Indeed looks like we use[ markdown-it](https://github.com/markdown-it/markdown-it) for JS by default. Was researching and it does indeed look like markdown generates HTML which as David clarifies collapses the whitespaces by default. Looking at this it almost looks like the rest of our renderers should be following suit and collapsing whitespaces as well by default. 
Then if the user would like to add whitespaces to their markdown. something like what's specified [here](https://stackoverflow.com/questions/15721373/how-do-i-ensure-that-whitespace-is-preserved-in-markdown) to create spaces in their markdown content.

**Comment by RebeccaAnne** [comment] 2019-07-08 16:07
I tend to think that since we're not supporting full markdown, we shouldn't collapse spacing, but i don't feel particularly strongly about it. If we do want collapse spacing, we should add it to the list of documented supported markdown features here: https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/text-features. @andrewleader @matthidinger thoughts?

**Comment by andrewleader** [comment] 2019-07-08 16:13
[According to Markdown specs](https://spec.commonmark.org/0.28/#example-185) it seems like whitespace **should** be trimmed. I've filed that inconsistency and a couple others here: https://github.com/microsoft/AdaptiveCards/issues/1984

**Comment by matthidinger** [comment] 2019-07-09 17:18
We're still following a **subset** of markdown (as described in the page Becky linked) correct? If that's the case, I think including whitespace trimming to our subset spec makes sense to consider and include if it's causing compat issues.

**Comment by nesalang** [comment] 2019-08-19 21:15
if there are no markdown tokens in the text, the text should be plain text. The behavior described by JS renderer assumes all text is in markdwon. For iOS, rendering html text is CPU intensive task, and can be handled only in the main thread, so iOS renderer has two paths for rendering text, if there are no markdown tokens, then it's rendered as simple text, and it is faster.

**Comment by shalinijoshi19** [comment] 2019-08-23 01:01
@paulcam206 / @nesalang  can we roll up the markdown inconsistency issues into one bug ? I believe #3348 assigned to @paulcam206 tracks some remaining inconsistencies in the SharedModel -- Also @paulcam206 , should we load balance that out to make progress here?

**Comment by shalinijoshi19** [comment] 2019-08-23 01:04
Resolvine as Duplicate of #3348 that should track addressing this issue

**Closed** 2019-08-23 01:08 UTC
Labels: Bug, BugBash, Inconsistency, Resolution-Duplicate, Triage-Investigate
