### ISSUE TITLE
Pixel based image size not supported in schema

### ISSUE THREAD

**Issue by tfennel** [Microsoft/AdaptiveCards#466] opened 2017-07-11 17:51 UTC
Developers frequently reuse images as a main image and a thumbnail on the same card.  Requiring two different dimensions of that image to be hosted isn't ideal and not everyone has a thumbnail/rendering service they can call out to for on demand image generation.  Reuse of an existing asset would be the easiest, meaning being able to specify the same image in a card, but with pixel dimensions on one or all to achieve the desired size effects.

As an example, on the Netflix site they frequently do a "show card" kind of action to drop down into more details about a title and they reuse the movie art in both places.  I've mocked up how that might work in a card/show card situation below.

![image](https://user-images.githubusercontent.com/18040091/28082225-c13b626c-6626-11e7-8eb9-d39e418fed28.png)

**Comment by matthidinger** [comment] 2018-03-13 22:14
Duplicate of #622

**Closed by matthidinger** 2018-03-13 22:14 UTC
Labels: Area-Schema
