### ISSUE TITLE
Better accessibility support 

### ISSUE THREAD

**Issue by spanwargithub** [Microsoft/AdaptiveCards#511] opened 2017-07-26 03:57 UTC
We would like to see better accessibility support in the schema and the HTML renderer. 
1. Use of proper HTML tags and attributes (e.g  anchor element for hyperlinks, **alt** on image etc)
2.  Support for ARIA attributes
3. Support for high contrast mode

**Comment by matthidinger** [comment] 2017-08-14 21:55
Duplicate of #422

**Closed by matthidinger** 2017-08-14 21:55 UTC
Labels: Area-Renderers, Platform-HTML
