### ISSUE TITLE
[UWP] Background images on columns incorrectly increase height of the column instead of clipping

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2697] opened 2019-04-16 16:09 UTC
# Platform

* UWP

# Version of SDK

Latest master

# Issue

I’ve been looking into an issue with the incorrect rendering of background images (in this case column backgrounds) in the UWP renderer.
I’m not really sure what’s going on, so I wanted to get your opinions on how to approach it.
 
The problem is that when setting a large image as a (column) background with the mode set to stretch/cover, then it expands the column vertically to incorporate the full resolution of the image.
This is clearly incorrect. See below.
 
For the following json:
```json
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "backgroundImage": "https://www.bing.com/th?id=AMMS_925faef413dcd7b32dcd822bf3025c1b",
                    "width": 1
                },
                {
                    "type": "Column",
                    "items": [
                        {
                            "type": "TextBlock",
                            "text": "Some text"
                        }
                    ],
                    "width": 1
                }
            ]
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.1"
}
```
 
I get the following on the 1.2 designer web page (which is what I expect):

![image](https://user-images.githubusercontent.com/13246069/56225980-2e66f080-6027-11e9-80f1-cc005f70c90d.png)

 
 
But in the UWP Visualizer app I get the following:

![image](https://user-images.githubusercontent.com/13246069/56225992-332ba480-6027-11e9-891b-d2104d3d26f6.png)

 
 
I *think* that the problem is to do with the custom measure/arrange override in WholeItemsPanel, as the Image has what I believe to be the correct properties: MaxWidth & MaxHeight set to the image dimensions, Stretch set to UniformToFill.
 
If I set the Image Stetch to Uniform then the Visualizer renders as I’d expect in my case. That’s not really the correct solution though, as that would not always fill the background correctly depending on available space and image aspect ratio.
In our case the image is not behaving as you would expect it to with Stretch set to UniformToFill – the Image should be filling the available space, not defining/expanding it.
 
If I take the created XAML elements and place them inside a StackPanel instead of a WholeItemsPanel then everything renders as expected in a UWP sample app.
I can’t immediately spot the issue in WholeItemsPanel, but I’m guessing that it’s something to do with passing an infinite max height (noVerticalLimit) all the way down into all of the Measure calls.

**Comment by shalinijoshi19** [comment] 2019-04-29 17:38
@paulcam206 load-balancing over to you for 1.2

**Comment by shalinijoshi19** [comment] 2019-05-03 16:24
@RebeccaAnne / @paulcam206 can this be resolved as a dup of #2809 ?

**Comment by paulcam206** [comment] 2019-05-03 17:17
@shalinijoshi19 -- @RebeccaAnne may know more, but at this point I don't think we have enough information to know whether or not these two issues share a root cause...

**Comment by shalinijoshi19** [comment] 2019-05-16 22:53
Reassigning to @almedina-ms for load balancing. Thanks!

**Comment by shalinijoshi19** [comment] 2019-05-19 14:17
Moving this out of 1.2 at this point for fixing post RTM.  @RebeccaAnne / @paulcam206 / @almedina-ms FYI.

**Closed** 2019-05-21 20:55 UTC
Labels: Bug, Platform-UWP, Triage-Approved for Fix
