### ISSUE TITLE
[WPF] Spacing and Separator on some controls has no effect

### ISSUE THREAD

**Issue by mrbrennonwilliams** [Microsoft/AdaptiveCards#1015] opened 2017-12-01 12:35 UTC
Spacing and separators appears to work as expected on Container elements, but for example, spacing and separator have no effect on the ColumnSet element or a textblock inside a column element

As all elements support both these properties, this may require a test of all element implementations

**Comment by almedina-ms** [comment] 2018-11-28 19:42
I'm having trouble reproducing this issue, I ran the wpf visualizer and it looks good

![image](https://user-images.githubusercontent.com/35784165/49177166-5e745800-f301-11e8-8c48-dd6011ade2f3.png)

![image](https://user-images.githubusercontent.com/35784165/49177660-a5168200-f302-11e8-8f0a-01723ca677ae.png)

**Comment by shalinijoshi19** [comment] 2019-04-15 17:14
Looks like this has been fixed in WPF. @mrbrennonwilliams please reactivate with repro steps if you continue to see this. Thanks a ton!

**Closed by shalinijoshi19** 2019-04-15 17:14 UTC
Labels: Area-Renderers, Bug, Platform-.NET
