### ISSUE TITLE
[Android/iOS][Renderer] [iconUrl UI issues for Actions]

### ISSUE THREAD

**Issue by manujai** [microsoft/AdaptiveCards#5087] opened 2020-11-17 17:50 UTC
# Platform

What platform is your issue or question related to? (Delete other platforms).
- [x] Android
- [x] iOS

# Author or host
Host on Webex Teams

# Version of SDK
1.2.12 for Android, 2020.10 (latest master as of Oct 27th) for iOS

# Details
The Action buttons has UI issues when iconUrl is used on both Android and iOS 

Button text pushes itself to the right instead of aligning itself to the centre when iconUrl is used.

Android example - 
![urlasdad](https://user-images.githubusercontent.com/69314716/99403585-a175ce80-2910-11eb-855f-f03387a895e7.png)
(In this case, chevron is disappears/pushed out of the view to the right when iconUrl is used)

iOS example - 
<img width="297" alt="Screenshot 2020-11-12 at 4 48 40 PM" src="https://user-images.githubusercontent.com/69314716/99408195-f6681380-2915-11eb-8c89-78df950b8a16.png">
(The button is height is minimised to contain the icon without any padding) 

<img width="246" alt="Screenshot 2020-11-12 at 4 50 37 PM" src="https://user-images.githubusercontent.com/69314716/99408525-55c62380-2916-11eb-8805-b8edfa4fce53.png">
(Sometimes this is how it shows up in iOS)

**Comment by manujai** [comment] 2020-11-18 05:11
[iconUrl.docx](https://github.com/microsoft/AdaptiveCards/files/5557883/iconUrl.docx)
json payload

**Comment by shalinijoshi19** [comment] 2020-11-30 16:51
Hello @manujai note that we are no longer on master but main. (_Just wanted to make sure that was a typo in the issue description and that you weren't actually referencing our old branch_).. is this somethign that is repro'ing for our latest main/2.x bits?

**Comment by manujai** [comment] 2020-11-30 19:03
@shalinijoshi19 I was referring to the main branch and not master. This issue can be seen in the 2.x bits as well.

**Comment by shalinijoshi19** [comment] 2020-11-30 21:44
Moving out to 21.01 since we havent had a chance to investigate this ahead of the other 1.3 upgrade blockers/Accessibility issues. @jwoo-msft / @golddove pls update with comments here as you investigate.tx

**Comment by jwoo-msft** [comment] 2021-01-15 06:54
@manujai 
I couldn't reproduce the issue of the absence of padding in the top and the bottom of the icon in the sample app.
![image](https://user-images.githubusercontent.com/4112696/104691442-1c622800-56bb-11eb-8e24-14875b3089cc.png)

**Comment by jwoo-msft** [comment] 2021-01-15 07:00
The same payload without icon url in one of the buttons.
![image](https://user-images.githubusercontent.com/4112696/104692124-4700b080-56bc-11eb-9471-b6d90d5f36ca.png)

**Comment by golddove** [comment] 2021-01-15 10:02
@manujai on the latest renderer version, icons are not causing the button height to grow as you describe. Is there a config I am missing?

![image](https://user-images.githubusercontent.com/4442788/104710114-b3e06e80-56ed-11eb-9ff3-3763eb272401.png)

The fix for the disappearing right icon is now in PR.

**Comment by golddove** [comment] 2021-01-21 19:19
Android PR is merged.

**Comment by manujai** [comment] 2021-01-22 15:51
[hostCapabilities.docx](https://github.com/microsoft/AdaptiveCards/files/5856920/hostCapabilities.docx)
Hi Risheek, 
I checked again with ACL 2.4.0 (Android) and I was able to reproduce the expanding iconUrl issue. 
Can you please try using this host config for Android to reproduce the issue. 
ACL version used: 2.4.0

**Comment by golddove** [comment] 2021-01-28 04:20
@manujai I've tried again with the payload you provided above (iconUrl.docx) and the host config (hostCapabilities.docx) in our sample app, from the `release/20.12` branch. This is the card I get in that config:

![image](https://user-images.githubusercontent.com/4442788/106089464-fa729780-60f5-11eb-87d0-84572c1aeaa7.png)

Let's set up a call to try to identify why you are seeing different behavior

**Comment by manujai** [comment] 2021-01-28 05:06
Sure @golddove 
Let's connect later and try to narrow it down. Thanks!

**Comment by golddove** [comment] 2021-02-11 15:58
Diagnosed an issue with using a resource resolver with icon sizing. The fix will be in included in the 21.02 release.

**Comment by golddove** [comment] 2021-02-25 15:56
Removed ResourceResolver issue from this description and split off to #5431. @jwoo-msft, if the iOS part of this is complete, feel free to close.

**Comment by jwoo-msft** [comment] 2021-03-04 19:28
Closing this issue since the issues mentioned are fixed. Opened a new issue that tracks icon placement issue. https://github.com/microsoft/AdaptiveCards/issues/5517

**Closed by jwoo-msft** 2021-03-04 19:28 UTC
Labels: 1.3 Upgrade Blocker, Bug, CiscoWebEx-Integration, High Priority, Needs: Attention :wave:, Triage-Approved for Fix
