### ISSUE TITLE
[Android]Complex layout will freeze when recyclerview merge to androidx

### ISSUE THREAD

**Issue by kexuejin** [microsoft/AdaptiveCards#4711] opened 2020-09-01 02:30 UTC
# Android

* Android

# Version of SDK

2.0.0

# Details

The sample demo is base on android support framework, but when recyclerview merge to androidx and load complex json, such as FlightDetails.json, it list will freeze and card view refresh the height repeatedly.
There have a sample demo [Sample.zip](https://github.com/microsoft/AdaptiveCards/files/5153594/Sample.zip)

**Comment by shalinijoshi19** [comment] 2020-09-04 07:05
@almedina-ms could you please take a look at this one and see what's going on? Thanks

**Comment by almedina-ms** [comment] 2020-09-14 18:37
we currently haven't supported ```androidx``` libraries, ```support``` libraries and ```androidx``` sometimes are not interchangeable. @golddove made a PR for us to migrate into androidx but we haven't figured out yet if there are any rendering side effects as well as we don't know how many customers are still using support libraries that may need fixes still using support packages. We could be releasing two packages at the same time with one being flagged as androidx to support this kind of scenarios but that would increase a little overhead on dev, test and building processes.

**Comment by shalinijoshi19** [comment] 2020-09-21 20:04
Thanks; have moved this to our backlog and assigning to @golddove to investigate as part of his ES explorations.

**Comment by shalinijoshi19** [comment] 2020-09-21 20:05
> we currently haven't supported `androidx` libraries, `support` libraries and `androidx` sometimes are not interchangeable. @golddove made a PR for us to migrate into androidx but we haven't figured out yet if there are any rendering side effects as well as we don't know how many customers are still using support libraries that may need fixes still using support packages. We could be releasing two packages at the same time with one being flagged as androidx to support this kind of scenarios but that would increase a little overhead on dev, test and building processes.

@kexuejin based on @almedina-ms 's response above, looks like we don't support androidx libraries at this point. How blocked are you on this?

**Comment by kexuejin** [comment] 2020-09-22 01:13
> > we currently haven't supported `androidx` libraries, `support` libraries and `androidx` sometimes are not interchangeable. @golddove made a PR for us to migrate into androidx but we haven't figured out yet if there are any rendering side effects as well as we don't know how many customers are still using support libraries that may need fixes still using support packages. We could be releasing two packages at the same time with one being flagged as androidx to support this kind of scenarios but that would increase a little overhead on dev, test and building processes.
> 
> @kexuejin based on @almedina-ms 's response above, looks like we don't support androidx libraries at this point. How blocked are you on this?

https://developer.android.com/jetpack/androidx/migrate , The Android plugin uses the appropriate AndroidX library instead of a Support Library. So we can use AdaptiveCards sdk for Androidx.

**Comment by golddove** [comment] 2020-10-05 16:22
Blocked on #4477

**Comment by golddove** [comment] 2020-10-05 16:25
Because migrating to AndroidX would be a breaking change, we need to confirm with our partners that they are not using the deprecated support libraries.

**Comment by golddove** [comment] 2020-10-09 03:42
WebEx Teams has confirmed they are using AndroidX libraries.

**Comment by kexuejin** [comment] 2020-10-09 07:15
I noticed that the latest version(2.2.0) uses flexbox to render Columns, but the version 1.0.0 is used instead of the latest 2.0.1, and the sliding still freezes. When I try to upgrade the flexbox version to 2.0.1, the sliding is smooth. But it will report java.lang.OutOfMemoryError.

2020-10-09 15:04:02.641 25759-25759/com.example.mobilechatapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.mobilechatapp, PID: 25759
    java.lang.OutOfMemoryError
        at android.graphics.Bitmap.nativeCreate(Native Method)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1165)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1115)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1065)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1026)
        at io.adaptivecards.renderer.BackgroundImageLoaderAsync$BackgroundImageDrawable.resizeBitmapForCover(BackgroundImageLoaderAsync.java:113)
        at io.adaptivecards.renderer.BackgroundImageLoaderAsync$BackgroundImageDrawable.draw(BackgroundImageLoaderAsync.java:80)

This seems 'getScaleFactorForCover' method has issue, and result very huge scale.

**Comment by golddove** [comment] 2020-10-29 09:31
Cisco WebEx is using AndroidX.

Microsoft Teams is also using AndroidX.

@matthidinger what other partners should we check with about a breaking change on Android?

**Comment by RebeccaAnne** [comment] 2021-03-18 20:19
We have decided to go ahead and take this breaking change based on the partner confirmations above and at the community call.

**Closed** 2021-04-12 16:22 UTC
Labels: Bug, Status-In Code Review, Triage-Approved for Fix, Triage-Reviewed-21.03
