### ISSUE TITLE
Adaptive cards v1.1 - iconUrl in action.openUrl do not work for "selectAction" on a column

### ISSUE THREAD

**Issue by sravanthialuri** [Microsoft/AdaptiveCards#2105] opened 2018-10-18 21:07 UTC
Excited about the new Adaptive cards v1.1. Thanks to the team for the great useful features. I'm trying to use one of the most useful one for our project the "iconUrl". 

The "iconUrl" works great when included in the "Actions" "action.openUrl" but I'm unable to see the icon image when used on a Column. Below is the sample code.

```
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.1",
	"body": [
		{
			"type": "ColumnSet",
			"columns": [
				{
					"type": "Column",
					"items": [
						{
							"type": "TextBlock",
							"text": "Column 1"
						}						
					],
					"selectAction": {
						"type": "Action.OpenUrl",
                        "iconUrl": "http://adaptivecards.io/content/cats/1.png",
						"title": "cool link",
						"url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
					}
				}
		    ]
		}
	],
    "actions":[
        {
            "type": "Action.OpenUrl",
            "iconUrl": "http://adaptivecards.io/content/cats/1.png",
            "title": "cool link",
            "url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
        }
    ]
}
```

**Comment by nesalang** [comment] 2018-10-18 23:04
Can you specify which platform(s) you are seeing this issue?

**Comment by andrewleader** [comment] 2018-10-19 00:05
Hey @sravanthialuri 

selectActions do NOT show any visuals. They are purely touch targets. The `title` property can be used for accessibility purposes (screen readers, tooltips, etc), but the `iconUrl` is not used by design. It is only seen in buttons within the `actions` array (just as `title` is really only seen in buttons).

If you need an image, you can add an `Image` element.

If that doesn't work for your scenario, let us know why! Closing this for now. Thanks!

**Closed by andrewleader** 2018-10-19 00:05 UTC
