### ISSUE TITLE
[Rendering] HTML Renderer Action.Execute for Input.Toggle puts quotes around result 

### ISSUE THREAD

**Issue by tomlm** [microsoft/AdaptiveCards#6670] opened 2021-11-01 18:51 UTC
### Target Platforms

Other

### SDK Version

2.7

### Application Name

HTML

### Problem Description

When I have bool true, false values the Action.execute post back has quotes around the value.

Expected:
data.X = true|false

### Screenshots

![image](https://user-images.githubusercontent.com/17789481/139725069-a092b29c-6ff3-4a38-a614-ebd0923b6ac7.png)

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5",
    "actions": [
        {
            "type": "Action.Execute",
            "title": "Action.Execute"
        }
    ],
    "body": [
        {
            "type": "Input.Toggle",
            "title": "New Input.Toggle",
            "id": "X",
            "valueOn":true,
            "valueOff": false        
        }
    ]
}
```

**Comment by dclaux** [comment] 2021-11-02 21:55
@tomlm that's by design (and you contributed to it ;)) - Input.Toggle's values (value, valueOn, valueOff) are all strings. https://adaptivecards.io/explorer/Input.Toggle.html

**Comment by jonmill** [comment] 2021-11-04 20:14
Closing as by-design per David...Tom if you want this to be a request to change this, please re-open and I'll change this to a feature request

**Closed by jonmill** 2021-11-04 20:14 UTC
Labels: Bug, Area-Renderers, Triage-Needed
