### ISSUE TITLE
[Android][Image rendering] Image sizes are not being respected when rendering inside a column

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#5054] opened 2020-11-06 20:32 UTC
# Platform

- [ ] Android

# Version of SDK

main

# Details

When images are rendered inside a column, they may shrink to allow other columns have enough space to render, this provokes behaviours as documented in #4988 , a revision must be made to verify what is the actual behaviour we want as cards as `1.2/Scenarios/FlightUpdate` expect images to shrink

**Comment by golddove** [comment] 2020-11-06 21:31
Closing as duplicate of #4988

**Closed by golddove** 2020-11-06 21:31 UTC
Labels: Bug, Msft-TeamsMobile, Platform-Android, Priority-Now
