### ISSUE TITLE
[iOS-UWP][ColumnSet Parity Issue] [Parity issue between iOS and desktop for image width in columnSet]

### ISSUE THREAD

**Issue by adumrewal** [microsoft/AdaptiveCards#4504] opened 2020-07-31 10:04 UTC
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Author or host

Host - Teams iOS

# Version of SDK

Release 1.2.10

# Details

Parity issue between desktop and iOS OOB experience for the following JSON.
iOS:
<img width="353" alt="Screenshot 2020-07-31 at 3 30 01 PM" src="https://user-images.githubusercontent.com/8917620/89024456-c08d2800-d342-11ea-8f76-9ad51bfe3f52.png">
Desktop:
<img width="434" alt="Screenshot 2020-07-31 at 3 29 48 PM" src="https://user-images.githubusercontent.com/8917620/89024466-c420af00-d342-11ea-88cf-a82fa834b71a.png">

[ACColumnSetImageWidth.txt](https://github.com/microsoft/AdaptiveCards/files/5006405/ACColumnSetImageWidth.txt)
```
{
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "items": [
            {
              "type": "TextBlock",
              "size": "ExtraLarge",
              "weight": "Lighter",
              "text": "BLR"
            }
          ],
          "width": "auto"
        },
        {
          "type": "Column",
          "verticalContentAlignment": "Center",
          "items": [
            {
              "type": "Image",
              "url": "https://messagecardplayground.azurewebsites.net/assets/graydot2x2.png",
              "width": "10000px",
              "height": "2px"
            }
          ],
          "width": "stretch"
        },
        {
          "type": "Column",
          "spacing": "Small",
          "verticalContentAlignment": "Center",
          "items": [
            {
              "type": "Image",
              "url": "https://messagecardplayground.azurewebsites.net/assets/smallairplane.png",
              "height": "16px",
              "altText": "Flight to"
            }
          ],
          "width": "auto"
        },
        {
          "type": "Column",
          "items": [
            {
              "type": "TextBlock",
              "horizontalAlignment": "Right",
              "size": "ExtraLarge",
              "weight": "Lighter",
              "text": "CDG"
            }
          ],
          "width": "auto"
        }
      ],
      "height": "stretch"
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.0"
}
```

**Comment by jwoo-msft** [comment] 2020-10-21 23:38
@shalinijoshi19 PR for the issue is merged and closed for iOS.

**Comment by shalinijoshi19** [comment] 2020-10-22 14:40
Thanks. @almedina-ms is this on your radar at all for Android?

**Closed** 2020-10-22 23:47 UTC
Labels: AdaptiveCards v20.10, Area-Inconsistency, Bug, CiscoWebEx-Integration, Msft-TeamsMobile, MsftTeams-Integration, Priority-Now, Status-In Code Review, Triage-Approved for Fix
