### ISSUE TITLE
[iOS] Select Action not working with images in imageSet

### ISSUE THREAD

**Issue by jykukrej** [microsoft/AdaptiveCards#8105] opened 2022-12-06 16:27 UTC
### Target Platforms

iOS

### SDK Version

latest master

### Application Name

Microsoft Teams

### Problem Description

When images are present with in a `imagesSet`, select action is not working. When we tap on the image (that has select action registered), nothing happened. Is this the expected behaviour on iOS client? 
It is working as expected in JS SDK. Select action is working on JS SDK.

### Screenshots

<img width="443" alt="Screenshot 2022-12-06 at 9 49 20 PM" src="https://user-images.githubusercontent.com/59954612/205966709-776e6726-03db-4a17-8a85-b087defb1ab5.png">

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body":[
        {
           "spacing":"medium",
           "type":"ImageSet",
           "imageSize":"large",
           "images":[
              {
                 "height":"auto",
                 "id":"thumb-0",
                 "size":"stretch",
                 "altText":"a pencil and watercolor drawing of a bright city in the future with flying cars",
                 "type":"Image",
                 "selectAction":{
                    "title":"Open",
                    "data":{
                       "msteams":{
                          "type":"task\/fetch"
                       }
                    },
                    "type":"Action.Submit"
                 },
                 "url":"https://adaptivecards.io/content/cats/1.png"
              },
              {
                 "height":"auto",
                 "id":"thumb-1",
                 "size":"stretch",
                 "altText":"a pencil and watercolor drawing of a bright city in the future with flying cars",
                 "type":"Image",
                 "selectAction":{
                    "title":"Open",
                    "data":{
                       "msteams":{
                          "type":"task\/fetch"
                       }
                    },
                    "type":"Action.Submit"
                 },
                 "url":"https://adaptivecards.io/content/cats/1.png"
              }
           ]
        }
     ]
}
```

**Comment by jwoo-msft** [comment] 2022-12-12 23:47
duplicate of #8044

**Closed by jwoo-msft** 2022-12-12 23:47 UTC
Labels: Bug, Area-Renderers
