### ISSUE TITLE
[Javascript] Empty Input.Date on AdaptiveCards

### ISSUE THREAD

**Issue by pedroacuma** [microsoft/AdaptiveCards#3631] opened 2019-11-21 08:55 UTC
# Platform
* JavaScript

# Author or host
Microsoft Teams

If you're an author, who are you sending cards to?

# Version of SDK
I'm using botbuilder 3.11 and botbuilder-teams 0.2.6.

# Details
I've built an adaptive cards with a Input.Date where user can select a date.

`{
                    "type": "Container",
                    "items": [
                        {
                            "type": "ColumnSet",
                            "columns": [
                                {
                                    "type": "Column",
                                    "width": "auto",
                                    "items": [
                                        {
                                            "type": "TextBlock",
                                            "text": "Select from 📅",
                                            "size": "medium",
                                            "wrap": true
                                        }
                                    ]
                                },
                                {
                                    "type": "Column",
                                    "width": "auto",
                                    "items": [
                                        {
                                            "type": "Input.Date",
                                            "id": "startDate",
                                            "value": ""
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }`

This is part of the card. The card is sent to Microsoft Teams and renders properly. Here comes the bug:

If the Teams client is on mobile there is no problem. But if the client is web, the Input.Date value is only being returned when the user locale is English. I think this happens because of the default date format.
I've tried with Spanish, Deustch and other languages and the date value is not returned.
As I said if I do it from Microsoft Teams mobile app this problem is solved.

Other users have reported similar problems:
[https://github.com/OfficeDev/BotBuilder-MicrosoftTeams/issues/195](url)
[https://github.com/microsoft/botframework-sdk/issues/5411](url)

**Comment by matthidinger** [comment] 2019-11-25 19:05
@shalinijoshi19 @siduppal any idea if this is part of the upcoming patch?

**Comment by shalinijoshi19** [comment] 2019-11-25 23:27
This is not part of the 1.2.5 patch.  To recap:  [JS fixes going in for November](https://github.com/microsoft/AdaptiveCards/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22AdaptiveCards+v1.2.5%22+label%3AMsftTeams-Integration+-label%3A%22Msft-TeamsMobile%22)  

@dclaux mind taking a first stab at this please?  Thanks!

**Comment by dclaux** [comment] 2019-11-25 23:46
I can't reproduce this using the out-of-box JS implementation. But Teams replaces the HTML5 date input control with their own, which is probably the culprit. In other words, I believe this is a Teams bug, not a JS renderer bug.

**Comment by shalinijoshi19** [comment] 2019-11-26 00:09
@siduppal / @clearab / @susanshen96 heads up; Can somebody from the teams side pick this up please?

**Comment by susanshen96** [comment] 2019-11-26 00:12
@shalinijoshi19 - We have a bug for this issue - fix is pending, will post update when it's checked in.

**Comment by shalinijoshi19** [comment] 2019-11-26 00:13
Thanks @susanshen96 ! Any chance we can reference the bug here over github or is it being tracked internally? @pedroacuma fyi.

**Comment by susanshen96** [comment] 2019-11-26 00:56
@shalinijoshi19 - it's being tracked internally.

**Comment by pedroacuma** [comment] 2019-12-11 08:00
Any updates on the bug solution?

**Comment by susanshen96** [comment] 2019-12-12 19:07
@pedroacuma The fix should be in the public build of Teams now - please try out a card with Input.Date and see if it's being sent correctly, and let me know otherwise. Thanks!

**Comment by RebeccaAnne** [comment] 2020-07-27 22:10
Per comment above this should be fixed now. Please reactivate if there are further concerns!

**Closed by RebeccaAnne** 2020-07-27 22:10 UTC
Labels: Bug, MsftTeams-Integration, Platform-HTML, Triage-External, no-recent-activity
