### ISSUE TITLE
Adaptive card designer - Add custom action/element and show it in the designer

### ISSUE THREAD

**Issue by Trish92** [microsoft/AdaptiveCards#5326] opened 2021-01-27 19:56 UTC
# Platform

What platform is your issue or question related to? (Delete other platforms).

* JavaScript

# Author or host

Author

# Version of SDK

latest

# Issue
https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/javascript/extensibility 

This documentation shows an example to show a progress bar and create your own action 
But how do I then show those in the designer ? Where can I find documentation for the same? 

For the ProgressBarPeer, this is my class type : export class ProgressBarPeer extends ACDesigner.TypedCardElementPeer<ProgressBar>

This is  what I sent to  registerPeer :  ACDesigner.CardDesignerSurface.cardElementPeerRegistry.registerPeer(
      ProgressBar,
      ProgressBarPeer,
      "Elements",
      'acd-icon-columnSet'
    );
If I use AC.TextBlock instead of my own custom component ProgressBar I do see changes in the properties as defined in my ProgressBarPeer

Please let me know what maybe missing  to see the ProgressBar under elements in the designer. I am using all the latest npm packages.
I am attaching as evidence my registry that contains an action and an element with their peers.
It would be great if there was some more documentation and an example for adding an action and an element to the designer. Thanks.
 
@matthidinger @dclaux

**Comment by Trish92** [comment] 2021-01-27 23:06
https://github.com/microsoft/AdaptiveCards/discussions/5240   Following this

**Comment by Trish92** [comment] 2021-01-28 00:48
![image](https://user-images.githubusercontent.com/15216947/106073757-a7d6b280-60d8-11eb-802e-d04ce05f33b0.png)

**Comment by Trish92** [comment] 2021-02-28 04:30
![image](https://user-images.githubusercontent.com/15216947/109408032-c3411180-7953-11eb-84fe-4732e6c8a3d5.png)

**Comment by Trish92** [comment] 2021-04-12 15:34
#5240

**Comment by jonmill** [comment] 2021-05-27 20:28
Dupe of #5652

**Closed by jonmill** 2021-05-27 20:28 UTC
