### ISSUE TITLE
Teams native reply input ontop of ios dropdown picker

### ISSUE THREAD

**Issue by jameskleinschnitz** [microsoft/AdaptiveCards#5754] opened 2021-04-30 20:03 UTC
# Target Platform

Please list the platform(s) that your application is targeting and remove platforms you are not targeting:

- iOS

# Target Application

Teams on iOS

# Problem Description
 I have an adaptive card with a form for setting ticket values, on iOS when I try to select the value from one of the form dropdowns, the native teams reply input is on top of native iOS dropdown picker

# Screenshot

![iOS-adaptivecard-picker-issue](https://user-images.githubusercontent.com/3209749/116748544-dc4e5900-a9bc-11eb-8a1a-68add8ff0f7d.png)

# Card JSON
`
{
    "type": "AdaptiveCard",
    "version": "1.2",
    "body": [
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "width": "stretch",
                    "items": [
                        {
                            "type": "TextBlock",
                            "size": "Medium",
                            "weight": "Bolder",
                            "text": "Ticket has been updated"
                        },
                        {
                            "type": "TextBlock",
                            "weight": "Lighter",
                            "text": ""
                        }
                    ],
                    "style": "emphasis",
                    "bleed": true,
                    "isVisible": false
                }
            ]
        },
        {
            "type": "TextBlock",
            "size": "Large",
            "weight": "Bolder",
            "text": "[Active]: Ticket #6",
            "wrap": true
        },
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "width": "auto",
                    "items": [
                        {
                            "type": "Image",
                            "size": "Small",
                            "style": "Person",
                            "url": "https://teams.microsoft.com/api/mt/emea/beta/users/admin@ciresondev.onmicrosoft.com/profilepicturev2?displayname=Lelouche Lamperouge&voidCache=false"
                        }
                    ]
                },
                {
                    "type": "Column",
                    "width": "stretch",
                    "items": [
                        {
                            "type": "TextBlock",
                            "weight": "Bolder",
                            "text": "Lelouche Lamperouge",
                            "wrap": true
                        },
                        {
                            "type": "TextBlock",
                            "text": "Created {{DATE(2021-01-26T19:33:44Z, SHORT)}}",
                            "wrap": true,
                            "spacing": "None"
                        }
                    ]
                }
            ]
        },
        {
            "type": "TextBlock",
            "weight": "Lighter",
            "text": "create this ticket for me.",
            "wrap": true
        },
        {
            "type": "FactSet",
            "facts": [
                {
                    "title": "Category:",
                    "value": "Networking"
                },
                {
                    "title": "Priority:",
                    "value": "2 (Medium)"
                },
                {
                    "title": "Assignee:",
                    "value": "Unassigned "
                },
                {
                    "title": "Due Date:",
                    "value": "{{DATE(0001-01-01T00:00:00Z,SHORT)}} at {{TIME(0001-01-01T00:00:00Z)}}"
                },
                {
                    "title": "Modified:",
                    "value": "{{DATE(2021-01-26T19:33:44Z,SHORT)}} at {{TIME(2021-01-26T19:33:44Z)}}"
                },
                {
                    "title": "Tags:",
                    "value": "None"
                }
            ]
        },
        {
            "type": "TextBlock",
            "text": " "
        },
        {
            "type": "Container",
            "items": [
                {
                    "id": "ticketActionsContainer",
                    "type": "ActionSet",
                    "actions": [
                        {
                            "type": "Action.Submit",
                            "id": "TakeTicket",
                            "data": {
                                "userId": "${user.Id}",
                                "ticket": 6,
                                "commandId": "TakeTicket"
                            },
                            "title": "Take"
                        },
                        {
                            "type": "Action.ToggleVisibility",
                            "id": "replyBtnId",
                            "targetElements": [
                                "replyContainer",
                                {
                                    "elementId": "modifyContainer",
                                    "isVisible": false
                                },
                                {
                                    "elementId": "tagContainer",
                                    "isVisible": false
                                }
                            ],
                            "title": "Reply"
                        },
                        {
                            "type": "Action.ToggleVisibility",
                            "id": "modifyBtnId",
                            "targetElements": [
                                {
                                    "elementId": "replyContainer",
                                    "isVisible": false
                                },
                                {
                                    "elementId": "tagContainer",
                                    "isVisible": false
                                },
                                "modifyContainer"
                            ],
                            "title": "Modify"
                        },
                        {
                            "type": "Action.ToggleVisibility",
                            "id": "addtagsBtnId",
                            "targetElements": [
                                {
                                    "elementId": "replyContainer",
                                    "isVisible": false
                                },
                                {
                                    "elementId": "modifyContainer",
                                    "isVisible": false
                                },
                                "tagContainer"
                            ],
                            "title": "Tag"
                        },
                        {
                            "type": "Action.OpenUrl",
                            "id": "ChatWithRequesterId",
                            "url": "https://teams.microsoft.com/l/chat/0/0?users=admin@ciresondev.onmicrosoft.com",
                            "title": "Chat with Lelouche"
                        }
                    ]
                },
                {
                    "type": "Container",
                    "id": "displayActionsContainer",
                    "items": [
                        {
                            "type": "Container",
                            "id": "modifyContainer",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "weight": "Bolder",
                                    "text": "Modify this Ticket"
                                },
                                {
                                    "type": "ColumnSet",
                                    "columns": [
                                        {
                                            "type": "Column",
                                            "width": "80px",
                                            "items": [
                                                {
                                                    "type": "TextBlock",
                                                    "text": "Status",
                                                    "wrap": true
                                                }
                                            ],
                                            "verticalContentAlignment": "Center",
                                            "height": "stretch"
                                        },
                                        {
                                            "type": "Column",
                                            "width": "stretch",
                                            "items": [
                                                {
                                                    "type": "Input.ChoiceSet",
                                                    "id": "changeStatusOptions",
                                                    "value": "16",
                                                    "style": "compact",
                                                    "isMultiSelect": false,
                                                    "choices": [
                                                        {
                                                            "title": "Active",
                                                            "value": "16"
                                                        },
                                                        {
                                                            "title": "Pending",
                                                            "value": "17"
                                                        },
                                                        {
                                                            "title": "Resolved",
                                                            "value": "18"
                                                        },
                                                        {
                                                            "title": "Closed",
                                                            "value": "19"
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    "type": "ColumnSet",
                                    "columns": [
                                        {
                                            "type": "Column",
                                            "width": "80px",
                                            "items": [
                                                {
                                                    "type": "TextBlock",
                                                    "text": "Category",
                                                    "wrap": true
                                                }
                                            ],
                                            "verticalContentAlignment": "Center",
                                            "height": "stretch"
                                        },
                                        {
                                            "type": "Column",
                                            "width": "stretch",
                                            "items": [
                                                {
                                                    "type": "Input.ChoiceSet",
                                                    "id": "changeCategoryOptions",
                                                    "value": "1",
                                                    "style": "compact",
                                                    "isMultiSelect": false,
                                                    "choices": [
                                                        {
                                                            "title": "Networking",
                                                            "value": "1"
                                                        },
                                                        {
                                                            "title": "Onboarding",
                                                            "value": "2"
                                                        },
                                                        {
                                                            "title": "Permissions",
                                                            "value": "3"
                                                        },
                                                        {
                                                            "title": "Printing",
                                                            "value": "4"
                                                        },
                                                        {
                                                            "title": "Software",
                                                            "value": "5"
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    "type": "ColumnSet",
                                    "columns": [
                                        {
                                            "type": "Column",
                                            "width": "80px",
                                            "items": [
                                                {
                                                    "type": "TextBlock",
                                                    "text": "Priority",
                                                    "wrap": true
                                                }
                                            ],
                                            "verticalContentAlignment": "Center"
                                        },
                                        {
                                            "type": "Column",
                                            "width": "stretch",
                                            "items": [
                                                {
                                                    "type": "Input.ChoiceSet",
                                                    "id": "changePriorityOptions",
                                                    "value": "12",
                                                    "style": "compact",
                                                    "isMultiSelect": false,
                                                    "choices": [
                                                        {
                                                            "title": "1 (High)",
                                                            "value": "11"
                                                        },
                                                        {
                                                            "title": "2 (Medium)",
                                                            "value": "12"
                                                        },
                                                        {
                                                            "title": "3 (Low)",
                                                            "value": "13"
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    "type": "ColumnSet",
                                    "columns": [
                                        {
                                            "type": "Column",
                                            "width": "80px",
                                            "items": [
                                                {
                                                    "type": "TextBlock",
                                                    "text": "Assignee",
                                                    "wrap": true
                                                }
                                            ],
                                            "verticalContentAlignment": "Center"
                                        },
                                        {
                                            "type": "Column",
                                            "width": "stretch",
                                            "items": [
                                                {
                                                    "type": "Input.ChoiceSet",
                                                    "id": "changeAssigneeOptions",
                                                    "value": "",
                                                    "style": "compact",
                                                    "isMultiSelect": false,
                                                    "choices": [
                                                        {
                                                            "title": "LAPTOP-P33KB2TI\\\\Administrator",
                                                            "value": "1"
                                                        },
                                                        {
                                                            "title": "Lelouche Lamperouge",
                                                            "value": "2"
                                                        },
                                                        {
                                                            "title": "Nestor Wilke",
                                                            "value": "3"
                                                        },
                                                        {
                                                            "title": "Adele Vance",
                                                            "value": "4"
                                                        },
                                                        {
                                                            "title": "Isaiah Langer",
                                                            "value": "5"
                                                        },
                                                        {
                                                            "title": "Lee Gu",
                                                            "value": "6"
                                                        },
                                                        {
                                                            "title": "Pradeep Gupta",
                                                            "value": "7"
                                                        },
                                                        {
                                                            "title": "Lidia Holloway",
                                                            "value": "8"
                                                        },
                                                        {
                                                            "title": "Patti Fernandez",
                                                            "value": "9"
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    "type": "ColumnSet",
                                    "columns": [
                                        {
                                            "type": "Column",
                                            "width": "80px",
                                            "items": [
                                                {
                                                    "type": "TextBlock",
                                                    "text": "Due Date",
                                                    "wrap": true
                                                }
                                            ],
                                            "verticalContentAlignment": "Center"
                                        },
                                        {
                                            "type": "Column",
                                            "width": "stretch",
                                            "items": [
                                                {
                                                    "type": "Input.Date",
                                                    "id": "changeDueDate"
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    "type": "ActionSet",
                                    "actions": [
                                        {
                                            "type": "Action.Submit",
                                            "id": "ModifyTicket",
                                            "data": {
                                                "ticket": 6,
                                                "commandId": "ModifyTicket",
                                                "FilterValue": "${FilterValue}",
                                                "SearchText": "${SearchText}"
                                            },
                                            "title": "OK"
                                        }
                                    ]
                                }
                            ],
                            "style": "emphasis",
                            "bleed": false,
                            "isVisible": false
                        },
                        {
                            "type": "Container",
                            "id": "replyContainer",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "weight": "Bolder",
                                    "text": "Reply to Ticket",
                                    "wrap": true
                                },
                                {
                                    "type": "Input.Text",
                                    "id": "comment",
                                    "placeholder": "Add a comment",
                                    "isMultiline": true
                                },
                                {
                                    "type": "Input.Toggle",
                                    "id": "private",
                                    "title": "Private",
                                    "valueOn": "false",
                                    "valueOff": "true"
                                },
                                {
                                    "type": "ActionSet",
                                    "actions": [
                                        {
                                            "type": "Action.Submit",
                                            "id": "AddComment",
                                            "data": {
                                                "ticket": 6,
                                                "commandId": "AddComment",
                                                "FilterValue": "${FilterValue}",
                                                "SearchText": "${SearchText}"
                                            },
                                            "title": "Send"
                                        },
                                        {
                                            "type": "Action.Submit",
                                            "id": "AddCommentAndKB",
                                            "data": {
                                                "ticket": 6,
                                                "question": "create this ticket for me.",
                                                "commandId": "AddCommentAndKB",
                                                "FilterValue": "${FilterValue}",
                                                "SearchText": "${SearchText}",
                                                "msteams": {
                                                    "type": "task/fetch"
                                                }
                                            },
                                            "title": "Send & Add to KB"
                                        }
                                    ]
                                }
                            ],
                            "style": "emphasis",
                            "bleed": false
                        },
                        {
                            "type": "Container",
                            "id": "tagContainer",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "weight": "Bolder",
                                    "text": "Tag a Ticket:",
                                    "wrap": true
                                },
                                {
                                    "type": "TextBlock",
                                    "size": "Small",
                                    "weight": "Lighter",
                                    "text": "Tags must be space-delimited",
                                    "wrap": true,
                                    "spacing": "None"
                                },
                                {
                                    "type": "Input.Text",
                                    "id": "tags",
                                    "placeholder": "Add Tag (Example: Tag1 Tag2)"
                                },
                                {
                                    "type": "ActionSet",
                                    "actions": [
                                        {
                                            "type": "Action.Submit",
                                            "id": "AddTags",
                                            "data": {
                                                "ticket": 6,
                                                "commandId": "AddTags",
                                                "FilterValue": "${FilterValue}",
                                                "SearchText": "${SearchText}"
                                            },
                                            "title": "OK"
                                        }
                                    ]
                                }
                            ],
                            "style": "emphasis",
                            "bleed": false,
                            "isVisible": false
                        }
                    ],
                    "style": "default"
                },
                {
                    "type": "Container",
                    "items": [
                        {
                            "type": "ActionSet",
                            "actions": [
                                {
                                    "type": "Action.Submit",
                                    "id": "HiddenButton",
                                    "title": "HiddenButton"
                                }
                            ],
                            "isVisible": false
                        }
                    ],
                    "isVisible": false
                }
            ],
            "style": "default"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}
`

# Sample Code

Please provide any relevant code samples to help reproduce the issue

# Version of SDK

1.2

**Comment by jwoo-msft** [comment] 2021-05-04 18:40
c.c @lindach167

**Comment by linda167** [comment] 2021-05-05 02:50
@jwoo-msft duplicate of previous issue we discussed. We are taking a fix for it this sprint in Teams

**Comment by jwoo-msft** [comment] 2021-05-05 18:07
@linda167, thank you!

**Comment by jonmill** [comment] 2021-05-06 20:37
Closed as a dupe for Teams; @linda167 can you please link to any open issue in GitHub that is tracking this?

**Closed by jonmill** 2021-05-06 20:37 UTC
Labels: Area-Renderers, Bug, Partner-MsftTeamsMobile, Resolution-External, Triage-Needed

**Comment by linda167** [comment] 2021-05-06 20:49
This was the previous issue discussed:
https://github.com/microsoft/AdaptiveCards/issues/5276
