### ISSUE TITLE
Action title: required or not?

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#2189] opened 2018-11-27 03:50 UTC
# Platform

* .NET HTML
* .NET WPF
* Android
* iOS
* JavaScript
* UWP

# Issue

Similar to #2111. I haven't been able to validate behavior between renderers (VS is updating), but at least in the visualizer, if you leave out an action's title, you get a warning:

```json
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
	],
	"actions": [
		{
			"type": "Action.OpenUrl",
			"url": "http://adaptivecards.io"
		}
	]
}
```
Warning given: `Actions should always have a title.`

However, according to our schema, title isn't required. Buttons render weird (at least in HTML) if a title isn't given, though. Should `title` be required? Should we have better default behavior in the absence of a `title`?

**Comment by khouzam** [comment] 2018-11-28 18:42
This is related to #1882

**Comment by jonmill** [comment] 2021-11-04 22:44
Dupe of #1882

**Closed by jonmill** 2021-11-04 22:44 UTC
Labels: Bug, Area-Inconsistency
