### ISSUE TITLE
[Programmatic access - Adaptive Cards - ExpenseReport.JSON] The name property of focusable element must not be NULL

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#7012] opened 2022-02-08 02:04 UTC
https://microsoft.visualstudio.com/OS/_workitems/edit/37140182

**Comment by carlos-zamora** [comment] 2022-03-16 23:25
Closing. This is a duplicate of https://github.com/microsoft/AdaptiveCards/issues/6274.

**Closed by carlos-zamora** 2022-03-16 23:25 UTC
Labels: Platform-XAML, Area-Accessibility, Accessibility-Sev2-Scorecard
