### ISSUE TITLE
[iOS][Action.ShowCard] ShowCard not expanding the card

### ISSUE THREAD

**Issue by Aditya0603** [microsoft/AdaptiveCards#3553] opened 2019-10-31 07:13 UTC
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Author or host

Host
If you're an author, who are you sending cards to?

# 1.2

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...

# Details

ShowCard action does not expand the card on adaptiveCards v1.2, seems to be working fine on 1.3

Inline is the payload

{"body":[{"items":[{"size":"medium","weight":"bolder","type":"TextBlock","text":"🎉🎉  Ment.io was installed in Teams Platform!"}],"type":"Container"},{"items":[{"type":"TextBlock","text":"Now that you installed Ment.io, you can create questions, collect answers with reasoning, pin the discussion over time, and get useful discussion analytics","wrap":true}],"type":"Container"},{"url":"https:\/\/urlp.asm.skype.com\/v1\/url\/content?url=https%3a%2f%2fteamsimages.blob.core.windows.net%2fteamsimage%2fwelcomeimage.jpg","type":"Image","height":"auto"},{"type":"TextBlock","text":"Learn How To:","weight":"bolder"}],"$schema":"http:\/\/adaptivecards.io\/schemas\/adaptive-card.json","selectAction":{"title":"Pin in Tab","card":{"type":"AdaptiveCard","$schema":"http:\/\/adaptivecards.io\/schemas\/adaptive-card.json"},"type":"Action.ShowCard"},"type":"AdaptiveCard","actions":[{"title":"Ask","card":{"body":[{"items":[{"size":"large","text":"🤔Ask a question ","weight":"bolder","type":"TextBlock","spacing":"None"}],"type":"Container"},{"items":[{"size":"medium","spacing":"Large","text":"Create a new discussion by asking a question. Just click on the Ment.io App from the chat bar and press ➕ to add a new question","type":"TextBlock","wrap":true}],"type":"Container"},{"spacing":"Large","type":"Image","url":"https:\/\/urlp.asm.skype.com\/v1\/url\/content?url=https%3a%2f%2fteamsimages.blob.core.windows.net%2fteamsimage%2fexpl_ask_new.jpg","height":"auto"}],"$schema":"http:\/\/adaptivecards.io\/schemas\/adaptive-card.json","type":"AdaptiveCard","version":"1.0"},"type":"Action.ShowCard"},{"title":"Answer","card":{"body":[{"items":[{"size":"large","text":"🙋Answer the question at hand","weight":"bolder","type":"TextBlock","spacing":"None"}],"type":"Container"},{"items":[{"size":"medium","spacing":"Large","text":"Direct the discussion by suggesting one of the possible answers. Start a comment thread and got input on your take.","type":"TextBlock","wrap":true}],"type":"Container"},{"spacing":"Large","type":"Image","url":"https:\/\/urlp.asm.skype.com\/v1\/url\/content?url=https%3a%2f%2fteamsimages.blob.core.windows.net%2fteamsimage%2fexpl_answer.jpg","height":"auto"}],"$schema":"http:\/\/adaptivecards.io\/schemas\/adaptive-card.json","type":"AdaptiveCard","version":"1.0"},"type":"Action.ShowCard"},{"title":"Pin Tab","card":{"body":[{"items":[{"size":"large","text":"📌Pin a discussion in a tab","weight":"bolder","type":"TextBlock","spacing":"None"}],"type":"Container"},{"items":[{"size":"medium","spacing":"Large","text":"Make your discussion last, add it as a tab and jump into the discussion at any time","type":"TextBlock","wrap":true}],"type":"Container"},{"spacing":"Large","type":"Image","url":"https:\/\/urlp.asm.skype.com\/v1\/url\/content?url=https%3a%2f%2fteamsimages.blob.core.windows.net%2fteamsimage%2fexpl_pin.jpg","height":"auto"}],"$schema":"http:\/\/adaptivecards.io\/schemas\/adaptive-card.json","type":"AdaptiveCard","version":"1.0"},"type":"Action.ShowCard"},{"title":"Explore","card":{"body":[{"items":[{"size":"large","text":"🤓Explore discussion insights","weight":"bolder","type":"TextBlock","spacing":"None"}],"type":"Container"},{"items":[{"size":"medium","spacing":"Large","text":"Track the progression of the discussion in the discussion tab, with analytics views for Answers, Discussions, and even Team analytics.","type":"TextBlock","wrap":true}],"type":"Container"},{"spacing":"Large","type":"Image","url":"https:\/\/urlp.asm.skype.com\/v1\/url\/content?url=https%3a%2f%2fteamsimages.blob.core.windows.net%2fteamsimage%2fexpl_analytics.jpg","height":"auto"}],"$schema":"http:\/\/adaptivecards.io\/schemas\/adaptive-card.json","type":"AdaptiveCard","version":"1.0"},"type":"Action.ShowCard"}],"version":"1.0"}

**Comment by nesalang** [comment] 2019-10-31 17:04
@Aditya0603 
You said "seems to be working fine on 1.3" What's 1.3? Our next version will be 1.2.4

**Comment by shalinijoshi19** [comment] 2019-11-04 18:14
@nesalang assigning to you for investigation; @Aditya0603 is this also being tracked for 1.2.* upgrade on the teams side?

**Comment by nesalang** [comment] 2019-11-04 19:29
@shalinijoshi19 ,
@Aditya0603 confirmed that it's no issue on the latest; I will mark it with low priority, and come back later, once teams finishes 1.2.4 integration.

**Comment by shalinijoshi19** [comment] 2019-11-12 23:04
@Aditya0603 / @VikrantSingh01 can you please confirm where/what branch/what iOS package version you are observing this bug on so we know to decide on our next steps?

**Comment by shalinijoshi19** [comment] 2019-11-19 17:29
@VikrantSingh01 ping on this one

**Comment by VikrantSingh01** [comment] 2019-11-21 09:35
@shalinijoshi19 @nesalang  : Aditya is O.O.F

"@Aditya0603 : You said "seems to be working fine on 1.3" What's 1.3? Our next version will be 1.2.4"

Can you check this on AC 1.2.3. I guess Aditya was trying this version.

**Comment by shalinijoshi19** [comment] 2019-11-21 18:33
@nesalang can we test this issue on our outbound 1.2.5 bits see if we can repro it today? Thanks

**Comment by nesalang** [comment] 2019-11-21 19:48
Here are the payload to use for bug bash
samples/v1.0/Elements/
Action.ShowCard.Style.json
Action.ShowCard.json
samples/v1.2/Tests/
NestedShowCard.json

**Comment by nesalang** [comment] 2019-11-22 02:13
it's no repro with 1.2.5 package.

**Closed by nesalang** 2019-11-22 02:13 UTC
Labels: AdaptiveCards v1.2.5, Bug, Msft-TeamsMobile, MsftTeams-Integration, Platform-iOS, Priority-Later
