### ISSUE TITLE
[Designer] Elements with bleed should bleed top and bottom in addition to left and right

### ISSUE THREAD

**Issue by andrewleader** [Microsoft/AdaptiveCards#2704] opened 2019-04-17 18:01 UTC
**Automatically generated task. Any updates to the title and body will be overwritten. Do NOT modify the labels.**

Designer fix of #2702

**Comment by RebeccaAnne** [comment] 2019-04-17 18:05
@dclaux Assiging this auto-generated bug to you to track any changes you may want to make to the designer to make the top/bottom bleed more obvious. If this issue isn't useful to you or is tracked elsewhere feel free to close.

**Comment by dclaux** [comment] 2019-04-19 22:13
At this point the behavior is by design in designer. Closing this.

**Closed by dclaux** 2019-04-19 22:13 UTC
Labels: Area-Renderers, Area-Tooling, Bug, Triage-Approved for Fix, zZ-ImplementationChild
