### ISSUE TITLE
[Adaptive Card-Schema Explorer- Input.Date]: 'Clear' and 'Today' buttons in calendar pop-up is appearing as links in HC mode.

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7300] opened 2022-04-29 22:53 UTC
https://microsoft.visualstudio.com/OS/_workitems/edit/37642918

**Comment by vagpt** [comment] 2023-12-24 08:27
Hi @anna-dingler 

Could you please let us know is there any future plan to fix this issue? As issue is still repro.

![image](https://github.com/microsoft/AdaptiveCards/assets/95913748/60179ecb-0108-40e8-9f03-99c28175d389)

**Comment by anna-dingler** [comment] 2024-01-02 18:07
Closing this issue since it is a duplicate of https://github.com/microsoft/AdaptiveCards/issues/7714

**Closed by anna-dingler** 2024-01-02 18:07 UTC
Labels: Bug, Area-Accessibility, A11ySev3, A11yWCAG, HCL-E+D, Product-AC, HCL-AdaptiveCards-Web, A11yTTValidated, AdaptiveCards_Web, A11yMissing_HCLReviewed, MissingReviewedDeprecated

**Comment by vagpt** [comment] 2024-01-03 05:16
As per the comment above adding A11yTTValidated.
