### ISSUE TITLE
[Android] [Accessibility] Showing card actions horizontally when there're not enough space

### ISSUE THREAD

**Issue by SiarheiKuchukBelitsoft** [microsoft/AdaptiveCards#3919] opened 2020-04-13 13:25 UTC
# Platform
* Teams for Android

# Author or host

Bot sends card to user

# Version of SDK

Node.JS package 
botbuilder version 4.7.2

# Details

Steps to reproduce:
1. Open **Teams** and install **Microsoft Apps Studio**
2. Go to **App Studio**, click **New Card** and paste the JSON below
`{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "wrap": true,
            "text": "Problem with wrapping text of adaptive card actions."
        }
    ],
    "actions": [
        {
            "type": "Action.ShowCard",
            "title": "Button with long text",
            "card": {
                "type": "AdaptiveCard",
                "body": [
                    {
                        "type": "TextBlock",
                        "text": "This is a show card"
                    }
                ],
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
            }
        },
        {
            "type": "Action.ShowCard",
            "title": "Button with long text",
            "card": {
                "type": "AdaptiveCard",
                "body": [
                    {
                        "type": "TextBlock",
                        "text": "This is a show card"
                    }
                ],
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
            }
        },
        {
            "type": "Action.ShowCard",
            "title": "Button with long text",
            "card": {
                "type": "AdaptiveCard",
                "body": [
                    {
                        "type": "TextBlock",
                        "text": "This is a show card"
                    }
                ],
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
            }
        },
        {
            "type": "Action.ShowCard",
            "title": "Button with long text",
            "card": {
                "type": "AdaptiveCard",
                "body": [
                    {
                        "type": "TextBlock",
                        "text": "This is a show card"
                    }
                ],
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
            }
        },
        {
            "type": "Action.ShowCard",
            "title": "Button with long text",
            "card": {
                "type": "AdaptiveCard",
                "body": [
                    {
                        "type": "TextBlock",
                        "text": "This is a show card"
                    }
                ],
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
            }
        },
        {
            "type": "Action.ShowCard",
            "title": "Button with long text",
            "card": {
                "type": "AdaptiveCard",
                "body": [
                    {
                        "type": "TextBlock",
                        "text": "This is a show card"
                    }
                ],
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
            }
        }
    ]
}`
3. Click **Send to me as a Card**
4. Open **Teams** app on **Android** and observe the result
![image](https://user-images.githubusercontent.com/60220228/79123668-53f61980-7da3-11ea-8ce3-2eebf995eac3.png)

**Actual behavior:** 
Action cards are stacked horizontally without scroll bar when there're not enough space to show them all

**Expected behavior:**
Wrap cards and show them vertically if there're not enough space

**Comment by jwoo-msft** [comment] 2020-04-13 23:05
@SiarheiKuchukBelitsoft 
Thanks for sharing this info.
The behavior you desired is supported via HostConfig. The hostconfig is managed by host app, in this case, it's Teams Mobile app. 

The buttons are actually horizontally scrollable although it's missing the scroll bar indicator. @shbhadra, is there a plan for adding a scroll bar for actions?

**Comment by SiarheiKuchukBelitsoft** [comment] 2020-04-14 09:45
@jwoo-msft, The same behavior I observe for Teams for IOS.

**Comment by shalinijoshi19** [comment] 2020-04-17 15:58
@VikrantSingh01 / @jwoo-msft is this something ath needs to be addressed on the Teams end here?

**Comment by jwoo-msft** [comment] 2020-04-22 00:21
@shalinijoshi19 
Could you forward this issue to Teams?

**Comment by Gousia-MSFT** [comment] 2020-04-23 05:36
@SiarheiKuchukBelitsoft Thanks for reporting this. We have raised a bug for this and we are looking into it.

**Comment by SiarheiKuchukBelitsoft** [comment] 2020-04-23 08:37
@Gousia-MSFT, thanks! You're doing a great job with Teams. It serves so well as corporate chat, planner, etc...

**Comment by anbah34** [comment] 2020-05-13 07:10
This is being fixed in the June sprint by Teams Mobile Platform

**Comment by DeeJayTC** [comment] 2020-06-23 09:26
One more mention of the bug here: https://stackoverflow.com/questions/62470617/how-would-it-be-possible-that-adaptive-cards-in-microsoft-teams-for-android-neve

**Comment by DeeJayTC** [comment] 2020-06-23 09:31
#3705 
#3865 

Seem to be similar or related aswell

**Comment by shalinijoshi19** [comment] 2020-11-16 20:40
@anbah34 did the June release wtih the fix go out?  Could you drop a link to the release here for reference at all? 

Also @DeeJayTC / @SiarheiKuchukBelitsoft closing this issue out now; Pls feel free to file a new one or reactivate if you find this is not fixed with the latest Teams release

**Closed by shalinijoshi19** 2020-11-16 20:40 UTC
Labels: Bug, MSTeams-Developer-Support, Msft-TeamsMobile, MsftTeams-Integration, Triage-External

**Comment by anbah34** [comment] 2020-11-23 07:18
@shalinijoshi19 yes this was fixed back in June/ july and can be checked/ validated on the current store build.

Change made - Buttons wrap in a card rather than being shown horizontally

**Comment by Nikitha-MSFT** [comment] 2020-11-25 08:55
Bug is Resolved now, we have tested this at our end, could you please also check and confirm?
The issue is with the Teams client which is fixed now.
