### ISSUE TITLE
[Rendering] Cannot read property 'fallback' of undefined

### ISSUE THREAD

**Issue by estruyf** [microsoft/AdaptiveCards#6286] opened 2021-08-31 13:42 UTC
### Target Platforms

NodeJS

### SDK Version

2.9.0

### Application Name

Externally using Adaptive Cards

### Problem Description

When I try to create the adaptive card from my external app, it always returns an error that it cannot read property `fallback` of undefined. Related to this line: https://github.com/microsoft/AdaptiveCards/blob/main/source/nodejs/adaptivecards/src/card-elements.ts#L7068

My code is the sample code from the site:

```
const ac = new AdaptiveCard();
ac.parse(cardToRender);
```

It happens on the second line.

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "Hello ${name}, will you come to the office tomorrow?"
        }
    ],
    "actions": [
        {
            "type": "Action.Submit",
            "id": "EXP_GOTOOFFICE",
            "title": "Go to office",
            "data": {
              "message": "It is great that you are coming to the office!"
            }
        }
    ]
  }
```

**Comment by RebeccaAnne** [comment] 2021-09-02 20:13
@paulcam206 can you check this out and see what the issue is? Thanks!

**Comment by paulcam206** [comment] 2022-01-27 21:25
@estruyf - can you clarify a bit here? Is this literally taking the supplied card JSON and passing it directly as `cardToRender` above with no other code interaction? What about the template binding directive in the card -- are you passing this after binding to data? And can you confirm that there aren't any `fallback` directives involved in your card?

**Comment by paulcam206** [comment] 2022-02-03 21:31
Close this as we need more information to investigate.

**Closed by paulcam206** 2022-02-03 21:31 UTC
Labels: Bug, Area-Renderers
