### ISSUE TITLE
We need to define a schema for returned input json on a submit action and make sure all renderers are behaving consistently

### ISSUE THREAD

**Issue by RebeccaAnne** [Microsoft/AdaptiveCards#390] opened 2017-06-05 16:34 UTC
The current behavior for the json returned on a submit action is not consistent across renderers.  Here's what we have today:

Date inputs:
HTML renderer uses "2017-06-02" and UWP and .Net use "6/2/2017".  Should probably be ISO-8601 for consistency with min/max fields in Input.Date.

Time inputs:
HTML and UWP use 24 hour format ("17:30") and .Net uses 12 hour format with AM/PM ("5:30 PM")

Multiselect ChoiceSet inputs:
UWP and .Net return the values as a json array of strings ([ "1", "2" ]), HTML returns a single semicolon delimited string ("1;2").  

Number inputs:
UWP and HTML return the value as a string ("1"), .Net returns it as a number (1).  In .Net, if the value in the input is not a number, that input is not included in the returned json.  In HTML it is returned with an empty string.  In UWP no validation is performed and the string in the input is returned as a string regardless of whether or not it is a number.  We should probably define what happens with missing/invalid inputs all up.

**Comment by matthidinger** [comment] 2017-09-22 19:45
Duplicate of #652

**Closed by matthidinger** 2017-09-22 19:45 UTC
Labels: Area-Renderers, Area-Schema, Status-Needs Proposal
