### ISSUE TITLE
[AdaptiveCards- Designer - Card Structure]: Ensures elements with an ARIA role that require parent roles are contained by them (.acd-tree-item[role="treeitem"])

### ISSUE THREAD

**Issue by vagpt** [microsoft/AdaptiveCards#8170] opened 2022-12-20 12:23 UTC
### Target Platforms

Other

### SDK Version

1.5

### Application Name

Adaptive Cards

### Problem Description

**Test Environment:**
URL: [https://adaptivecards.io/](https://nam06.safelinks.protection.outlook.com/?url=https://adaptivecards.io/&data=04%7c01%7cv-ibalam%40microsoft.com%7cbd35d875ec3f4539762308d88f709775%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637417061036711036%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=dUolQbKGi1J8gsoxC2JG5TGoNi41msPfIIjKSIyPGHM%3D&reserved=0)
OS Version: 22H2(OS Build 25247.1000)
Browser Version: Version 110.0.1543.0 (Official build) dev (64-bit)
Tool: Accessibility Insight For Web

**Repro Steps:**
1. Open the URL above with valid credential.
2. Navigate to 'Designer' link and press the enter key to activate it.
3. Navigate to 'Card Structure' button and press the tab key.
4. Run accessibility insight for web and observe the issue.

**Actual Result:**
Elements with an ARIA role that require parent roles are not contained by them.

**Expected Result:**
Ensures elements with an ARIA role that require parent roles are contained by them

**User Experience:**
It will impact the screen reader user if the screen reader does not convey the message to the user.

**Element path:**
li[aria-level="\31 "] > .acd-tree-item[role="treeitem"]

**Snippet:**
<div class="acd-tree-item" role="treeitem" aria-labelledby="880f03f6-3f7d-4488-a7da-bbc13de33f4c" style="display: flex; align-items: center; padding-left: 16px;">

**How to fix:**
Fix any of the following:
Required ARIA parents role not present: group, tree

**MAS Reference:**
https://microsoft.sharepoint.com/:w:/r/sites/accessibility/_layouts/15/Doc.aspx?sourcedoc=%7B9C514377-76E5-4CFE-8300-DA3079D3CDC3%7D&file=MAS%201.3.1%20%E2%80%93%20Info%20and%20Relationships.docx&action=default&mobileredirect=true&share=IQF3Q1Gc5Xb-TIMA2jB5083DAcWOZyaXcx7TtNeRlXM4uHk

"Have feedback to share on Bugs ? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-apoorva%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400998658942%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=l6w0SvVcMSvyGnJ6%2B6uSSgd3braF2dZ7/AdBrqqzIR8%3D&reserved=0) “.

### Screenshots

<img width="960" alt="MAS1 3 1_Ensures elements with an ARIA role that require parent roles are contained by them" src="https://user-images.githubusercontent.com/95913748/208666340-32217582-a517-4851-92a1-05abdc78c596.png">
<img width="960" alt="MAS1 3 1-Ensures elements with an ARIA role that require parent roles are contained by them" src="https://user-images.githubusercontent.com/95913748/208666352-cca8f832-7e75-41bc-8167-7b2b7a4db8b3.png">

### Card JSON

```JSON
NA
```

**Comment by vagpt** [comment] 2023-12-28 08:04
Hi @anna-dingler,

As this issue is still repro, so could you please let us know is there any future plan to fix this issue?

**Comment by anna-dingler** [comment] 2024-01-02 18:46
Closing this issue since it is a duplicate of https://github.com/microsoft/AdaptiveCards/issues/7288

**Closed by anna-dingler** 2024-01-02 18:46 UTC
Labels: Bug, Area-Renderers, Area-Accessibility, A11ySev3, A11yWCAG, HCL-E+D, HCL-AdaptiveCards-Web, A11yTTValidated, AdaptiveCards_Web, A11yMissing_HCLReviewed, MissingReviewedDeprecated

**Comment by vagpt** [comment] 2024-01-03 05:38
Adding A11yTTValidated tag as per the comment above,
