### ISSUE TITLE
[.Net][Rendering] Input.Number initial value is not set

### ISSUE THREAD

**Issue by arman-g** [microsoft/AdaptiveCards#4091] opened 2020-06-03 00:09 UTC
# Platform

* .NET

# Version of SDK

NuGet 1.2.4

# Details

I am not able to set the initial value of an `AdaptiveNumberInput` field. When I set its Value field to a number it will not be shown in the input box for Bot Framework Emulator and WebChat (see the image below). The JSON does have the value but it is not rendered. `AdaptiveTextInput` does not have this problem.
I do remember this issue existed in the Adaptive designer too prior to the latest release 1.2.9. The issue does not exist in the designer anymore but it still exist at least in emulator and WebChat in .Net.

![img-123](https://user-images.githubusercontent.com/22778273/83581451-b0e49500-a4f3-11ea-9fbc-343c3af3e06f.png)

**Comment by shalinijoshi19** [comment] 2020-06-04 20:13
@paulcam206 is this a duplicate of #3829 that you've been looking into?

**Comment by arman-g** [comment] 2020-07-27 04:12
Any updates on this?

**Comment by arman-g** [comment] 2020-12-18 02:56
Any updates?

**Comment by arman-g** [comment] 2021-02-05 20:42
Ok, are you guys ever going to fix this simple bug? I can't believe it is taking too long even to knowledge this bug. Just unbelievable, why do you even have issues section if you are going to ignore bug reports?

**Comment by paulcam206** [comment] 2021-02-08 17:09
closing as dupe of #3991

**Closed by paulcam206** 2021-02-08 17:09 UTC
Labels: Area-Inputs, Bug, MsftBot-Integration
