### ISSUE TITLE
[Bug]SelectAction escapes to parent element

### ISSUE THREAD

**Issue by Kartik1607** [Microsoft/AdaptiveCards#1343] opened 2018-04-07 14:10 UTC
When we add a select action to an item in column, the action escapes to the parent Column element. 

Example : To produce below image I have used JSON schema as below
![App Store Banner Image](https://imgur.com/BmMtpdu.png)
```json
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
		{
            "type":"ColumnSet",
            "columns": [
            {
                "type": "Column",
                "items": [
                {
                    "type": "Image",
                    "size": "medium",
                    "url": "https://imgur.com/lKusx7W.png",
                    "selectAction":{
                        "type": "Action.OpenUrl",
                        "url": "https://www.apple.com"
                    }
                }
                ]
            },
            {
                "type": "Column",
                "items": [
                {
                    "type": "Image",
                    "size": "medium",
                    "url": "https://imgur.com/sau4J4M.png",
                    "selectAction":{
                        "type": "Action.OpenUrl",
                        "url": "https://www.google.com"
                    }
                }
                ]
            }
          ]
        }
	]
}
```

**Expected** : The url should open when I click on image and **should not open when I click on empty space between image (column)** since the **action is applied to Image and not Column!**.

**Bug** :  If we try to click the empty space between image, then also the selectAction is triggered.

![DOM](https://imgur.com/D3wmiZz.png)
I have seen that the `.ac-selectable` class is applied to parent div and not the image. This class is generally responsible for  changing mouse cursor to pointer and changing the background color. **(Both of which are currently broken).**

**Workaround for mouse hover and background color** : Add the following class to webchat. (This should be actually done in adaptivecard, but we are currently not using custom build of adaptive card)

```CSS
    .ac-selectable img:hover {
            cursor: pointer;
            background: #007799
        }
```

We still are having issue that if a user clicks outside image, in the column, then the action is run. 

**AC Version :** 1.0
**Webchat Version :** 0.12

**Comment by dclaux** [comment] 2018-04-07 17:29
@Kartik1607 thanks for reporting this. A couple things:
- For an Image with a selectAction, it is expected and as designed that there is no hover background color; that is how the .ac-selectable class is defined for an Image. The hover background is only for containers with a selectAction (e.g. Container or Column)
- The reason there is no hover background for images with a selectAction is that it would be covered by the image anyway
- It looks like the .ac-selectable class should applied to the ```<img>``` itself rather than the parent ```<div>```. That would solve the problem on the selectAction applying outside the visual boundaries of the image. This is an easy fix.

Make sense?

**Comment by Kartik1607** [comment] 2018-04-08 04:25
It makes sense to have no hover background color for image only when image takes up full size. What if image is not a square / rectangle. We do need to provide visual feedback there as well. 

Take this example image, I am currently using ![Example image](https://imgur.com/KzOh6lo.png)

As you can see, **adding the background color property helps in case of image as well.** Adding the background property may be useless most of the time in case of images, but there is no harm if it can solve some edge cases as above some of the time.

Also one of the most important visual feedback a user expects is that **his mouse cursor should change to pointer** when the element is clickable.

The ``.ac-selectable`` class is broken in this regard as well. If you try to hover on image or any select-able element, there is no change is mouse pointer.

**Comment by dclaux** [comment] 2018-04-08 16:53
@Kartik1607 good point about images with transparent background (e.g. non square/rectangular images.) I sure can't hurt to use a background color on hover anyway, so we should add that.

About the cursor I am not sure I am following. The one thing that does happen currently is the cursor does change on hover for images. Is that not what you are seeing?

**Comment by dclaux** [comment] 2018-04-08 17:48
Ok, I have coded the fix, you can check [this PR](https://github.com/Microsoft/AdaptiveCards/pull/1344). Below is the end result.

No hover:
![image](https://user-images.githubusercontent.com/1334689/38470593-09c852d8-3b1a-11e8-841a-c936ec0c50cc.png)
Hover:
![image](https://user-images.githubusercontent.com/1334689/38470580-d1b4287c-3b19-11e8-929b-c001d1c78945.png)

Does that work for you?

**Comment by dclaux** [comment] 2018-04-11 17:18
This is now fixed as per the above.

**Closed by dclaux** 2018-04-11 17:18 UTC
