### ISSUE TITLE
[Teams][Rendering] Cards not rendered correctly on teams channel

### ISSUE THREAD

**Issue by schemburkar** [microsoft/AdaptiveCards#3685] opened 2019-12-17 15:52 UTC
### Platform
Microsoft Teams

### Description

I'm sending a adaptive card to multiple platforms including teams and web chat. The card will have multiple options based on user input (up to 5). These are not suggested actions but Submit Actions via cards
Except for teams, the adaptive card is rendered incorrectly. 
I can reproduce the issue on the designer (https://adaptivecards.io/designer/) as well.

### JSON

```
{
    "type": "AdaptiveCard",
    "body": [
        {
            "color": "Accent",
            "text": "Please choose a feature.",
            "type": "TextBlock"
        },
        {
            "text": "Please select from one of the below options",
            "wrap": true,
            "type": "TextBlock"
        },
        {
            "items": [
                {
                    "columns": [
                        {
                            "items": [
                                {
                                    "actions": [
                                        {
                                            "title": "GitHub Test 1",
                                            "type": "Action.Submit"
                                        }
                                    ],
                                    "type": "ActionSet"
                                }
                            ],
                            "type": "Column",
                            "width": "stretch"
                        },
                        {
                            "items": [
                                {
                                    "actions": [
                                        {
                                            "title": "GitHub Test Action 2",
                                            "type": "Action.Submit"
                                        }
                                    ],
                                    "type": "ActionSet"
                                }
                            ],
                            "type": "Column",
                            "width": "stretch"
                        },
                        {
                            "items": [
                                {
                                    "actions": [
                                        {
                                            "wrap": true,
                                            "title": "GitHub Test Action 3",
                                            "type": "Action.Submit"
                                        }
                                    ],
                                    "type": "ActionSet"
                                }
                            ],
                            "type": "Column",
                            "width": "stretch"
                        }
                    ],
                    "type": "ColumnSet"
                },
                {
                    "columns": [
                        {
                            "items": [
                                {
                                    "actions": [
                                        {
                                            "title": "GitHub Test 4",
                                            "type": "Action.Submit"
                                        }
                                    ],
                                    "type": "ActionSet"
                                }
                            ],
                            "type": "Column",
                            "width": "stretch"
                        },
                        {
                            "items": [
                                {
                                    "actions": [
                                        {
                                            "title": "GitHub Test 5",
                                            "type": "Action.Submit"
                                        }
                                    ],
                                    "type": "ActionSet"
                                }
                            ],
                            "type": "Column",
                            "width": "stretch"
                        }
                    ],
                    "type": "ColumnSet"
                }
            ],
            "type": "Container"
        }
    ],
    "version": "1.2",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}
```
### Rendering
Web Chat Rendering (Designer) ✅
![image](https://user-images.githubusercontent.com/3159347/71010824-653f5a00-2112-11ea-96f1-e577d4b78b51.png)

Teams Rendering (Designer)❌
![image](https://user-images.githubusercontent.com/3159347/71010863-78eac080-2112-11ea-8d0f-ceaa03c09613.png)

Teams Rendering (Actual)❌
![image](https://user-images.githubusercontent.com/3159347/71011045-c2d3a680-2112-11ea-8114-88fe5fb088c9.png)

### Expected Result
Rendering on teams should be same as other channels like web chat.

Please let me know if any more information is needed

**Comment by shalinijoshi19** [comment] 2020-01-08 21:45
Thanks for reporting this@schemburkar.  I dont see this repro'ing on https://adaptivecards.io/designer
![image](https://user-images.githubusercontent.com/20822397/72018734-0a82b500-321d-11ea-9341-f3d2cdcf2fda.png)

Can you please confirm if you are still seeing this? If so, @ckkashyap , @siduppal can you please help triage as this doesn't seem to be an AdaptiveCards issue on the onset.. 

Thanks!

**Comment by siduppal** [comment] 2020-01-08 23:57
@Susan Shen<mailto:Susan.Shen@microsoft.com> can you take a look?


________________________________

**Comment by schemburkar** [comment] 2020-01-09 02:24
@Shalini-MSFT Thanks for investigating. I think you overlooked the fact that the rendering does not work on **Teams** channel, whereas your screenshot is for Web Chat.

I tested again on both live teams app as well as on the designer with the teams channel.

Live Microsoft Teams app ❌
![image](https://user-images.githubusercontent.com/3159347/72032145-8ed44700-32b4-11ea-9fb2-2964b076d6e4.png)

adaptivecards.io/designer - Host App: Teams ❌
![image](https://user-images.githubusercontent.com/3159347/72032254-d2c74c00-32b4-11ea-9149-4e0cd7ee836e.png)

To answer your question

> Can you please confirm if you are still seeing this

YES

**Comment by susanshen96** [comment] 2020-01-09 19:26
@schemburkar, @shalinijoshi19  - Took a look, and it does seem to be an issue on the Teams client. There was a regression in how the button text is rendered, but the buttons in column seems to be a newer rendering issue that wasn't considered before. Will have a fix out, which should be available externally in around a month's time.

**Comment by shalinijoshi19** [comment] 2020-01-24 16:58
@susanshen96 assigning to you for tracking.

**Closed** 2021-11-29 21:48 UTC
Labels: Bug, Partner-MsftTeams, Resolution-External, MSTeams-Developer-Support
