### ISSUE TITLE
Add "name" property to the objects in the AdaptiveCard for easy deserialization

### ISSUE THREAD

**Issue by vxnsbir1ugsp** [Microsoft/AdaptiveCards#526] opened 2017-08-02 08:49 UTC
When using AdaptiveCard you either have the choice to
1. describe the card by code (which is absurd, if you have to describe columns and columnSets), or
2. to create it using the Visualizer in adaptivecards.io and in the text property of every object to create a custom convention and read the Json from your code, then string.replace the text property with the actual data

Instead you can add "name" prop to every object and deserialize it directly into object, then add values to the properties

**Comment by dclaux** [comment] 2017-08-02 16:24
Hi @vxnsbir1ugsp it seems you want to do some sort of "late binding", e.g. inject data into a template. If so, I think the string.replace approach you mention above is really not that bad.

That being said, we are adding an Id property to elements (and actions) and the renderer OM will make it possible to get to elements by Id. This work is tracked here: https://github.com/Microsoft/AdaptiveCards/issues/493

In the end, you will be able to write code like this (example using the TypeScript renderer):
```
var deserializedCard = JSON.parse("card payload as string");

var myCard = new AdaptiveCard();
myCard.parse(deserializedCard);

var element = myCard.getElementById("abc");
(<TextBlock>element).text = "whatever";

// Note that a card must always be fully re-rendered when element properties are changed
var renderedCard = myCard.render();
```

Is that what you are looking for?

**Comment by vxnsbir1ugsp** [comment] 2017-08-02 16:30
Yes, thats what I mean, exactly!

**Comment by dclaux** [comment] 2017-08-02 16:32
Great! Can I ask which renderer(s) you are using or are planning to use?

**Comment by vxnsbir1ugsp** [comment] 2017-08-02 16:33
As many as possible, starting with Skype and the not-so-sure-its-supported-now Cortana canvas

**Comment by dclaux** [comment] 2017-08-03 18:11
Duplicate of https://github.com/Microsoft/AdaptiveCards/issues/493

**Closed by dclaux** 2017-08-03 18:11 UTC
Labels: Duplicate

**Comment by artemious7** [comment] 2018-12-14 21:13
I can't find this extension method (that @dclaux proposed) in C#. Am I missing something?

    var element = myCard.GetElementById("abc");
