### ISSUE TITLE
[Input.Date in Teams] Customize Input.Date current date rendering in Teams 

### ISSUE THREAD

**Issue by GeorgianaMihaela** [microsoft/AdaptiveCards#3604] opened 2019-11-13 10:04 UTC
**What platform is your feature request related to? (Delete other platforms).**

* .NET Core 
* JS 
* Adaptive cards in MS Teams inside Chat bot 

**Is your feature request related to a problem? Please describe.**
I use a simple Input.Date in adaptive card. 
In Teams, the date is rendered with white, if the default Teams theme is chosen: 

![image](https://user-images.githubusercontent.com/13887936/68749714-580ce800-0607-11ea-8d84-ff50cd6fa667.png)

If I change the Teams theme to dark, the highlight for the current date is still not clear (I can barely see the date):

![image](https://user-images.githubusercontent.com/13887936/68749851-97d3cf80-0607-11ea-9e5b-37addf70d390.png)

For Teams high contrast theme, the  highlight is bit better:
![image](https://user-images.githubusercontent.com/13887936/68750092-044ece80-0608-11ea-9d98-bf7e56347825.png)

But this theme is not suitable for me, as is tiring for my eyes. 

**Describe the solution you'd like**
I would like to have:
a) either a clear distinctive highlight for the current date in the Input.Date on adaptive card on Teams (any colour for the highlight would work which contrasts with the background: white on white is not an option). 

b) either the possibility to customize the highlight colour for the current date within the adaptive card. 
Probably a property in the JSON for the adaptive card which could allow the customisation of the current date highlight. 

Note that in the webchat the current date is rendered in black 

![image](https://user-images.githubusercontent.com/13887936/68752859-ab356980-060c-11ea-8816-9bdf9a6f72a7.png)

This white rendering in Teams makes me (and other users) believe the current date selection is disabled. This is not intuitive and is confusing. 

**Describe alternatives you've considered**
Use the high contrast Teams theme, but I find it overwhelming for my eyes. 

**Additional context**
The simple JSON I use is this one taken from MS samples 
https://adaptivecards.io/explorer/Input.Date.html 

Thank you for your time and for taking into account users feedback.

**Comment by dclaux** [comment] 2019-11-18 17:06
This is a Teams issue. I am checking with them to determine what's the best way to report it, and we update this issue once I know.

**Comment by dclaux** [comment] 2019-11-18 19:19
Teams is aware of this bug and working on a fix. I am still waiting on official word as to what the appropriate channel is to report Teams bugs.

**Comment by susanshen96** [comment] 2019-11-26 19:44
@GeorgianaMihaela - a fix has been checked in. It might be 1-2 weeks before the change manifests in the public version of Teams, but the current date on default/dark theme will look like this, respectively: 
![image](https://user-images.githubusercontent.com/10697383/69666281-db373080-1040-11ea-91a1-f06fff14c743.png)
![image](https://user-images.githubusercontent.com/10697383/69666402-0c176580-1041-11ea-8dbc-985563198619.png)

**Comment by geo-msft** [comment] 2019-12-16 14:15
Thank you for your support. If the issue is solved, we can close this issue.

**Closed** 2020-07-27 21:59 UTC
Labels: Request, no-recent-activity
