### ISSUE TITLE
[Designer] Schema validation warnings (image size and nested cards)

### ISSUE THREAD

**Issue by joschi27** [microsoft/AdaptiveCards#6143] opened 2021-07-27 10:21 UTC
# Problem Description

Schema validator over at https://adaptivecards.io/designer suggests a warning when nested cards are used. It wants to have the version key. I'm still not sure wether to include it. (in the nested cards example, they are not present.)

Also, in the card below, the schema displays a warning that the size key expects an object, which is not true. (This only occurs when an Image is the first element of the body)

--> It does not matter if the size key is Uppercase or not.

# Screenshot

Card version:
![image](https://user-images.githubusercontent.com/16883655/127138290-b991e271-2fcb-45ac-8dae-9babe8d77d54.png)

Image size:
![image](https://user-images.githubusercontent.com/16883655/127138378-28aeed37-9e1e-49dc-b45c-911e2afd726d.png)

# Card JSON

`{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.3",
    "body": [
        {
            "type": "Image",
            "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Microsoft_Office_Teams_%282018%E2%80%93present%29.svg/258px-Microsoft_Office_Teams_%282018%E2%80%93present%29.svg.png",
            "size": "medium"
        }
    ],
    "actions": [
        {
            "type": "Action.ShowCard",
            "title": "Action.ShowCard",
            "card": {
                "type": "AdaptiveCard",
                "body": [
                    {
                        "type": "Image",
                        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Microsoft_Office_Teams_%282018%E2%80%93present%29.svg/258px-Microsoft_Office_Teams_%282018%E2%80%93present%29.svg.png",
                        "size": "Medium"
                    }
                ]
            }
        }
    ]
}`

Thanks!

**Comment by RebeccaAnne** [comment] 2021-08-05 20:46
These are caused by validating against the schema. The version property is required for parent cards but not for sub cards, and our schema doesn't express this.

The size issue looks most likely to be a bug in the schema.

**Comment by paulcam206** [comment] 2022-01-27 21:49
Addressing this issue is not currently on our roadmap, so closing. Please feel free to continue the conversation in this issue for future consideration.

**Closed by paulcam206** 2022-01-27 21:49 UTC
Labels: Area-Designer
