### ISSUE TITLE
We need samples that build against public packages

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#3634] opened 2019-11-21 21:47 UTC
We currently have test apps that build against source, which we obviously need to test changes. However, we don't have a convenient way to test against public or near-public sources (e.g. a .nupkg or the currently-published nuget package). We should invest here to improve our coverage and give us a platform for diagnosing issues for customers.

**Comment by jonmill** [comment] 2021-11-15 21:28
Dupe of #6660

**Closed by jonmill** 2021-11-15 21:28 UTC
Labels: Bug, Triage-Approved for Fix, no-recent-activity
