### ISSUE TITLE
Adaptive Card -unable to hear voice in iPhone Safari/chrome browser, media player is not supporting

### ISSUE THREAD

**Issue by amoyalan20** [microsoft/AdaptiveCards#6894] opened 2022-01-18 11:13 UTC
### Target Platforms

iOS

### SDK Version

V4

### Application Name

Chatbot Web

### Problem Description

•	**Issue Description**: Unable to hear the audio file(WAV & MP3) playback inside Adaptive card of chatbot. Audio control bar shows up, user clicks on play button, the audio plays but no sound is heard. Issue occurs only in IOS Devices. Android mobiles, Desktop, Laptop browsers working fine. 
•	**Findings** : Volume Control are not showing in the media player. Same audio URL is perfectly working in iOS browsers(safari, chrome) when tried as open URL with default browser player.
•	**Device with Issue** : IOS Mobile devices (Iphone X, Iphone 11plus tested)
•	**Browser** : Safari/Chrome browsers 
•	**Chatbot Details**: Bot framework V4 Used
•	**Channel with issue** : Web

### Screenshots

![image](https://user-images.githubusercontent.com/73281779/149926339-6d88bd18-d3fb-4a2d-9200-45c53313b045.png)

### Card JSON

```JSON
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "Media",
            "sources": [
                {
                    "mimeType": "audio/mpeg",
                    "url": "https://.......wav"
                }
            ]
        }
    ]
}
```

### Sample Code Language

C# botframework

### Sample Code

var pronunciationPlayBack = new AdaptiveMedia()
{
Type = "Media",
Sources = new List()
{
new AdaptiveMediaSource()
{
Url = "https://.......wav",
MimeType = "audio/mpeg"
}

                            }

                        };

**Comment by amoyalan20** [comment] 2022-01-20 10:21
is there any updates?

**Comment by paulcam206** [comment] 2022-01-20 21:14
duplicate of #6788

**Closed by paulcam206** 2022-01-20 21:14 UTC
Labels: Bug, Area-Renderers, Triage-Needed
