### ISSUE TITLE
[Visualizer] Markdown lists are not rendered

### ISSUE THREAD

**Issue by almedina-ms** [Microsoft/AdaptiveCards#1910] opened 2018-09-13 23:12 UTC
# Platform

* JavaScript

# Author or host

Developer

# Version of SDK

master

# Issue

The visualizer doesn't render the lists as shown in the image below. All the other renderers are actually able to render the lists (even when the behavior is not 100% consistent between them all)

![image](https://user-images.githubusercontent.com/35784165/45520739-9f7fb600-b76f-11e8-9897-b902f36df18e.png)

**Comment by dclaux** [comment] 2018-09-13 23:17
The problem is that the visualizer uses CSS styles that interfere with bulleted lists. The offending style is declared in conceptual.css and sets the padding for bulleted lists to 0, which has the effect of removing the bullets:
![image](https://user-images.githubusercontent.com/1334689/45520918-84617600-b770-11e8-93c8-9d18d0705712.png)

**Comment by almedina-ms** [comment] 2018-09-13 23:18
So, should we close this one?

**Comment by dclaux** [comment] 2018-09-13 23:19
No, it should be fixed. @matthidinger?

**Comment by matthidinger** [comment] 2018-09-13 23:35
Indeed this is fixed on the upcoming build of the site. Feel free to close this if ya like

**Comment by khouzam** [comment] 2018-09-17 17:28
Fixed in CI. Will show up on next deployment.

**Closed by khouzam** 2018-09-17 17:28 UTC
