### ISSUE TITLE
[UWP][Textblock] Long string doesn't wrap

### ISSUE THREAD

**Issue by Joshua-David** [microsoft/AdaptiveCards#4251] opened 2020-06-29 13:56 UTC
# Platform
UWP

What platform is your issue or question related to? (Delete other platforms).
* UWP

# Author or host
Host 

Are you an author (like sending something to Outlook), or a host that is rendering your own cards? If host, please specify the corresponding host (app) name.
Cortana on Windows

What version are you using? Ex: NuGet 1.0.2, or latest main, etc...
1.2.7

# Details
We have long strings in an AC textblock, when we specify for them to wrap they don't wrap unless the string has spaces
![image](https://user-images.githubusercontent.com/8453924/86014535-5ec26100-ba18-11ea-88fb-789f64a73dd0.png)

We are also seeing a strange wrap if there is a + character- this causes the wrap to happen wherever the + character is in the string which could be early on:
![image](https://user-images.githubusercontent.com/8453924/86014660-8a454b80-ba18-11ea-8bc7-c9528952f35f.png)

This is not an issue for the web renderer, only seems to happen on UWP.

Here is the JSON for this issue:
```json
{
  "type": "AdaptiveCard",
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.2",
  "body": [
    {
      "type": "TextBlock",
      "text": "ThisIsAReallyLongTextBlockWithNoSpaces",
      "size": "ExtraLarge",
      "wrap": true,
      "maxLines": 2
    }
  ]
}
```

**Comment by shalinijoshi19** [comment] 2020-06-30 20:43
interesting, @paulcam206 / @RebeccaAnne you guys seen this one before? Thoughts?

**Comment by paulcam206** [comment] 2020-06-30 21:04
> interesting, @paulcam206 / @RebeccaAnne you guys seen this one before? Thoughts?

We're using the standard UWP XAML TextBlock control and setting the text trimming and text wrapping properties like so:
https://github.com/microsoft/AdaptiveCards/blob/314146e0e162295b292dbdfe94867592e846620b/source/uwp/Renderer/lib/TextHelpers.cpp#L153-L159

AFAIK we're not supplying any special word breakers or anything, so unexpected behaviors are likely present in the controls themselves. It's possible that there are extra properties we _should_ be setting, but I don't know off the top of my head. @RebeccaAnne might have thoughts/context here :)

**Comment by shalinijoshi19** [comment] 2020-08-11 15:40
@RebeccaAnne can you help take a look at this one for thoughts?

**Comment by RebeccaAnne** [comment] 2020-09-08 22:01
Interestingly, the non-wrapping doesn't repro for me in main in the UWP visualizer (the + behavior does repro):
![image](https://user-images.githubusercontent.com/9091833/92531578-6a35c380-f1e3-11ea-88a2-6130f468ec6e.png)

**Comment by RebeccaAnne** [comment] 2020-09-09 22:14
Confirmed that the main wrapping bug repros in 1.2.7 but not 2.1.0. Looks like this got fixed somewhere along the way. Investigating the + behavior.

**Comment by RebeccaAnne** [comment] 2020-09-09 22:27
As Paul mentions above, breaking on the + is the default behavior of the TextBlock control. It doesn't look like that's something that's configurable.

**Comment by paulcam206** [comment] 2020-09-09 22:41
could this be part of the problem?

https://github.com/microsoft/AdaptiveCards/blob/be54ffa92a4722e4062dd7b455fa6df74c330c8e/source/uwp/Renderer/lib/XamlHelpers.h#L263-L266

**Comment by RebeccaAnne** [comment] 2020-09-10 16:13
> could this be part of the problem?
> 
> https://github.com/microsoft/AdaptiveCards/blob/be54ffa92a4722e4062dd7b455fa6df74c330c8e/source/uwp/Renderer/lib/XamlHelpers.h#L263-L266

That function is only currently called for toggles and choice sets, but yes, that setting would produce the first behavior of not wrapping long words. I suspect we used to set that for TextBlocks and now don't, which would explain why it repros in 1.2.7 but not 2.1. That said, that setting doesn't affect whether or not we break on +.

**Comment by shalinijoshi19** [comment] 2020-09-21 19:49
@RebeccaAnne what are our next steps on this one?

**Comment by RebeccaAnne** [comment] 2020-09-22 20:16
The main issue where long words were not wrapping is fixed in the latest version. The breaking on + is the behavior of the UWP TextBlock control, and is not configurable. Although this may not be consistent with Adaptive Cards behavior on other platforms (JavaScript doesn’t do this, for example), it is consistent with text block behavior in UWP generally. Closing this issue.

**Closed by RebeccaAnne** 2020-09-22 20:16 UTC
Labels: AdaptiveCards v20.09, Bug, MsftCortana-Integration, Platform-UWP
