### ISSUE TITLE
[Rendering] iOS App crash

### ISSUE THREAD

**Issue by yanweida99** [microsoft/AdaptiveCards#7059] opened 2022-02-22 08:46 UTC
### Target Platforms

iOS

### SDK Version

AdaptiveCards Schema 1.5 (7704807)

### Application Name

Our app

### Problem Description

The app crash using AdaptiveCards SDK.

```
Code Type:             X86-64 (Native)
Parent Process:        launchd_sim [7440]
Responsible:           SimulatorTrampoline [686]
User ID:               501

Date/Time:             2022-02-19 01:11:56.222 +0800
OS Version:            macOS 11.4 (20F71)
Report Version:        12
Bridge OS Version:     5.4 (18P4663)
Anonymous UUID:        056AE47C-4FAC-516C-83B0-FFC2AFA62645


Time Awake Since Boot: 25000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000008
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [7752]

VM Regions Near 0x8:
--> 
    __TEXT                      10e16c000-114368000    [ 98.0M] r-x/r-x SM=COW  /Users/*/Library/Developer/CoreSimulator/Devices/097D0973-80E6-4AFB-9E9E-D2E27508B3C9/data/Containers/Bundle/Application/AF3D9025-A5B4-471B-B7C9-AEE6863972A0/Our.app/Our

Application Specific Information:
dyld4 config: DYLD_ROOT_PATH=/Applications/Xcode13.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot DYLD_LIBRARY_PATH=/Users/rcadmin/Library/Developer/Xcode/DerivedData/WebDriverAgent-bpjyxktypmiyugaudwkgvshhpehv/Build/Products/Debug-iphonesimulator DYLD_FRAMEWORK_PATH=/Users/rcadmin/Library/Developer/Xcode/DerivedData/WebDriverAgent-bpjyxktypmiyugaudwkgvshhpehv/Build/Products/Debug-iphonesimulator 
CoreSimulator 776.3 - Device: iPhone 11 (********-****-****-****-************) - Runtime: iOS 15.0 (19A339) - DeviceType: iPhone 11

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.apple.CoreFoundation      	0x00007fff2046a6aa -[__NSDictionaryM objectForKey:] + 133
1   MSFT.AdaptiveCards            	0x000000012463fd15 -[ACRTextBlockRenderer render:rootView:inputs:baseCardElement:hostConfig:] + 713
2   MSFT.AdaptiveCards            	0x00000001245df72a +[ACRRenderer render:rootView:inputs:withCardElems:andHostConfig:] + 728
3   MSFT.AdaptiveCards            	0x00000001245ded70 +[ACRRenderer renderWithAdaptiveCards:inputs:context:containingView:hostconfig:] + 1012
4   MSFT.AdaptiveCards            	0x0000000124632bd5 -[ACRView render] + 316
5   MSFT.AdaptiveCards            	0x00000001246329c6 -[ACRView init:hostconfig:widthConstraint:delegate:] + 725
6   MSFT.AdaptiveCards            	0x00000001245de6b4 +[ACRRenderer render:config:widthConstraint:delegate:] + 141
7   com.our.mobile           	0x000000010e9053d7 ItemAdaptiveCardView.renderView() + 583
8   com.our.mobile            	0x000000010e905124 ItemAdaptiveCardView.configAdaptiveCard() + 692
9   com.our.mobile            	0x000000010e904caa ItemAdaptiveCardView.configureUI() + 3226
10  com.our.mobile            	0x000000010e5385d8 specialized ItemBaseView.init(item:actionDelegate:) + 360
11  com.our.mobile            	0x000000010e9097e8 specialized ItemAdaptiveCardView.init(item:actionDelegate:) + 408
12  com.our.mobile            	0x000000010e9090a0 ItemAdaptiveCardView.__allocating_init(item:actionDelegate:) + 48
13  com.our.mobile            	0x000000010e96bb60 ChatContentView.createItemViews(items:) + 1200
14  com.our.mobile            	0x000000010e99d291 specialized ChatCell.setItems(items:height:) + 177
15  com.our.mobile            	0x000000010e43b9e0 ChatTableView.configCell(_:indexPath:) + 1216
16  com.our.mobile            	0x000000010e43da89 @objc ChatTableView.tableView(_:cellForRowAt:) + 297
17  com.apple.UIKitCore           	0x00007fff2526568a -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 1580
18  com.apple.UIKitCore           	0x00007fff2522ae84 -[UITableView _updateVisibleCellsForRanges:createIfNecessary:] + 787
19  com.apple.UIKitCore           	0x00007fff2522b72e -[UITableView _updateVisibleCellsNow:] + 1716
20  com.apple.UIKitCore           	0x00007fff2524d273 -[UITableView layoutSubviews] + 217
21  com.apple.UIKitCore           	0x00007fff255bcaad -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2962
22  com.apple.QuartzCore          	0x00007fff2893c2b6 CA::Layer::layout_if_needed(CA::Transaction*) + 548
23  com.apple.QuartzCore          	0x00007fff289474f1 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 65
24  com.apple.QuartzCore          	0x00007fff288830ca CA::Context::commit_transaction(CA::Transaction*, double, double*) + 652
25  com.apple.QuartzCore          	0x00007fff288bac47 CA::Transaction::commit() + 699
26  com.apple.QuartzCore          	0x00007fff288bbfc8 CA::Transaction::flush_as_runloop_observer(bool) + 60
27  com.apple.CoreFoundation      	0x00007fff20368c77 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
28  com.apple.CoreFoundation      	0x00007fff2036349c __CFRunLoopDoObservers + 541
29  com.apple.CoreFoundation      	0x00007fff20363a4c __CFRunLoopRun + 1126
30  com.apple.CoreFoundation      	0x00007fff20363103 CFRunLoopRunSpecific + 567
31  com.apple.GraphicsServices    	0x00007fff2c851cd3 GSEventRunModal + 139
32  com.apple.UIKitCore           	0x00007fff24ffbe63 -[UIApplication _run] + 928
33  com.apple.UIKitCore           	0x00007fff25000a53 UIApplicationMain + 101
34  com.our.mobile            	0x000000010e1740cf main + 255
35  dyld_sim                      	0x00000001241a1e1e start_sim + 10
36  ???                           	0x0000000000000001 0 + 1
37  ???                           	0x0000000000000003 0 + 3`
```

### Card JSON

```JSON
{
            "type": "AdaptiveCard",
            "version": "1.3",
            "fallbackText": "",
            "body": [
                {
                    "type": "TextBlock",
                    "size": "Medium",
                    "weight": "Bolder",
                    "text": "Publish Adaptive Card Schema"
                }
            ]
        }
```

**Comment by jwoo-msft** [comment] 2022-02-24 10:46
@yanweida99,

are you using custom text renderer?

I can't reproduce this issue this issue.

**Comment by yanweida99** [comment] 2022-02-25 07:35
> @yanweida99,
> 
> are you using custom text renderer?
> 
> I can't reproduce this issue this issue.

We are not using custom text renderer. And the crash only appeared once. Is there any way to provide you with more debugging information? We will continue to observe this issue.

**Comment by jwoo-msft** [comment] 2022-03-03 19:57
@yanweida99 

thanks for reporting. I will close this issue for now. If this is reproduced again, let me know.

**Closed by jwoo-msft** 2022-03-03 19:57 UTC
Labels: Bug, Area-Renderers
