### ISSUE TITLE
{Freeway-Bug}[Adaptive Cards- Home- Stock Update]: Keyboard focus moving to non-interactive text of the card.

### ISSUE THREAD

**Issue by Bhaskar301101** [microsoft/AdaptiveCards#8449] opened 2023-04-06 13:27 UTC
### Target Platforms

Android

### SDK Version

2023.03.31.1

### Application Name

Adaptive Card

### Problem Description

**Test Environment**
Device: S21+ 5G
Screen Reader: Talkback
AdaptiveCard Android App version: 2023.03.31.1

**Repro Steps:**

1. Open Adaptive Cards Visualizer Application.
2. Home Page will opened.
3. Now Navigate to 'Sample card' button and select it.
4. Now navigate to "choose sample" expands/collapse control and select "Inputs" list item.
5. Now Navigate to Visual tab and select it.
6. Now navigate to Stock update card using swipe gesture and navigate to card using tab key navigation using keyboard and observe the issue.

**Actual Result:**
Keyboard focus moving to non-interactive text of the card.

**Expected Result:**
Keyboard focus shouldn't move to non-interactive text of the card.

**User Experience:**
User who rely keyboard navigation will be impacted if the keyboard focus move to the non-interactive text of the page and the experience can create a different interaction pattern, and/or unintended content relationships for assistive technology users. On rare occasions, there is a logical reason the focus order is different from the reading order, but the meaning of the content and interactions must remain the same.

**WCAG Reference:**
https://www.w3.org/WAI/WCAG21/Understanding/focus-order

"Have feedback to share on Bugs ? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-apoorva%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400998658942%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=l6w0SvVcMSvyGnJ6%2B6uSSgd3braF2dZ7/AdBrqqzIR8%3D&reserved=0)

### Screenshots

https://user-images.githubusercontent.com/89897257/230392285-88846098-8094-43f2-bc75-f49a577f1c87.mp4

### Card JSON

```JSON
NA
```

**Comment by jwoo-msft** [comment] 2023-06-08 22:54
duplicate of #7959

**Closed by jwoo-msft** 2023-06-08 22:54 UTC
Labels: Bug, Area-Renderers, Platform-Android, Resolution-Duplicate, Area-Accessibility, A11ySev2, A11yWCAG, HCL-E+D, Product-AC, HCL-AdaptiveCards-Android, HCL-AdaptiveCards-Mobile

**Comment by vagpt** [comment] 2023-07-10 10:54
Adding A11yTTValidated tag as per the above comment.
