### ISSUE TITLE
{Freeway-Bug}[Adaptive Cards> Save File]: Keyboard focus does not retain back to the 'Save file' button on pressing esc key to close the dialog.

### ISSUE THREAD

**Issue by vaishali1397** [microsoft/AdaptiveCards#7788] opened 2022-08-30 07:47 UTC
### Target Platforms

UWP

### SDK Version

3.0.2206.2001

### Application Name

Adaptive Cards

### Problem Description

**Test Environment:**
OS version: 22H2 (Build 25182.1010)
Application: AdaptiveCardVisualizer
Application Version: 3.0.2206.2001

**Repro Steps:**
1. Open the Adaptive Card Visualizer application.
2. Navigate to the 'Save File' button present on header and activate it.
3. Press Esc key to close the dialog
4. Observe the issue.

**Actual Result:**
On pressing 'Esc' key to close the dialog, keyboard focus is not retaining back to the 'Save File' button.

**Expected Result:**
Keyboard focus should retain back to the 'Save file' button on pressing esc key to close the dialog.

**User Impact:**
Keyboard dependent user will get impacted as user will have difficulty in tracking the content or user have to use extra tabbing to navigate back on the content.

**MAS Reference link:**
https://liquid.microsoft.com/Web/Object/Read/MS.Accessibility/Requirements/02.04.03

**“Have feedback to share on Bugs?** Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-vaibgu%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400980259288%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=TrcBaCyAPKg0WAQfdSZJP2i9pghMEDg59i2NeUUs5EQ%3D&reserved=0) “

### Screenshots

https://user-images.githubusercontent.com/104483005/187380071-19fcf252-a2f3-4e00-a457-27c7cd9ed354.mp4

### Card JSON

```JSON
NA
```

**Comment by anna-dingler** [comment] 2023-04-17 16:49
Hi @vaishali1397,

I'm closing this issue because we do not release the UWP visualizer as an app for customers to use. We use this app for internal testing. Only accessibility issues found in the preview window will reach our customers because these are caused by the Adaptive Cards UWP rendering package.

Please let me know if you have any questions - thanks!

**Closed by anna-dingler** 2023-04-17 16:49 UTC
Labels: Bug, Area-Renderers, A11ySev2, A11yWCAG, HCL-E+D, HCL-AdaptiveCards-WPF, HCL-AdaptiveCards-Universal

**Comment by vaishali1397** [comment] 2023-05-01 06:26
Adding A11yTTValIdated tag and closing the issue as per below comment.
![image](https://user-images.githubusercontent.com/104483005/235416530-65fa9a8d-6249-4c15-88c2-a07d6e858468.png)
