### ISSUE TITLE
[Android][Accessibility][Input Validation] Input elements are not receiving focus after validation

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#5015] opened 2020-11-03 06:49 UTC
# Platform

- [ ] .NET HTML
- [ ] .NET WPF
- [X] Android
- [ ] iOS
- [ ] JavaScript
- [ ] UWP

# Version of SDK

2.3.0

# Details

Input.Time, Input.Date and compact Input.ChoiceSet input elements are not receiving focus when validation fails and those elements should be getting focus. 

Currently Input.Time and Input.Date can be fixed with custom rendering and some investigation is needed to determine a fix for compact ChoiceSet

**Comment by golddove** [comment] 2020-11-04 00:11
Closing as duplicate of #5020

**Closed** 2020-11-04 00:11 UTC
Labels: Area-Inconsistency, Bug, Priority-Now
