### ISSUE TITLE
Adaptive cards height

### ISSUE THREAD

**Issue by fplaten** [microsoft/AdaptiveCards#1781] opened 2018-08-09 07:49 UTC
# Platform

What platform is your issue or question related to? (Delete other platforms).

* JavaScript

# Author or host

Me

If you're an author, who are you sending cards to?

Directline webchat using BotFramework-Webchate

# Version of SDK

Adaptive Cards 1.0.0

# Issue

Since BotFramework-Webchate is using Adaptive Cards 1.0.0 I had an issue with the display of PromptChoice dialogs. 

The single choice had a height of 100% (see below).
![image](https://user-images.githubusercontent.com/6834102/38624298-096f2510-3da8-11e8-8348-98a7b7204253.png)

I managed to fix it by setting 
```css
.ac-pushButton {
        flex: 0 1 auto !important;
}
```

Another user reported a similar issue and mentioned it only happened in Çhrome for him. 
See https://github.com/Microsoft/BotFramework-WebChat/issues/933#issuecomment-408525094

**Comment by matthidinger** [comment] 2018-08-10 16:41
@dclaux any thoughts on this?

**Comment by dclaux** [comment] 2018-08-10 16:54
I posted my thoughts yesterday here: https://github.com/Microsoft/BotFramework-WebChat/issues/933

Let me paste them here.

I am not able to repro this problem in the visualizer, which uses the same rendering logic as WebChat. It seems to me that there is either a problem with how WebChat vertically sizes cards, or maybe some conflicting styling being applied.

As a side note, an Image can't have "height": "stretch", it should be "size": "stretch"

**Comment by dclaux** [comment] 2018-08-14 03:13
I think we have a solution for this, assuming the problem is caused by the height property of some element being set to stretch. See this PR: https://github.com/Microsoft/AdaptiveCards/pull/1795

**Comment by compulim** [comment] 2018-11-08 23:43
It might also related to #1794. The user was rendering AC using HTML4 layout (i.e. pages without `<!DOCTYPE html>`).

**Comment by jonmill** [comment] 2021-11-04 22:57
Closed as the bug is related to doctypes in IE11, which is unsupported

**Closed by jonmill** 2021-11-04 22:57 UTC
Labels: Bug, Area-Renderers, Platform-JavaScript
