### ISSUE TITLE
[JavaScript/NodeJS] Improve the rendered image quality for unsupported platforms

### ISSUE THREAD

**Issue by Kadae** [microsoft/AdaptiveCards#5421] opened 2021-02-24 11:04 UTC
Adaptive Cards so pixelated when renders in Bot Framework in image for Telegram (Telegram doesn't support it) in NodeJs.
Is there a way to improve the image quality on NodeJS?

**Comment by paulcam206** [comment] 2021-02-25 17:53
I can take a look here :)

**Comment by jonmill** [comment] 2021-05-13 20:34
Dupe of #5430

**Closed by jonmill** 2021-05-13 20:34 UTC
Labels: Bug, Resolution-Duplicate, Triage-Investigate
