### ISSUE TITLE
[Templating] Problem binding bool values with .NET AdaptiveCards.Templating v1.2.2

### ISSUE THREAD

**Issue by juna-gupta** [microsoft/AdaptiveCards#7064] opened 2022-02-24 08:29 UTC
### Target Application

MS Teams

### Application Operating System

Windows

### Schema Version

1.5

### Problem Description

**Package**: AdaptiveCards.Templating (.NET)
**version**: 1.2.2 
> Note v1.2.1 works fine.

If we consume AdaptiveCards.Templating v1.2.2 to bind bool variables to Adaptive card, it evaluates it as `True`/`False` which is an invalid value in JSON. It should evaluate bool variables/expressions as `true`/`false`.

We noticed this issue after upgrading to v1.2.2. Works fine with the previous version.

Sample AC
```
{
    "refresh": {
        "action": {
            "type": "Action.Execute",
            "verb": "RefreshCard",
            "data": {
                "shouldRefresh": "${shouldRefresh}",
            },
        }
    },
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "${title}"
        }],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5"
}
```

Sample code to bind data.
```

     var data = new
     {
          shouldRefresh = false,
          title = "Title"
      };

      var template = GetCardTemplate(RefreshAllUsersViewCardTemplatePath);
      var serializedJson = template.Expand(data); // bool variable is set to False in the serialized json.
```

### Expected Outcome

```
{
    "refresh": {
        "action": {
            "type": "Action.Execute",
            "verb": "RefreshCard",
            "data": {
                "shouldRefresh": false,
            },
        }
    },
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "Title"
        }],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5"
}
```

### Actual Outcome

```
{
    "refresh": {
        "action": {
            "type": "Action.Execute",
            "verb": "RefreshCard",
            "data": {
                "shouldRefresh": False,
            },
        }
    },
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "Title"
        }],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5"
}
```

### Card JSON

```JSON
{
    "refresh": {
        "action": {
            "type": "Action.Execute",
            "verb": "RefreshCard",
            "data": {
                "shouldRefresh": false,
            },
        }
    },
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "Title"
        }],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5"
}
```

### Repro Steps

1. Bind bool values to the Adaptive card using .NET AdaptiveCards.Template package v.1.2.2

**Comment by paulcam206** [comment] 2022-02-24 21:12
Closing as duplicate of #6854

**Closed by paulcam206** 2022-02-24 21:12 UTC
Labels: Bug, Area-Schema
