### ISSUE TITLE
Updated schema doc is missing enums

### ISSUE THREAD

**Issue by jsw** [Microsoft/AdaptiveCards#736] opened 2017-10-02 23:06 UTC
Intentional?

ImageSize, etc...

https://docs.microsoft.com/en-us/adaptive-cards/create/cardschema

**Comment by matthidinger** [comment] 2017-11-11 00:47
Known issue and will be resolved soon. In the mean time you can view all those properties using the [Schema explorer](adaptivecards.io/explorer/)

**Comment by matthidinger** [comment] 2017-11-11 01:08
Duplicate of #883

**Closed by matthidinger** 2017-11-11 01:08 UTC
Labels: Area-Documentation
