### ISSUE TITLE
Request: Inline GIFs/animated emojis within text

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2525] opened 2019-03-09 02:22 UTC
Ability to use an animated emoji/animojis and/or animated GIFs inside a string of text. Similar to the below, but animated.

<img width="432" alt="screen shot 2018-06-25 at 9 15 55 am" src="https://user-images.githubusercontent.com/1210985/41827236-907b8f0e-7858-11e8-8c3f-79c9f4377198.png">

# Asks

* Tyagit3 (#1645)

**Comment by salekh** [comment] 2020-06-05 11:25
Hi Contributors

Has there been any update on this issue yet?

**Comment by jonmill** [comment] 2021-05-06 20:38
Dupe of #3079

**Closed by jonmill** 2021-05-06 20:38 UTC
Labels: Area-Renderers, Request, Resolution-Duplicate, no-recent-activity
