### ISSUE TITLE
Input.Date  card is not rendering in IE but works in chrome

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/AdaptiveCards#859] opened 2017-10-27 02:41 UTC
![image](https://user-images.githubusercontent.com/2233628/32085645-109d6ba4-baee-11e7-8dda-af2c6837a59b.png)

the same card appears in chrome

![image](https://user-images.githubusercontent.com/2233628/32085718-611670d0-baee-11e7-93bf-93e205770efe.png)
If I remove the date field it renders the card in IE too...

**Comment by matthidinger** [comment] 2017-11-11 00:50
Duplicate of #519

**Closed by matthidinger** 2017-11-11 00:50 UTC
Labels: Area-Renderers, Platform-HTML
