### ISSUE TITLE
[MsTeams][Mobile] [Adaptive card - visibility false is not supporting on mobile device]

### ISSUE THREAD

**Issue by Sujit-Gaikwad** [microsoft/AdaptiveCards#3884] opened 2020-03-27 20:12 UTC
# Platform

What platform is your issue or question related to? (Delete other platforms).
[IsVisibileIssue_ios.txt](https://github.com/microsoft/AdaptiveCards/files/4395694/IsVisibileIssue_ios.txt)

* iOS

# Author or host
MsTeams

# Details

I am using adaptive card Visibility option to show some validation messages in card which i am doing by switching off the visibility at first and then turning it on whenever conditions are met.
It is working fine on teams desktop but when i'm trying this on mobile ios(using the same json), the card is not rendering properly.

Elements which are having visibility set as false are getting displayed on the card on ios devices which should not happen . I need this property to work on Ios devices as well because this is creating a roadblock in my project.
Please help.

**Comment by nesalang** [comment] 2020-03-30 23:12
@Sujit-Gaikwad 
There sometime is a gap between what is offered in SDK (AdaptiveCard) and  host app (Teams).
This feature works with SDK as demonstrated below.
<img width="348" alt="Screen Shot 2020-03-30 at 3 59 57 PM" src="https://user-images.githubusercontent.com/4112696/77970411-ff31a980-72a0-11ea-9ed3-1d9495d091b4.png">
With visibility set to true, it would look as below.
<img width="335" alt="Screen Shot 2020-03-30 at 4 01 09 PM" src="https://user-images.githubusercontent.com/4112696/77970438-0eb0f280-72a1-11ea-870d-c0e6f9dd9aa3.png">

I bring your concern to Teams' attention.

**Comment by swapnilarsh06** [comment] 2020-04-02 07:57
Even I see this issue. The issue is not with Text Block but with the Action.Submit (Cancel button). It always gets displayed in mobile.

**Comment by Sujit-Gaikwad** [comment] 2020-04-02 11:52
@nesalang thanks  for your comment.

@swapnilrsh06 we have found this issue on iOS device but the visibility issue for action button is for all mobile platforms.

**Comment by shalinijoshi19** [comment] 2020-04-03 16:48
Adding the new MSTeams-Developer-Support label for the Teams workflow bots to pick these up. @Wajeed-msft FYI

**Comment by nesalang** [comment] 2020-04-06 19:19
@swapnilarsh06 @Sujit-Gaikwad 
Hi, 
"isVisible" property is not supported feature in Actions.
Please take a look at [the documentation](https://adaptivecards.io/explorer/Action.OpenUrl.html)

@Aditya0603 @adumrewal 
Could you please let us know if "isVisible" property is currently supported in Mobile Versions? If not, could you please share the ETA?

Thank you.

**Comment by Subhasish-msft** [comment] 2020-04-07 07:55
@Sujit-Gaikwad , 
I am able to render the given adaptive card json in ios.

IsVisible: false
![image](https://user-images.githubusercontent.com/56869764/78643967-bf874500-78d2-11ea-8963-6d7a27effdfc.png)

IsVisible: true
![image](https://user-images.githubusercontent.com/56869764/78643877-9797e180-78d2-11ea-937d-feaec71b5f29.png)

Can you please share below details?
Ms Teams version in mobile: 
ios version:

FYI, I tried with MS Teams version (2.0.5) and ios version (13.3.1).

**Comment by Sujit-Gaikwad** [comment] 2020-04-07 08:00
Hi @Subhasish-msft,
This version of iOS and MS Teams app we are using
iphone 6
version - 12.4.5
ms teams app version - 2.0.2
ipad mini
version - 12.4.5
ms teams app version -2.0.2

**Comment by Subhasish-msft** [comment] 2020-04-07 10:27
@Sujit-Gaikwad ,
Can you please update to the latest version of Ms Teams and try again.

**Comment by Subhasish-msft** [comment] 2020-04-17 15:40
@Sujit-Gaikwad , Are you still facing this issue?

**Comment by Subhasish-msft** [comment] 2020-04-21 11:23
@Sujit-Gaikwad , Closing this issue. Please reopen if you still face this issue

**Closed by Subhasish-msft** 2020-04-21 11:23 UTC
Labels: Blocked-TeamsUpgrade1.2, Bug, MSTeams-Developer-Support, Msft-TeamsMobile, Platform-iOS
