### ISSUE TITLE
[iOS][Teams][Adaptivecard] GIF Support on ios device

### ISSUE THREAD

**Issue by Sujit-Gaikwad** [microsoft/AdaptiveCards#5753] opened 2021-04-30 05:35 UTC
# Target Platform
- iOS

# Target Application
- Teams

# Problem Description

As per my last bug #3886 is this issue got resolved. do we have GIF support for iOS teams platform

And one more clarity when we can we have v1.3 available for teams platform (All platform)

**Comment by Sujit-Gaikwad** [comment] 2021-05-03 05:44
Hi can anyone please look into the problem statement and give me answer on priority. 
this is really taking too much time answer simple questions. 
We need wanted to plan our activity accordingly. Excepecting Answer as soon as possible

**Comment by jwoo-msft** [comment] 2021-05-04 19:03
@Sujit-Gaikwad,
Gif is not an officially supported feature. We do have an open ticket for implementing this feature, it's tracked by  https://github.com/microsoft/AdaptiveCards/issues/5748

**Comment by Sujit-Gaikwad** [comment] 2021-05-05 06:52
@jwoo-msft  Thanks for reply. do we have any roadmap for this ??
Also Can please tell me is there any ETA available for adaptivecard v1.3 for all teams platform?

**Comment by jwoo-msft** [comment] 2021-05-05 18:12
If the v1.3 features you're looking for are not already supported, I believe by June, they will be all supported on all Teams platforms.

**Comment by jonmill** [comment] 2021-05-06 20:39
Closed as dupe of #3079

**Closed by jonmill** 2021-05-06 20:39 UTC
Labels: Area-Renderers, Bug, Resolution-Duplicate, Triage-Rejected
