### ISSUE TITLE
[iOS][Android] Alignment and possible placeholder rendering issues with ChoiceSet

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#5406] opened 2021-02-19 00:16 UTC
# Platform

iOS and Android were reported. We should verify against other platforms to see if any other platforms are affected.

# Details

This payload renders misaligned on Android (and possibly without `Input.ChoiceSet` placeholder at some sizes):

```json
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "body": [
        {
            "isVisible": true,
            "columns": [
                {
                    "items": [
                        {
                            "id": "country",
                            "choices": [
                                {
                                    "value": "Choice 1",
                                    "title": "Choice 1"
                                },
                                {
                                    "value": "Choice 2",
                                    "title": "Choice 2"
                                }
                            ],
                            "placeholder": "Pick a country code",
                            "type": "Input.ChoiceSet"
                        }
                    ],
                    "width": "stretch",
                    "type": "Column"
                },
                {
                    "items": [
                        {
                            "id": "NewPhoneNumber",
                            "placeholder": "Type the number here",
                            "type": "Input.Text"
                        }
                    ],
                    "width": "stretch",
                    "type": "Column"
                }
            ],
            "type": "ColumnSet"
        }
    ],
    "version": "1.0",
    "type": "AdaptiveCard"
}
```

Here's what the customer is seeing on Android:
![cust-and](https://user-images.githubusercontent.com/16614499/108438848-f3c2d600-7204-11eb-99de-79fd0d1501b9.png)

@golddove sees this locally on Android (placeholder works, but alignment still not great):
![image](https://user-images.githubusercontent.com/16614499/108438953-279dfb80-7205-11eb-8819-994f848c86a5.png)

**Comment by paulcam206** [comment] 2021-02-19 00:20
@jwoo-msft - are you able to repro this behavior on iOS?

**Comment by jwoo-msft** [comment] 2021-02-19 00:39
> @jwoo-msft - are you able to repro this behavior on iOS?

@paulcam206  No, I can't
![image](https://user-images.githubusercontent.com/4112696/108440361-d3484b00-7207-11eb-903b-17be570b45f8.png)

**Comment by golddove** [comment] 2021-02-19 01:08
@paulcam206 to be clear, the issue is that the choiceset seems to be too high (not vertically centered), right?

**Comment by paulcam206** [comment] 2021-02-19 01:12
Yeah, though we should double-check that we don't stop showing the placeholder if the content is sized smaller or something :)

**Comment by golddove** [comment] 2021-04-16 23:36
@lindach167 dug into this a little bit - please look at the suggestions below and let us know if they won't work for you

## Placeholder
As mentioned above, placeholder should be working (fixed by #4811)

## Vertical Alignment
Just double-checked, we are not doing anything special here. These are simply the default sizes of the native Android controls (namely, Spinner and EditText). You can see Google adds a [default top/bottom inset for EditText](https://android.googlesource.com/platform/frameworks/base/+/master/core/res/res/values/dimens_material.xml#124) but [none for Spinner](https://android.googlesource.com/platform/frameworks/base/+/master/core/res/res/drawable/spinner_background_material.xml). 

While the JS renderer does happen to have the same height for both, this is no longer true when you add Input.Toggle to the comparison:

![image](https://user-images.githubusercontent.com/4442788/115093317-e4e85f00-9ee7-11eb-9d71-95a1075a9535.png)

We can surely override the Android defaults and tweak padding/margin such that the two controls take up the exact same height, but this would involve putting magic numbers in our code that aren't configurable by the host. I don't believe this is the right approach.

### Mitigation Options

1. Card author should be advised to set `verticalContentAlignment: center` to get guaranteed alignment for any input/element, on all renderers, and all hosts (this is the ideal approach): <br/> 
![image](https://user-images.githubusercontent.com/4442788/115093532-a56e4280-9ee8-11eb-90ee-bcfa58de58ff.png)
1. If you (the host) would like all your cards' inputs to have the same height, simply subclass our implementations and explicitly set your desired heights/paddings/etc on the rendered view. I believe Teams already has subclasses for most Inputs, but let us know if you run into issues with that.

cc: @jonmill @paulcam206 (point 2 would be much easier for hosts if we ever get around to native styling on Android - #3830)

**Comment by linda167** [comment] 2021-04-16 23:42
@golddove Thank you I think the placeholder not working was the main customer complaint. Seems we can advise customers to use the suggestions you have here for fix alignment issues

**Comment by jonmill** [comment] 2021-04-22 20:14
Great, thanks folks!

**Closed by jonmill** 2021-04-22 20:14 UTC
Labels: Bug, Platform-Android, Platform-iOS, Triage-Investigate
