### ISSUE TITLE
OnlineMeeting JoinURL as Action does not work in AdaptiveCards

### ISSUE THREAD

**Issue by dawwa** [microsoft/AdaptiveCards#3497] opened 2019-09-27 21:38 UTC
Please note that this issue only applies to Meeting Join Url, regular conversation thread link works properly.

How to Repro:
1. In Microsoft Teams Client, create a MeetNow meeting with specifying a **Subject** in any channel.
2. Get the JoinUrl of the meeting
3. Create simple card to have an action button to open the JoinUrl
4. Send the card in Teams, and click the button
5. Reply the card with pasting the JoinUrl 

**Expected**:  Clicking the button should let user join the meeting, same as clicking on the latter raw link
**Actual**: Clicking the button does not redirect user to join the meeting, instead, it creates a new meeting at current channel, you can tell by not seeing the meeting subject you set previously.

{
    "type": "AdaptiveCard",
    "version": "1.0",
    "actions": [
    {
      "type": "Action.OpenUrl",
      "title": "Join This Meeting",
      "url": "{JoinUrl}"
    }
  ],
    "body": []
}

**Comment by shalinijoshi19** [comment] 2019-10-01 18:41
@siduppal offline comment: 
<snip>
       " There're bugs on meeting deeplinks on mobile currently. " 
</snip>

**Comment by Trinetra-MSFT** [comment] 2019-10-21 06:43
@dawwa, We have tested this for Teams desktop, web and mobile versions but could not able to reproduce. When we click on `Join This Meeting` button in adaptive card we are able to see the meeting room, Please take a look at screenshot

![image](https://user-images.githubusercontent.com/50989436/67182085-fc7e7e80-f3fb-11e9-804e-8d99fb2d1cfb.png)

![image](https://user-images.githubusercontent.com/50989436/67181948-9db90500-f3fb-11e9-8d35-84a34bdd41ee.png)

Could you please check your `joinUrl `and test it again?

**Comment by dawwa** [comment] 2019-10-25 17:35
this might be to the serialization/deserialization not sure from Teams side or AdaptiveCard side, as I noticed the Action.SubmitUrl turns to null after I transported the serialized card content through the wire.

**Comment by dawwa** [comment] 2020-03-19 23:37
ping for updates, as we really prefer actionable control rather than hyperlink for better UX

**Comment by okulygin** [comment] 2020-04-09 16:50
do we have any updates on this ?

**Comment by shalinijoshi19** [comment] 2020-09-08 18:43
@siduppal / @dawwa this isn't related to Teams Mobile though does seem specific to Teams at the moment --Do we have the corresponding Teams-side bug we can use to track this investigation and reference here? Following up offline on repro/debugging steps.

**Comment by shalinijoshi19** [comment] 2020-09-08 23:16
This is a feature request being tracked by Teams ADO item https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/720439; 
Per @siduppal from Teams, the ask is to enhance deeplink support in cards to allow join links..
Closing this issue out - @dawwa please do use the link above to track progress on this. Thanks

**Closed by shalinijoshi19** 2020-09-08 23:16 UTC
Labels: Bug, MsftTeams-Integration, Triage-External, no-recent-activity
