### ISSUE TITLE
Add underline support to RichTextBlock

### ISSUE THREAD

**Issue by dclaux** [microsoft/AdaptiveCards#3028] opened 2019-06-06 18:21 UTC
# Problem
RichTextBlock is quite powerful, but lack the basic ability to underline text.

# Solution
Add an underline property to TextRun.

**Comment by matthidinger** [comment] 2019-06-17 18:20
@andrewleader can you re-create through productboard

**Comment by andrewleader** [comment] 2019-06-17 20:46
Closing as dupe of #3051 (productboard unfortunately doesn't let us link an existing issue, we have to create a new one :/ we've sent a feature request to them to allow linking to existing)

**Closed by andrewleader** 2019-06-17 20:46 UTC
Labels: Feature
