### ISSUE TITLE
[UWP] Stretch background image not stretching

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#2840] opened 2019-05-03 21:12 UTC
# Platform

* UWP

# Issue

Background images in columns are not stretching (growing to fill the complete container). In the image below it can be seen in the first column as the image is not growing to fill

Json: 
* Samples\v1.2\Elements\Column.BackgroundImage.json 
* Samples\v1.2\Elements\Container.BackgroundImage.json 

![image](https://user-images.githubusercontent.com/35784165/57165865-2b049080-6dad-11e9-92f1-473c2d6d5e2d.png)

**Comment by shalinijoshi19** [comment] 2019-06-07 15:46
@RebeccaAnne FYI - Assigning to you for fixing.

**Comment by jonmill** [comment] 2021-11-08 21:56
Dupe of #2841

**Closed by jonmill** 2021-11-08 21:56 UTC
Labels: Bug, Triage-Approved for Fix, Resolution-By Design, no-recent-activity
