### ISSUE TITLE
[Feature Request] The time of iOS and Android should be consistent!!!

### ISSUE THREAD

**Issue by yanweida99** [microsoft/AdaptiveCards#8067] opened 2022-11-21 02:59 UTC
### Problem Statement

![image](https://user-images.githubusercontent.com/26455374/202953620-a38bb7e6-64c0-4486-80c4-6a2a94aeccd2.png)
![image (1)](https://user-images.githubusercontent.com/26455374/202953613-b98dbde7-9f6e-4996-ad0a-9a0deb6ddeae.png)
![image (2)](https://user-images.githubusercontent.com/26455374/202953619-1a52c6ff-11c9-4ee1-ae1c-00f766a3810d.png)
Sample 1:
From: 12:00 AM, To: 12:00 PM
The time(12:00 AM) is inconsistent with the data submitted by iOS and Android.

Sample 2:
From: 11:55 AM, To: 12:05 PM
Right!

### Proposed solution

The time of iOS and Android should be consistent!!!

**Comment by yanweida99** [comment] 2022-11-21 02:59
`{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.3",
  "body": [
    {
      "type": "Input.Time",
      "placeholder": "From",
      "id": "time_from"
    },
    {
      "type": "Input.Time",
      "placeholder": "To",
      "id": "time_to"
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "Set time",
      "data": {
        "id": "1234567890",
        "path": "set_effective_time"
      }
    }
  ]
}
`

This is my card json.

**Comment by paulcam206** [comment] 2022-11-29 21:27
Duplicate of #8076

**Closed by paulcam206** 2022-11-29 21:27 UTC
Labels: Request
