### ISSUE TITLE
[Javascript][Serialization] [Discrepancy between JS and C# lib handling of InputNumber->Value]

### ISSUE THREAD

**Issue by p-nagpal** [microsoft/AdaptiveCards#3829] opened 2020-03-09 23:39 UTC
# Platform
JavaScript

# Host
WebChat

# Version of SDK
Adaptive Cards JS lib (>= NPM version 1.2.3)

# Details
This problem comes from a [customer issue reported on GitHub](https://github.com/microsoft/BotFramework-Services/issues/185). 

We see that InputNumber->Value serialized in C# (Nuget version 1.2.4) cannot be rendered correctly by the Adaptive Cards JS lib (>= NPM version 1.2.3)

The C# library treats InputNumber->Value as a double while the JS library recently stopped accepting doubles (only strings are accepted). We picked up the change when WebChat upgraded adaptive cards JS lib from 1.2.0 to 1.2.3. 

Could you help us?

**Comment by Chekrii** [comment] 2020-04-30 01:35
Hello @shalinijoshi19, So after this fix Input.Number will accept string and special characters as well?

**Comment by dclaux** [comment] 2020-04-30 02:06
@shalinijoshi19 we first need to reconcile with this issue: https://github.com/microsoft/AdaptiveCards/issues/3171

The JS library used to accept both number and string, for both the value property as well as min and max. The change was made to only accept numbers in order to be consistent with the UWP renderer as per the issue I linked above.

Also, we need to treat value, min and max the same way.

**Comment by shalinijoshi19** [comment] 2020-05-28 14:19
@Paulcam206 am moving this out of the 20.05 patch release. Also since you are stretched thin at the moment, am taking this off your plate for load balancing out for now..

**Comment by v-kydela** [comment] 2020-10-26 18:54
@dclaux - There seems to be some inconsistency here. You said:

> The change was made to only accept numbers in order to be consistent with the UWP renderer as per the issue I linked above.

But @p-nagpal said:

> the JS library recently stopped accepting doubles (only strings are accepted).

Can you clarify whether only numbers are accepted or only strings are accepted?

**Comment by dclaux** [comment] 2020-10-26 19:12
@v-kydela the JS SDK only accepts `number` for the `value`, `min` and `max` properties of an Input.Number. It used to accept both `number` and `string`. And it accepts integers as well as decimals.

**Comment by v-kydela** [comment] 2020-10-27 00:02
@dclaux - Well then it's very strange that people are reporting that the `value` property only accepts a string

**Comment by dclaux** [comment] 2020-11-04 22:27
I can confirm that the fix to this problem is for WebChat to update to the AC JS SDK v2.0 or later

**Comment by dclaux** [comment] 2020-11-04 22:30
@v-kydela BTW my memory was indeed wrong, and earlier versions of the SDK only did accept string, not number. Apologies for the confusion.

**Comment by shalinijoshi19** [comment] 2020-12-04 14:00
This is now resolved per comments above.

**Closed by shalinijoshi19** 2020-12-04 14:00 UTC
Labels: Area-Inconsistency, Bug, Platform-HTML, Triage-Approved for Fix, javascript
