### ISSUE TITLE
Name property does not defined for “Date" and "Time" editable text boxes from all card inputs data

### ISSUE THREAD

**Issue by JasonAment** [microsoft/AdaptiveCards#2237] opened 2018-12-14 22:00 UTC
Repro steps and video for this bug can be found at:
https://github.com/Microsoft/BotFramework-WebChat/issues/1347

**Comment by shalinijoshi19** [comment] 2020-04-13 18:15
@shalinijoshi19 to follow up on potential dup that @dclaux triaged in ADO last week.

**Comment by paulcam206** [comment] 2020-05-27 20:36
Looks like #2256 is a duplicate of this bug, which is the bug I've been tracking/working against.

**Closed by paulcam206** 2020-05-27 20:36 UTC
Labels: Area-Accessibility, Bug, HealthBotBlocker, MsftBot-Integration, Platform-HTML, Priority-Normal, Triage-Investigate, javascript
