### ISSUE TITLE
IE11 rendering issue

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/AdaptiveCards#680] opened 2017-09-25 03:23 UTC
Date field is not working well in IE11 but working in Chrome...
![image](https://user-images.githubusercontent.com/2233628/30790434-7d31e990-a1c9-11e7-8aa5-3c06d8878b78.png)

Chrome renders as below
![image](https://user-images.githubusercontent.com/2233628/30791268-f8188cea-a1ce-11e7-9a58-85d720b86bf1.png)

**Comment by matthidinger** [comment] 2017-11-11 00:43
Duplicate of #519

**Closed by matthidinger** 2017-11-11 00:43 UTC
