### ISSUE TITLE
UI/UX update to change from 6 Widgets options to have light/dark and s/m/l menus

### ISSUE THREAD

**Issue by KesemZ** [microsoft/AdaptiveCards#7538] opened 2022-06-15 04:59 UTC

**Comment by anna-dingler** [comment] 2022-07-14 21:27
@KesemZ 

How will this relate to #7540?

If we allow the user to view all 6 modes at once, does that make the light/dark and small/medium/large menus obsolete?

**Comment by anna-dingler** [comment] 2022-07-14 22:26
Closing since it is a duplicate of #7540

**Closed by anna-dingler** 2022-07-14 22:26 UTC
Labels: Feature, Partner-MsftTeams, Partner-MsftTeamsMobile, Area-Designer
