### ISSUE TITLE
JavaScript library does not natively support markdown, and third-party libs are too permissive

### ISSUE THREAD

**Issue by riarenas** [microsoft/AdaptiveCards#910] opened 2017-11-08 21:10 UTC
This sample has a lot of markdown syntax that shouldn't be supported according to the docs.
```json
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "## Markdown Headers should not be supported"
        },
        {
            "type": "TextBlock",
            "text": "___"
        },
        {
            "type": "TextBlock",
            "text": "Neither should horizontal rules"
        },
        {
            "type": "TextBlock",
            "text": "Some of my spaces are being eaten up by the         markdown parser"
        },
        {
            "type": "TextBlock",
            "text": "~~Strikethrough should not be supported.~~"
        },
        {
            "type": "TextBlock",
            "text": ">Quote blocks should be ignored"
        },
        {
            "type": "TextBlock",
            "text": "Markdown | Tables | Work\n:--- | :---: | ---:\n*And* | change | **horizontal alignment**\n1 | 2 | 3"
        },
        {
            "type": "TextBlock",
            "text": "    This one I don't really understand"
        },
        {
            "type": "TextBlock",
            "text": "````\nBut Seems to be a shortcut for code blocks, which should be ignored."
        }
    ]
}
```

Renders as:

![image](https://user-images.githubusercontent.com/23242101/32574446-1ce974c4-c486-11e7-9db6-cc4eb5e7d274.png)

**Comment by riarenas** [comment] 2017-11-08 21:51
Inline images also work via markdown:
```Json
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "![alt text](https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png \"Logo Title Text 1\")"
        }
    ]
}
```
renders as 

![image](https://user-images.githubusercontent.com/23242101/32576456-df4fc9f0-c48b-11e7-8604-996b4878469c.png)

**Comment by dclaux** [comment] 2017-11-10 04:28
This one is interesting:
- Best way to do this would be to tell the Markdown processing library to not handle some aspects of Markdown. I am not sure such a library exists
- Even if it does, we have been talking about removing the Markdown-it (or any other markdown library)dependency from the TypeScript renderer and instead leave it to the host to process markdown. But then it becomes the responsibility of every host to only support the subset of markdown Adaptive is supposed to allow

So, how can we address this?

**Comment by matthidinger** [comment] 2017-11-10 05:32
For .NET we forked a library and customized it. For the iOS/Android/UWP we are working through options, including writing a shared parser/implementation in our C++ layer. There are plenty of references out there, it seems like rolling our own given the very limited set of markdown options might be the best way to go?

**Comment by synk** [comment] 2017-11-24 09:55
we've found implementing markdown subset is not easy work :tired_face:
even if the spec becomes clear, it is difficult to use existing library.

I think adaptivecards is expressive enough even without markdown support
e.g.
* `selectAction` instead of markdown hyperlink
* `facts` and `columns` instead of markdown list

on the other hand, i hope auto linebreak and inline text emphasis feature since these are most wanted features by our developers.
but other markdown features can be replaced by adaptivecards itself.

**Comment by shalinijoshi19** [comment] 2019-04-15 17:10
@andrewleader / @matthidinger / @paulcam206/ @dclaux  is this addressed with 1.2 changes all up across all platforms? What should be the expected behavior wrt markdown in textblocks and richtextblocks resp with 1.2?

**Comment by andrewleader** [comment] 2019-04-15 18:08
No, this isn't addressed, but it's something we need to do. This inconsistent behavior leads to confusion. Users expect that what you see in the designer is what you get everywhere else.

**Comment by dclaux** [comment] 2019-04-15 18:15
Problem is we may not be able to control it unless we provide a built-in Markdown processor. We don't load markdown-it, and I'm not sure we can reconfigure it after it's been loaded by the host application. Plus, using Markdown-it isn't a requirement.

**Comment by shalinijoshi19** [comment] 2019-04-15 18:20
I'll table this in that case for 1.3 addressing. @andrewleader what are teh next steps here for this to result in a Markdown-related requierments spec for 1.3 ? THanks!

**Comment by shalinijoshi19** [comment] 2019-04-15 19:07
Working with @andrewleader to create a "parent" "Markdown support in TextBox" task/issue for 1.3

**Comment by shalinijoshi19** [comment] 2019-04-15 23:40
@dclaux FYI likely moving this to 1.3 (adding a checkbox that lets textbox element have the option to "opt-out" of markdown

**Comment by matthidinger** [comment] 2019-04-15 23:41
FYI the ReactNative team did in fact implement their own markdown processor. @vasanth-s can provide details. Ideally we could use the same or similar code in the plain JS renderer to bundle official AC markdown support in the renderer

**Comment by Surezt22** [comment] 2019-04-17 18:40
[This](https://github.com/Microsoft/AdaptiveCards/blob/master/source/community/reactnative/src/utils/markdown-formatter.js) is the markdown parser we are using for our react-native implementation. Currently, it supports the below 5 types:

- Bold
- Italic 
- Ordered List
- Unordered List
- Link

You can refer the same to support web-based markdown processor. In case, if you need any help, we are happy to work on that.

**Comment by shalinijoshi19** [comment] 2019-06-19 18:52
No immediate requirement to do this at this point. Chatted with @dclaux ; moving this out to our backlog to revisit.

**Comment by jonmill** [comment] 2021-11-04 20:57
Tracked by #1984

**Closed by jonmill** 2021-11-04 20:57 UTC
Labels: Bug, Area-Renderers, Platform-JavaScript, Triage-Approved for Fix, Area-Inconsistency, Area-Markdown
