### ISSUE TITLE
[Adaptive Card-Schema Explorer- Input.Date]: Text Spacing is not getting applied for the content in calendar pop-up.

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7301] opened 2022-04-29 22:53 UTC
https://microsoft.visualstudio.com/OS/_workitems/edit/37643063

**Comment by vagpt** [comment] 2023-12-24 08:36
HI @anna-dingler,

Could you please provide update regarding any future plan to fix this issue?

Issue is still repro. Please refer to below details for reference.

Test Environment:
OS Build: Windows 11 23H2 (OS Build 25997.1000)
Browser: Edge Dev Version 121.0.2277.4 (Official build) dev (64-bit)
URL: https://adaptivecards.io/explorer/Input.Date.html
Tool: Stylus

Repro Steps:
Open the above URL.
Schema Explore Input.Date Page will be appear.
Turn on the Stylus tool.
Navigate to Date Input field in Adaptive Card and activate it.
Calendar Pop-up will be appear.
Verify that text Spacing is getting applied for the content in calendar pop-up or not.

Actual:
Text Spacing is not getting applied for the content in calendar pop-up.

Expected:
Text Spacing should get applied for the content in calendar pop-up.

User Impact:
Users with dyslexia and low vision who need to increase space between text to make a better experience will be impacted if text get hidden after applying such techniques.

MAS Reference:
[MAS 1.4.12 - Text Spacing](https://nam06.safelinks.protection.outlook.com/ap/w-59584e83/?url=https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/Doc.aspx?sourcedoc%3D%257B645DCC70-F94C-462D-A91E-10DBE9E5C946%257D%26file%3DMAS%25201.4.12%2520%25E2%2580%2593%2520Text%2520Spacing.docx%26action%3Ddefault%26mobileredirect%3Dtrue&data=02%7c01%7cv-raku31%40microsoft.com%7cc08d0b4607df4964361308d810fc6589%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637278023593903667&sdata=/A83TShGmKVNM8kllPgygHVBw9VnkEEwODAmfUrO3oo%3D&reserved=0)


“Have feedback to share on Bugs ? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fforms.office.com%2fpages%2fresponsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-lalapati%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656401002888328%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=9rKyqggThK5iHRPhG9iMiNp6zSq%2BYr%2fr4gmiXwwFsnM%3D&reserved=0) “

**Comment by anna-dingler** [comment] 2024-01-02 18:05
Closing this issue since it is a duplicate of https://github.com/microsoft/AdaptiveCards/issues/7715

**Closed by anna-dingler** 2024-01-02 18:05 UTC
Labels: Bug, Area-Accessibility, A11ySev3, A11yWCAG, HCL-E+D, Product-AC, HCL-AdaptiveCards-Web, A11yTTValidated, AdaptiveCards_Web, A11yMissing_HCLReviewed, MissingReviewedDeprecated

**Comment by vagpt** [comment] 2024-01-03 05:08
As per the comment above adding A11yTTValidated tag.
